//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirectN
{
	/// <summary>
	/// WebdingsGlyph Enums.
	/// </summary>
	public enum WebdingsGlyphEnum
	{
		/// <summary>
		/// Device Control Four.
		/// </summary>
		DeviceControlFour = 0x0014,

		/// <summary>
		/// Spider.
		/// </summary>
		Spider = 0x0021,

		/// <summary>
		/// Spider Web.
		/// </summary>
		SpiderWeb = 0x0022,

		/// <summary>
		/// No Piracy.
		/// </summary>
		NoPiracy = 0x0023,

		/// <summary>
		/// Dark Sunglasses.
		/// </summary>
		DarkSunglasses = 0x0024,

		/// <summary>
		/// Trophy.
		/// </summary>
		Trophy = 0x0025,

		/// <summary>
		/// Military Medal.
		/// </summary>
		MilitaryMedal = 0x0026,

		/// <summary>
		/// Linked Paperclips.
		/// </summary>
		LinkedPaperclips = 0x0027,

		/// <summary>
		/// Left Speech Bubble.
		/// </summary>
		LeftSpeechBubble = 0x0028,

		/// <summary>
		/// Right Speech Bubble.
		/// </summary>
		RightSpeechBubble = 0x0029,

		/// <summary>
		/// Mood Bubble.
		/// </summary>
		MoodBubble = 0x002a,

		/// <summary>
		/// Lightning Mood Bubble.
		/// </summary>
		LightningMoodBubble = 0x002b,

		/// <summary>
		/// Hot Pepper.
		/// </summary>
		HotPepper = 0x002c,

		/// <summary>
		/// Reminder Ribbon.
		/// </summary>
		ReminderRibbon = 0x002d,

		/// <summary>
		/// Checker Board.
		/// </summary>
		CheckerBoard = 0x002e,

		/// <summary>
		/// Very Heavy Solidus.
		/// </summary>
		VeryHeavySolidus = 0x002f,

		/// <summary>
		/// Minimize.
		/// </summary>
		Minimize = 0x0030,

		/// <summary>
		/// Maximize.
		/// </summary>
		Maximize = 0x0031,

		/// <summary>
		/// Overlap.
		/// </summary>
		Overlap = 0x0032,

		/// <summary>
		/// Black Medium Left-Pointing Triangle.
		/// </summary>
		BlackMediumLeftPointingTriangle = 0x0033,

		/// <summary>
		/// Black Medium Right-Pointing Triangle.
		/// </summary>
		BlackMediumRightPointingTriangle = 0x0034,

		/// <summary>
		/// Black Medium Up-Pointing Triangle.
		/// </summary>
		BlackMediumUpPointingTriangle = 0x0035,

		/// <summary>
		/// Black Medium Down-Pointing Triangle.
		/// </summary>
		BlackMediumDownPointingTriangle = 0x0036,

		/// <summary>
		/// Black Left-Pointing Double Triangle.
		/// </summary>
		BlackLeftPointingDoubleTriangle = 0x0037,

		/// <summary>
		/// Black Right-Pointing Double Triangle.
		/// </summary>
		BlackRightPointingDoubleTriangle = 0x0038,

		/// <summary>
		/// Black Left-Pointing Double Triangle With Vertical Bar.
		/// </summary>
		BlackLeftPointingDoubleTriangleWithVerticalBar = 0x0039,

		/// <summary>
		/// Black Right-Pointing Double Triangle With Vertical Bar.
		/// </summary>
		BlackRightPointingDoubleTriangleWithVerticalBar = 0x003a,

		/// <summary>
		/// Double Vertical Bar.
		/// </summary>
		DoubleVerticalBar = 0x003b,

		/// <summary>
		/// Black Square For Stop.
		/// </summary>
		BlackSquareForStop = 0x003c,

		/// <summary>
		/// Black Circle For Record.
		/// </summary>
		BlackCircleForRecord = 0x003d,

		/// <summary>
		/// Increase Font Size Symbol.
		/// </summary>
		IncreaseFontSizeSymbol = 0x003e,

		/// <summary>
		/// Ballot Box With Ballot.
		/// </summary>
		BallotBoxWithBallot = 0x003f,

		/// <summary>
		/// Hammer And Wrench.
		/// </summary>
		HammerAndWrench = 0x0040,

		/// <summary>
		/// Building Construction.
		/// </summary>
		BuildingConstruction = 0x0041,

		/// <summary>
		/// House Buildings.
		/// </summary>
		HouseBuildings = 0x0042,

		/// <summary>
		/// Cityscape.
		/// </summary>
		Cityscape = 0x0043,

		/// <summary>
		/// Derelict House Building.
		/// </summary>
		DerelictHouseBuilding = 0x0044,

		/// <summary>
		/// Desert.
		/// </summary>
		Desert = 0x0045,

		/// <summary>
		/// Factory.
		/// </summary>
		Factory = 0x0046,

		/// <summary>
		/// Classical Building.
		/// </summary>
		ClassicalBuilding = 0x0047,

		/// <summary>
		/// House Building.
		/// </summary>
		HouseBuilding = 0x0048,

		/// <summary>
		/// Beach With Umbrella.
		/// </summary>
		BeachWithUmbrella = 0x0049,

		/// <summary>
		/// Desert Island.
		/// </summary>
		DesertIsland = 0x004a,

		/// <summary>
		/// Motorway.
		/// </summary>
		Motorway = 0x004b,

		/// <summary>
		/// Left-Pointing Magnifying Glass.
		/// </summary>
		LeftPointingMagnifyingGlass = 0x004c,

		/// <summary>
		/// Snow Capped Mountain.
		/// </summary>
		SnowCappedMountain = 0x004d,

		/// <summary>
		/// Eye.
		/// </summary>
		Eye = 0x004e,

		/// <summary>
		/// Ear.
		/// </summary>
		Ear = 0x004f,

		/// <summary>
		/// National Park.
		/// </summary>
		NationalPark = 0x0050,

		/// <summary>
		/// Camping.
		/// </summary>
		Camping = 0x0051,

		/// <summary>
		/// Railway Track.
		/// </summary>
		RailwayTrack = 0x0052,

		/// <summary>
		/// Stadium.
		/// </summary>
		Stadium = 0x0053,

		/// <summary>
		/// Passenger Ship.
		/// </summary>
		PassengerShip = 0x0054,

		/// <summary>
		/// Bullhorn With Sound Waves.
		/// </summary>
		BullhornWithSoundWaves = 0x0055,

		/// <summary>
		/// Bullhorn.
		/// </summary>
		Bullhorn = 0x0056,

		/// <summary>
		/// Right Speaker.
		/// </summary>
		RightSpeaker = 0x0057,

		/// <summary>
		/// Speaker.
		/// </summary>
		Speaker = 0x0058,

		/// <summary>
		/// Heart With Tip On The Left.
		/// </summary>
		HeartWithTipOnTheLeft = 0x0059,

		/// <summary>
		/// Bouquet Of Flowers.
		/// </summary>
		BouquetOfFlowers = 0x005a,

		/// <summary>
		/// Left Thought Bubble.
		/// </summary>
		LeftThoughtBubble = 0x005b,

		/// <summary>
		/// Very Heavy Reverse Solidus.
		/// </summary>
		VeryHeavyReverseSolidus = 0x005c,

		/// <summary>
		/// Right Thought Bubble.
		/// </summary>
		RightThoughtBubble = 0x005d,

		/// <summary>
		/// Two Speech Bubbles.
		/// </summary>
		TwoSpeechBubbles = 0x005e,

		/// <summary>
		/// Three Speech Bubbles.
		/// </summary>
		ThreeSpeechBubbles = 0x005f,

		/// <summary>
		/// Four Corner Arrows Circling Anticlockwise.
		/// </summary>
		FourCornerArrowsCirclingAnticlockwise = 0x0060,

		/// <summary>
		/// Heavy Check Mark.
		/// </summary>
		HeavyCheckMark = 0x0061,

		/// <summary>
		/// Bicycle.
		/// </summary>
		Bicycle = 0x0062,

		/// <summary>
		/// White Square.
		/// </summary>
		WhiteSquare = 0x0063,

		/// <summary>
		/// Shield.
		/// </summary>
		Shield = 0x0064,

		/// <summary>
		/// Package.
		/// </summary>
		Package = 0x0065,

		/// <summary>
		/// Oncoming Fire Engine.
		/// </summary>
		OncomingFireEngine = 0x0066,

		/// <summary>
		/// Black Square.
		/// </summary>
		BlackSquare = 0x0067,

		/// <summary>
		/// Ambulance.
		/// </summary>
		Ambulance = 0x0068,

		/// <summary>
		/// Circled Information Source.
		/// </summary>
		CircledInformationSource = 0x0069,

		/// <summary>
		/// Small Airplane.
		/// </summary>
		SmallAirplane = 0x006a,

		/// <summary>
		/// Satellite.
		/// </summary>
		Satellite = 0x006b,

		/// <summary>
		/// Reverse Light Four Pointed Pinwheel Star.
		/// </summary>
		ReverseLightFourPointedPinwheelStar = 0x006c,

		/// <summary>
		/// Man In Business Suit Levitating.
		/// </summary>
		ManInBusinessSuitLevitating = 0x006d,

		/// <summary>
		/// Medium Black Circle.
		/// </summary>
		MediumBlackCircle = 0x006e,

		/// <summary>
		/// Motor Boat.
		/// </summary>
		MotorBoat = 0x006f,

		/// <summary>
		/// Oncoming Police Car.
		/// </summary>
		OncomingPoliceCar = 0x0070,

		/// <summary>
		/// Clockwise Right And Left Semicircle Arrows.
		/// </summary>
		ClockwiseRightAndLeftSemicircleArrows = 0x0071,

		/// <summary>
		/// Cancellation X.
		/// </summary>
		CancellationX = 0x0072,

		/// <summary>
		/// Black Question Mark Ornament.
		/// </summary>
		BlackQuestionMarkOrnament = 0x0073,

		/// <summary>
		/// Diesel Locomotive.
		/// </summary>
		DieselLocomotive = 0x0074,

		/// <summary>
		/// Metro.
		/// </summary>
		Metro = 0x0075,

		/// <summary>
		/// Oncoming Bus.
		/// </summary>
		OncomingBus = 0x0076,

		/// <summary>
		/// Flag In Hole.
		/// </summary>
		FlagInHole = 0x0077,

		/// <summary>
		/// Prohibited Sign.
		/// </summary>
		ProhibitedSign = 0x0078,

		/// <summary>
		/// Circled Minus.
		/// </summary>
		CircledMinus = 0x0079,

		/// <summary>
		/// No Smoking Symbol.
		/// </summary>
		NoSmokingSymbol = 0x007a,

		/// <summary>
		/// Left Anger Bubble.
		/// </summary>
		LeftAngerBubble = 0x007b,

		/// <summary>
		/// Vertical Line.
		/// </summary>
		VerticalLine = 0x007c,

		/// <summary>
		/// Right Anger Bubble.
		/// </summary>
		RightAngerBubble = 0x007d,

		/// <summary>
		/// Lightning Mood.
		/// </summary>
		LightningMood = 0x007e,

		/// <summary>
		/// Mens Symbol.
		/// </summary>
		MensSymbol = 0x0080,

		/// <summary>
		/// Womens Symbol.
		/// </summary>
		WomensSymbol = 0x0081,

		/// <summary>
		/// Boys Symbol.
		/// </summary>
		BoysSymbol = 0x0082,

		/// <summary>
		/// Girls Symbol.
		/// </summary>
		GirlsSymbol = 0x0083,

		/// <summary>
		/// Baby Symbol.
		/// </summary>
		BabySymbol = 0x0084,

		/// <summary>
		/// Extraterrestrial Alien.
		/// </summary>
		ExtraterrestrialAlien = 0x0085,

		/// <summary>
		/// Weight Lifter.
		/// </summary>
		WeightLifter = 0x0086,

		/// <summary>
		/// Skier.
		/// </summary>
		Skier = 0x0087,

		/// <summary>
		/// Snowboarder.
		/// </summary>
		Snowboarder = 0x0088,

		/// <summary>
		/// Golfer.
		/// </summary>
		Golfer = 0x0089,

		/// <summary>
		/// Swimmer.
		/// </summary>
		Swimmer = 0x008a,

		/// <summary>
		/// Surfer.
		/// </summary>
		Surfer = 0x008b,

		/// <summary>
		/// Racing Motorcycle.
		/// </summary>
		RacingMotorcycle = 0x008c,

		/// <summary>
		/// Racing Car.
		/// </summary>
		RacingCar = 0x008d,

		/// <summary>
		/// Oncoming Automobile.
		/// </summary>
		OncomingAutomobile = 0x008e,

		/// <summary>
		/// Stock Chart.
		/// </summary>
		StockChart = 0x008f,

		/// <summary>
		/// Oil Drum.
		/// </summary>
		OilDrum = 0x0090,

		/// <summary>
		/// Money Bag.
		/// </summary>
		MoneyBag = 0x0091,

		/// <summary>
		/// Label.
		/// </summary>
		Label = 0x0092,

		/// <summary>
		/// Credit Card.
		/// </summary>
		CreditCard = 0x0093,

		/// <summary>
		/// Family.
		/// </summary>
		Family = 0x0094,

		/// <summary>
		/// Dagger Knife.
		/// </summary>
		DaggerKnife = 0x0095,

		/// <summary>
		/// Lips.
		/// </summary>
		Lips = 0x0096,

		/// <summary>
		/// Speaking Head In Silhouette.
		/// </summary>
		SpeakingHeadInSilhouette = 0x0097,

		/// <summary>
		/// Pinwheel Star.
		/// </summary>
		PinwheelStar = 0x0098,

		/// <summary>
		/// Envelope With Lightning.
		/// </summary>
		EnvelopeWithLightning = 0x0099,

		/// <summary>
		/// Flying Envelope.
		/// </summary>
		FlyingEnvelope = 0x009a,

		/// <summary>
		/// Stamped Envelope.
		/// </summary>
		StampedEnvelope = 0x009b,

		/// <summary>
		/// Pen Over Stamped Envelope.
		/// </summary>
		PenOverStampedEnvelope = 0x009c,

		/// <summary>
		/// Document With Text.
		/// </summary>
		DocumentWithText = 0x009d,

		/// <summary>
		/// Document With Text And Picture.
		/// </summary>
		DocumentWithTextAndPicture = 0x009e,

		/// <summary>
		/// Document With Picture.
		/// </summary>
		DocumentWithPicture = 0x009f,

		/// <summary>
		/// Sleuth Or Spy.
		/// </summary>
		SleuthOrSpy = 0x00a0,

		/// <summary>
		/// Mantelpiece Clock.
		/// </summary>
		MantelpieceClock = 0x00a1,

		/// <summary>
		/// Frame With Tiles.
		/// </summary>
		FrameWithTiles = 0x00a2,

		/// <summary>
		/// Frame With An X.
		/// </summary>
		FrameWithAnX = 0x00a3,

		/// <summary>
		/// Clipboard.
		/// </summary>
		Clipboard = 0x00a4,

		/// <summary>
		/// Spiral Note Pad.
		/// </summary>
		SpiralNotePad = 0x00a5,

		/// <summary>
		/// Spiral Calendar Pad.
		/// </summary>
		SpiralCalendarPad = 0x00a6,

		/// <summary>
		/// Open Book.
		/// </summary>
		OpenBook = 0x00a7,

		/// <summary>
		/// Books.
		/// </summary>
		Books = 0x00a8,

		/// <summary>
		/// Rolled-Up Newspaper.
		/// </summary>
		RolledUpNewspaper = 0x00a9,

		/// <summary>
		/// Page With Circled Text.
		/// </summary>
		PageWithCircledText = 0x00aa,

		/// <summary>
		/// Card File Box.
		/// </summary>
		CardFileBox = 0x00ab,

		/// <summary>
		/// Card Index Dividers.
		/// </summary>
		CardIndexDividers = 0x00ac,

		/// <summary>
		/// Frame With Picture.
		/// </summary>
		FrameWithPicture = 0x00ad,

		/// <summary>
		/// Performing Arts.
		/// </summary>
		PerformingArts = 0x00ae,

		/// <summary>
		/// Beamed Ascending Musical Notes.
		/// </summary>
		BeamedAscendingMusicalNotes = 0x00af,

		/// <summary>
		/// Musical Keyboard With Jacks.
		/// </summary>
		MusicalKeyboardWithJacks = 0x00b0,

		/// <summary>
		/// Studio Microphone.
		/// </summary>
		StudioMicrophone = 0x00b1,

		/// <summary>
		/// Headphone.
		/// </summary>
		Headphone = 0x00b2,

		/// <summary>
		/// Optical Disc.
		/// </summary>
		OpticalDisc = 0x00b3,

		/// <summary>
		/// Film Frames.
		/// </summary>
		FilmFrames = 0x00b4,

		/// <summary>
		/// Camera.
		/// </summary>
		Camera = 0x00b5,

		/// <summary>
		/// Admission Tickets.
		/// </summary>
		AdmissionTickets = 0x00b6,

		/// <summary>
		/// Clapper Board.
		/// </summary>
		ClapperBoard = 0x00b7,

		/// <summary>
		/// Film Projector.
		/// </summary>
		FilmProjector = 0x00b8,

		/// <summary>
		/// Video Camera.
		/// </summary>
		VideoCamera = 0x00b9,

		/// <summary>
		/// Portable Stereo.
		/// </summary>
		PortableStereo = 0x00ba,

		/// <summary>
		/// Radio.
		/// </summary>
		Radio = 0x00bb,

		/// <summary>
		/// Level Slider.
		/// </summary>
		LevelSlider = 0x00bc,

		/// <summary>
		/// Control Knobs.
		/// </summary>
		ControlKnobs = 0x00bd,

		/// <summary>
		/// Television.
		/// </summary>
		Television = 0x00be,

		/// <summary>
		/// Personal Computer.
		/// </summary>
		PersonalComputer = 0x00bf,

		/// <summary>
		/// Desktop Computer.
		/// </summary>
		DesktopComputer = 0x00c0,

		/// <summary>
		/// Keyboard And Mouse.
		/// </summary>
		KeyboardAndMouse = 0x00c1,

		/// <summary>
		/// Three Networked Computers.
		/// </summary>
		ThreeNetworkedComputers = 0x00c2,

		/// <summary>
		/// Joystick.
		/// </summary>
		Joystick = 0x00c3,

		/// <summary>
		/// Video Game.
		/// </summary>
		VideoGame = 0x00c4,

		/// <summary>
		/// Left Hand Telephone Receiver.
		/// </summary>
		LeftHandTelephoneReceiver = 0x00c5,

		/// <summary>
		/// Telephone Receiver With Page.
		/// </summary>
		TelephoneReceiverWithPage = 0x00c6,

		/// <summary>
		/// Pager.
		/// </summary>
		Pager = 0x00c7,

		/// <summary>
		/// Clamshell Mobile Phone.
		/// </summary>
		ClamshellMobilePhone = 0x00c8,

		/// <summary>
		/// Telephone On Top Of Modem.
		/// </summary>
		TelephoneOnTopOfModem = 0x00c9,

		/// <summary>
		/// Printer.
		/// </summary>
		Printer = 0x00ca,

		/// <summary>
		/// Pocket Calculator.
		/// </summary>
		PocketCalculator = 0x00cb,

		/// <summary>
		/// Black Folder.
		/// </summary>
		BlackFolder = 0x00cc,

		/// <summary>
		/// Black Hard Shell Floppy Disk.
		/// </summary>
		BlackHardShellFloppyDisk = 0x00cd,

		/// <summary>
		/// Compression.
		/// </summary>
		Compression = 0x00ce,

		/// <summary>
		/// Lock.
		/// </summary>
		Lock = 0x00cf,

		/// <summary>
		/// Open Lock.
		/// </summary>
		OpenLock = 0x00d0,

		/// <summary>
		/// Old Key.
		/// </summary>
		OldKey = 0x00d1,

		/// <summary>
		/// Inbox Tray.
		/// </summary>
		InboxTray = 0x00d2,

		/// <summary>
		/// North East Pointing Leaf.
		/// </summary>
		NorthEastPointingLeaf = 0x00d3,

		/// <summary>
		/// Hole.
		/// </summary>
		Hole = 0x00d4,

		/// <summary>
		/// White Sun.
		/// </summary>
		WhiteSun = 0x00d5,

		/// <summary>
		/// White Sun With Small Cloud.
		/// </summary>
		WhiteSunWithSmallCloud = 0x00d6,

		/// <summary>
		/// White Sun Behind Cloud.
		/// </summary>
		WhiteSunBehindCloud = 0x00d7,

		/// <summary>
		/// White Sun Behind Cloud With Rain.
		/// </summary>
		WhiteSunBehindCloudWithRain = 0x00d8,

		/// <summary>
		/// Cloud.
		/// </summary>
		Cloud = 0x00d9,

		/// <summary>
		/// Cloud With Rain.
		/// </summary>
		CloudWithRain = 0x00da,

		/// <summary>
		/// Cloud With Snow.
		/// </summary>
		CloudWithSnow = 0x00db,

		/// <summary>
		/// Cloud With Lightning.
		/// </summary>
		CloudWithLightning = 0x00dc,

		/// <summary>
		/// Cloud With Tornado.
		/// </summary>
		CloudWithTornado = 0x00dd,

		/// <summary>
		/// Wind Blowing Face.
		/// </summary>
		WindBlowingFace = 0x00de,

		/// <summary>
		/// Fog.
		/// </summary>
		Fog = 0x00df,

		/// <summary>
		/// Last Quarter Moon With Face.
		/// </summary>
		LastQuarterMoonWithFace = 0x00e0,

		/// <summary>
		/// Thermometer.
		/// </summary>
		Thermometer = 0x00e1,

		/// <summary>
		/// Couch And Lamp.
		/// </summary>
		CouchAndLamp = 0x00e2,

		/// <summary>
		/// Bed.
		/// </summary>
		Bed = 0x00e3,

		/// <summary>
		/// Fork And Knife With Plate.
		/// </summary>
		ForkAndKnifeWithPlate = 0x00e4,

		/// <summary>
		/// Cocktail Glass.
		/// </summary>
		CocktailGlass = 0x00e5,

		/// <summary>
		/// Bellhop Bell.
		/// </summary>
		BellhopBell = 0x00e6,

		/// <summary>
		/// Shopping Bags.
		/// </summary>
		ShoppingBags = 0x00e7,

		/// <summary>
		/// Circled Latin Capital Letter P.
		/// </summary>
		CircledLatinCapitalLetterP = 0x00e8,

		/// <summary>
		/// Wheelchair Symbol.
		/// </summary>
		WheelchairSymbol = 0x00e9,

		/// <summary>
		/// Triangle With Rounded Corners.
		/// </summary>
		TriangleWithRoundedCorners = 0x00ea,

		/// <summary>
		/// Black Pushpin.
		/// </summary>
		BlackPushpin = 0x00eb,

		/// <summary>
		/// Graduation Cap.
		/// </summary>
		GraduationCap = 0x00ec,

		/// <summary>
		/// Three Rays Above.
		/// </summary>
		ThreeRaysAbove = 0x00ed,

		/// <summary>
		/// Three Rays Below.
		/// </summary>
		ThreeRaysBelow = 0x00ee,

		/// <summary>
		/// Three Rays Left.
		/// </summary>
		ThreeRaysLeft = 0x00ef,

		/// <summary>
		/// Three Rays Right.
		/// </summary>
		ThreeRaysRight = 0x00f0,

		/// <summary>
		/// Northeast-Pointing Airplane.
		/// </summary>
		NortheastPointingAirplane = 0x00f1,

		/// <summary>
		/// Chipmunk.
		/// </summary>
		Chipmunk = 0x00f2,

		/// <summary>
		/// Bird.
		/// </summary>
		Bird = 0x00f3,

		/// <summary>
		/// Fish.
		/// </summary>
		Fish = 0x00f4,

		/// <summary>
		/// Dog.
		/// </summary>
		Dog = 0x00f5,

		/// <summary>
		/// Cat.
		/// </summary>
		Cat = 0x00f6,

		/// <summary>
		/// Leftwards Rocket.
		/// </summary>
		LeftwardsRocket = 0x00f7,

		/// <summary>
		/// Rightwards Rocket.
		/// </summary>
		RightwardsRocket = 0x00f8,

		/// <summary>
		/// Upwards Rocket.
		/// </summary>
		UpwardsRocket = 0x00f9,

		/// <summary>
		/// Downwards Rocket.
		/// </summary>
		DownwardsRocket = 0x00fa,

		/// <summary>
		/// World Map.
		/// </summary>
		WorldMap = 0x00fb,

		/// <summary>
		/// Earth Globe Europe-Africa.
		/// </summary>
		EarthGlobeEuropeAfrica = 0x00fc,

		/// <summary>
		/// Earth Globe Asia-Australia.
		/// </summary>
		EarthGlobeAsiaAustralia = 0x00fd,

		/// <summary>
		/// Earth Globe Americas.
		/// </summary>
		EarthGlobeAmericas = 0x00fe,

		/// <summary>
		/// Dove Of Peace.
		/// </summary>
		DoveOfPeace = 0x00ff,

		/// <summary>
		/// Device Control Four.
		/// </summary>
		DeviceControlFour_2 = 0xf014,

		/// <summary>
		/// Spider.
		/// </summary>
		Spider_2 = 0xf021,

		/// <summary>
		/// Spider Web.
		/// </summary>
		SpiderWeb_2 = 0xf022,

		/// <summary>
		/// No Piracy.
		/// </summary>
		NoPiracy_2 = 0xf023,

		/// <summary>
		/// Dark Sunglasses.
		/// </summary>
		DarkSunglasses_2 = 0xf024,

		/// <summary>
		/// Trophy.
		/// </summary>
		Trophy_2 = 0xf025,

		/// <summary>
		/// Military Medal.
		/// </summary>
		MilitaryMedal_2 = 0xf026,

		/// <summary>
		/// Linked Paperclips.
		/// </summary>
		LinkedPaperclips_2 = 0xf027,

		/// <summary>
		/// Left Speech Bubble.
		/// </summary>
		LeftSpeechBubble_2 = 0xf028,

		/// <summary>
		/// Right Speech Bubble.
		/// </summary>
		RightSpeechBubble_2 = 0xf029,

		/// <summary>
		/// Mood Bubble.
		/// </summary>
		MoodBubble_2 = 0xf02a,

		/// <summary>
		/// Lightning Mood Bubble.
		/// </summary>
		LightningMoodBubble_2 = 0xf02b,

		/// <summary>
		/// Hot Pepper.
		/// </summary>
		HotPepper_2 = 0xf02c,

		/// <summary>
		/// Reminder Ribbon.
		/// </summary>
		ReminderRibbon_2 = 0xf02d,

		/// <summary>
		/// Checker Board.
		/// </summary>
		CheckerBoard_2 = 0xf02e,

		/// <summary>
		/// Very Heavy Solidus.
		/// </summary>
		VeryHeavySolidus_2 = 0xf02f,

		/// <summary>
		/// Minimize.
		/// </summary>
		Minimize_2 = 0xf030,

		/// <summary>
		/// Maximize.
		/// </summary>
		Maximize_2 = 0xf031,

		/// <summary>
		/// Overlap.
		/// </summary>
		Overlap_2 = 0xf032,

		/// <summary>
		/// Black Medium Left-Pointing Triangle.
		/// </summary>
		BlackMediumLeftPointingTriangle_2 = 0xf033,

		/// <summary>
		/// Black Medium Right-Pointing Triangle.
		/// </summary>
		BlackMediumRightPointingTriangle_2 = 0xf034,

		/// <summary>
		/// Black Medium Up-Pointing Triangle.
		/// </summary>
		BlackMediumUpPointingTriangle_2 = 0xf035,

		/// <summary>
		/// Black Medium Down-Pointing Triangle.
		/// </summary>
		BlackMediumDownPointingTriangle_2 = 0xf036,

		/// <summary>
		/// Black Left-Pointing Double Triangle.
		/// </summary>
		BlackLeftPointingDoubleTriangle_2 = 0xf037,

		/// <summary>
		/// Black Right-Pointing Double Triangle.
		/// </summary>
		BlackRightPointingDoubleTriangle_2 = 0xf038,

		/// <summary>
		/// Black Left-Pointing Double Triangle With Vertical Bar.
		/// </summary>
		BlackLeftPointingDoubleTriangleWithVerticalBar_2 = 0xf039,

		/// <summary>
		/// Black Right-Pointing Double Triangle With Vertical Bar.
		/// </summary>
		BlackRightPointingDoubleTriangleWithVerticalBar_2 = 0xf03a,

		/// <summary>
		/// Double Vertical Bar.
		/// </summary>
		DoubleVerticalBar_2 = 0xf03b,

		/// <summary>
		/// Black Square For Stop.
		/// </summary>
		BlackSquareForStop_2 = 0xf03c,

		/// <summary>
		/// Black Circle For Record.
		/// </summary>
		BlackCircleForRecord_2 = 0xf03d,

		/// <summary>
		/// Increase Font Size Symbol.
		/// </summary>
		IncreaseFontSizeSymbol_2 = 0xf03e,

		/// <summary>
		/// Ballot Box With Ballot.
		/// </summary>
		BallotBoxWithBallot_2 = 0xf03f,

		/// <summary>
		/// Hammer And Wrench.
		/// </summary>
		HammerAndWrench_2 = 0xf040,

		/// <summary>
		/// Building Construction.
		/// </summary>
		BuildingConstruction_2 = 0xf041,

		/// <summary>
		/// House Buildings.
		/// </summary>
		HouseBuildings_2 = 0xf042,

		/// <summary>
		/// Cityscape.
		/// </summary>
		Cityscape_2 = 0xf043,

		/// <summary>
		/// Derelict House Building.
		/// </summary>
		DerelictHouseBuilding_2 = 0xf044,

		/// <summary>
		/// Desert.
		/// </summary>
		Desert_2 = 0xf045,

		/// <summary>
		/// Factory.
		/// </summary>
		Factory_2 = 0xf046,

		/// <summary>
		/// Classical Building.
		/// </summary>
		ClassicalBuilding_2 = 0xf047,

		/// <summary>
		/// House Building.
		/// </summary>
		HouseBuilding_2 = 0xf048,

		/// <summary>
		/// Beach With Umbrella.
		/// </summary>
		BeachWithUmbrella_2 = 0xf049,

		/// <summary>
		/// Desert Island.
		/// </summary>
		DesertIsland_2 = 0xf04a,

		/// <summary>
		/// Motorway.
		/// </summary>
		Motorway_2 = 0xf04b,

		/// <summary>
		/// Left-Pointing Magnifying Glass.
		/// </summary>
		LeftPointingMagnifyingGlass_2 = 0xf04c,

		/// <summary>
		/// Snow Capped Mountain.
		/// </summary>
		SnowCappedMountain_2 = 0xf04d,

		/// <summary>
		/// Eye.
		/// </summary>
		Eye_2 = 0xf04e,

		/// <summary>
		/// Ear.
		/// </summary>
		Ear_2 = 0xf04f,

		/// <summary>
		/// National Park.
		/// </summary>
		NationalPark_2 = 0xf050,

		/// <summary>
		/// Camping.
		/// </summary>
		Camping_2 = 0xf051,

		/// <summary>
		/// Railway Track.
		/// </summary>
		RailwayTrack_2 = 0xf052,

		/// <summary>
		/// Stadium.
		/// </summary>
		Stadium_2 = 0xf053,

		/// <summary>
		/// Passenger Ship.
		/// </summary>
		PassengerShip_2 = 0xf054,

		/// <summary>
		/// Bullhorn With Sound Waves.
		/// </summary>
		BullhornWithSoundWaves_2 = 0xf055,

		/// <summary>
		/// Bullhorn.
		/// </summary>
		Bullhorn_2 = 0xf056,

		/// <summary>
		/// Right Speaker.
		/// </summary>
		RightSpeaker_2 = 0xf057,

		/// <summary>
		/// Speaker.
		/// </summary>
		Speaker_2 = 0xf058,

		/// <summary>
		/// Heart With Tip On The Left.
		/// </summary>
		HeartWithTipOnTheLeft_2 = 0xf059,

		/// <summary>
		/// Bouquet Of Flowers.
		/// </summary>
		BouquetOfFlowers_2 = 0xf05a,

		/// <summary>
		/// Left Thought Bubble.
		/// </summary>
		LeftThoughtBubble_2 = 0xf05b,

		/// <summary>
		/// Very Heavy Reverse Solidus.
		/// </summary>
		VeryHeavyReverseSolidus_2 = 0xf05c,

		/// <summary>
		/// Right Thought Bubble.
		/// </summary>
		RightThoughtBubble_2 = 0xf05d,

		/// <summary>
		/// Two Speech Bubbles.
		/// </summary>
		TwoSpeechBubbles_2 = 0xf05e,

		/// <summary>
		/// Three Speech Bubbles.
		/// </summary>
		ThreeSpeechBubbles_2 = 0xf05f,

		/// <summary>
		/// Four Corner Arrows Circling Anticlockwise.
		/// </summary>
		FourCornerArrowsCirclingAnticlockwise_2 = 0xf060,

		/// <summary>
		/// Heavy Check Mark.
		/// </summary>
		HeavyCheckMark_2 = 0xf061,

		/// <summary>
		/// Bicycle.
		/// </summary>
		Bicycle_2 = 0xf062,

		/// <summary>
		/// White Square.
		/// </summary>
		WhiteSquare_2 = 0xf063,

		/// <summary>
		/// Shield.
		/// </summary>
		Shield_2 = 0xf064,

		/// <summary>
		/// Package.
		/// </summary>
		Package_2 = 0xf065,

		/// <summary>
		/// Oncoming Fire Engine.
		/// </summary>
		OncomingFireEngine_2 = 0xf066,

		/// <summary>
		/// Black Square.
		/// </summary>
		BlackSquare_2 = 0xf067,

		/// <summary>
		/// Ambulance.
		/// </summary>
		Ambulance_2 = 0xf068,

		/// <summary>
		/// Circled Information Source.
		/// </summary>
		CircledInformationSource_2 = 0xf069,

		/// <summary>
		/// Small Airplane.
		/// </summary>
		SmallAirplane_2 = 0xf06a,

		/// <summary>
		/// Satellite.
		/// </summary>
		Satellite_2 = 0xf06b,

		/// <summary>
		/// Reverse Light Four Pointed Pinwheel Star.
		/// </summary>
		ReverseLightFourPointedPinwheelStar_2 = 0xf06c,

		/// <summary>
		/// Man In Business Suit Levitating.
		/// </summary>
		ManInBusinessSuitLevitating_2 = 0xf06d,

		/// <summary>
		/// Medium Black Circle.
		/// </summary>
		MediumBlackCircle_2 = 0xf06e,

		/// <summary>
		/// Motor Boat.
		/// </summary>
		MotorBoat_2 = 0xf06f,

		/// <summary>
		/// Oncoming Police Car.
		/// </summary>
		OncomingPoliceCar_2 = 0xf070,

		/// <summary>
		/// Clockwise Right And Left Semicircle Arrows.
		/// </summary>
		ClockwiseRightAndLeftSemicircleArrows_2 = 0xf071,

		/// <summary>
		/// Cancellation X.
		/// </summary>
		CancellationX_2 = 0xf072,

		/// <summary>
		/// Black Question Mark Ornament.
		/// </summary>
		BlackQuestionMarkOrnament_2 = 0xf073,

		/// <summary>
		/// Diesel Locomotive.
		/// </summary>
		DieselLocomotive_2 = 0xf074,

		/// <summary>
		/// Metro.
		/// </summary>
		Metro_2 = 0xf075,

		/// <summary>
		/// Oncoming Bus.
		/// </summary>
		OncomingBus_2 = 0xf076,

		/// <summary>
		/// Flag In Hole.
		/// </summary>
		FlagInHole_2 = 0xf077,

		/// <summary>
		/// Prohibited Sign.
		/// </summary>
		ProhibitedSign_2 = 0xf078,

		/// <summary>
		/// Circled Minus.
		/// </summary>
		CircledMinus_2 = 0xf079,

		/// <summary>
		/// No Smoking Symbol.
		/// </summary>
		NoSmokingSymbol_2 = 0xf07a,

		/// <summary>
		/// Left Anger Bubble.
		/// </summary>
		LeftAngerBubble_2 = 0xf07b,

		/// <summary>
		/// Vertical Line.
		/// </summary>
		VerticalLine_2 = 0xf07c,

		/// <summary>
		/// Right Anger Bubble.
		/// </summary>
		RightAngerBubble_2 = 0xf07d,

		/// <summary>
		/// Lightning Mood.
		/// </summary>
		LightningMood_2 = 0xf07e,

		/// <summary>
		/// Mens Symbol.
		/// </summary>
		MensSymbol_2 = 0xf080,

		/// <summary>
		/// Womens Symbol.
		/// </summary>
		WomensSymbol_2 = 0xf081,

		/// <summary>
		/// Boys Symbol.
		/// </summary>
		BoysSymbol_2 = 0xf082,

		/// <summary>
		/// Girls Symbol.
		/// </summary>
		GirlsSymbol_2 = 0xf083,

		/// <summary>
		/// Baby Symbol.
		/// </summary>
		BabySymbol_2 = 0xf084,

		/// <summary>
		/// Extraterrestrial Alien.
		/// </summary>
		ExtraterrestrialAlien_2 = 0xf085,

		/// <summary>
		/// Weight Lifter.
		/// </summary>
		WeightLifter_2 = 0xf086,

		/// <summary>
		/// Skier.
		/// </summary>
		Skier_2 = 0xf087,

		/// <summary>
		/// Snowboarder.
		/// </summary>
		Snowboarder_2 = 0xf088,

		/// <summary>
		/// Golfer.
		/// </summary>
		Golfer_2 = 0xf089,

		/// <summary>
		/// Swimmer.
		/// </summary>
		Swimmer_2 = 0xf08a,

		/// <summary>
		/// Surfer.
		/// </summary>
		Surfer_2 = 0xf08b,

		/// <summary>
		/// Racing Motorcycle.
		/// </summary>
		RacingMotorcycle_2 = 0xf08c,

		/// <summary>
		/// Racing Car.
		/// </summary>
		RacingCar_2 = 0xf08d,

		/// <summary>
		/// Oncoming Automobile.
		/// </summary>
		OncomingAutomobile_2 = 0xf08e,

		/// <summary>
		/// Stock Chart.
		/// </summary>
		StockChart_2 = 0xf08f,

		/// <summary>
		/// Oil Drum.
		/// </summary>
		OilDrum_2 = 0xf090,

		/// <summary>
		/// Money Bag.
		/// </summary>
		MoneyBag_2 = 0xf091,

		/// <summary>
		/// Label.
		/// </summary>
		Label_2 = 0xf092,

		/// <summary>
		/// Credit Card.
		/// </summary>
		CreditCard_2 = 0xf093,

		/// <summary>
		/// Family.
		/// </summary>
		Family_2 = 0xf094,

		/// <summary>
		/// Dagger Knife.
		/// </summary>
		DaggerKnife_2 = 0xf095,

		/// <summary>
		/// Lips.
		/// </summary>
		Lips_2 = 0xf096,

		/// <summary>
		/// Speaking Head In Silhouette.
		/// </summary>
		SpeakingHeadInSilhouette_2 = 0xf097,

		/// <summary>
		/// Pinwheel Star.
		/// </summary>
		PinwheelStar_2 = 0xf098,

		/// <summary>
		/// Envelope With Lightning.
		/// </summary>
		EnvelopeWithLightning_2 = 0xf099,

		/// <summary>
		/// Flying Envelope.
		/// </summary>
		FlyingEnvelope_2 = 0xf09a,

		/// <summary>
		/// Stamped Envelope.
		/// </summary>
		StampedEnvelope_2 = 0xf09b,

		/// <summary>
		/// Pen Over Stamped Envelope.
		/// </summary>
		PenOverStampedEnvelope_2 = 0xf09c,

		/// <summary>
		/// Document With Text.
		/// </summary>
		DocumentWithText_2 = 0xf09d,

		/// <summary>
		/// Document With Text And Picture.
		/// </summary>
		DocumentWithTextAndPicture_2 = 0xf09e,

		/// <summary>
		/// Document With Picture.
		/// </summary>
		DocumentWithPicture_2 = 0xf09f,

		/// <summary>
		/// Sleuth Or Spy.
		/// </summary>
		SleuthOrSpy_2 = 0xf0a0,

		/// <summary>
		/// Mantelpiece Clock.
		/// </summary>
		MantelpieceClock_2 = 0xf0a1,

		/// <summary>
		/// Frame With Tiles.
		/// </summary>
		FrameWithTiles_2 = 0xf0a2,

		/// <summary>
		/// Frame With An X.
		/// </summary>
		FrameWithAnX_2 = 0xf0a3,

		/// <summary>
		/// Clipboard.
		/// </summary>
		Clipboard_2 = 0xf0a4,

		/// <summary>
		/// Spiral Note Pad.
		/// </summary>
		SpiralNotePad_2 = 0xf0a5,

		/// <summary>
		/// Spiral Calendar Pad.
		/// </summary>
		SpiralCalendarPad_2 = 0xf0a6,

		/// <summary>
		/// Open Book.
		/// </summary>
		OpenBook_2 = 0xf0a7,

		/// <summary>
		/// Books.
		/// </summary>
		Books_2 = 0xf0a8,

		/// <summary>
		/// Rolled-Up Newspaper.
		/// </summary>
		RolledUpNewspaper_2 = 0xf0a9,

		/// <summary>
		/// Page With Circled Text.
		/// </summary>
		PageWithCircledText_2 = 0xf0aa,

		/// <summary>
		/// Card File Box.
		/// </summary>
		CardFileBox_2 = 0xf0ab,

		/// <summary>
		/// Card Index Dividers.
		/// </summary>
		CardIndexDividers_2 = 0xf0ac,

		/// <summary>
		/// Frame With Picture.
		/// </summary>
		FrameWithPicture_2 = 0xf0ad,

		/// <summary>
		/// Performing Arts.
		/// </summary>
		PerformingArts_2 = 0xf0ae,

		/// <summary>
		/// Beamed Ascending Musical Notes.
		/// </summary>
		BeamedAscendingMusicalNotes_2 = 0xf0af,

		/// <summary>
		/// Musical Keyboard With Jacks.
		/// </summary>
		MusicalKeyboardWithJacks_2 = 0xf0b0,

		/// <summary>
		/// Studio Microphone.
		/// </summary>
		StudioMicrophone_2 = 0xf0b1,

		/// <summary>
		/// Headphone.
		/// </summary>
		Headphone_2 = 0xf0b2,

		/// <summary>
		/// Optical Disc.
		/// </summary>
		OpticalDisc_2 = 0xf0b3,

		/// <summary>
		/// Film Frames.
		/// </summary>
		FilmFrames_2 = 0xf0b4,

		/// <summary>
		/// Camera.
		/// </summary>
		Camera_2 = 0xf0b5,

		/// <summary>
		/// Admission Tickets.
		/// </summary>
		AdmissionTickets_2 = 0xf0b6,

		/// <summary>
		/// Clapper Board.
		/// </summary>
		ClapperBoard_2 = 0xf0b7,

		/// <summary>
		/// Film Projector.
		/// </summary>
		FilmProjector_2 = 0xf0b8,

		/// <summary>
		/// Video Camera.
		/// </summary>
		VideoCamera_2 = 0xf0b9,

		/// <summary>
		/// Portable Stereo.
		/// </summary>
		PortableStereo_2 = 0xf0ba,

		/// <summary>
		/// Radio.
		/// </summary>
		Radio_2 = 0xf0bb,

		/// <summary>
		/// Level Slider.
		/// </summary>
		LevelSlider_2 = 0xf0bc,

		/// <summary>
		/// Control Knobs.
		/// </summary>
		ControlKnobs_2 = 0xf0bd,

		/// <summary>
		/// Television.
		/// </summary>
		Television_2 = 0xf0be,

		/// <summary>
		/// Personal Computer.
		/// </summary>
		PersonalComputer_2 = 0xf0bf,

		/// <summary>
		/// Desktop Computer.
		/// </summary>
		DesktopComputer_2 = 0xf0c0,

		/// <summary>
		/// Keyboard And Mouse.
		/// </summary>
		KeyboardAndMouse_2 = 0xf0c1,

		/// <summary>
		/// Three Networked Computers.
		/// </summary>
		ThreeNetworkedComputers_2 = 0xf0c2,

		/// <summary>
		/// Joystick.
		/// </summary>
		Joystick_2 = 0xf0c3,

		/// <summary>
		/// Video Game.
		/// </summary>
		VideoGame_2 = 0xf0c4,

		/// <summary>
		/// Left Hand Telephone Receiver.
		/// </summary>
		LeftHandTelephoneReceiver_2 = 0xf0c5,

		/// <summary>
		/// Telephone Receiver With Page.
		/// </summary>
		TelephoneReceiverWithPage_2 = 0xf0c6,

		/// <summary>
		/// Pager.
		/// </summary>
		Pager_2 = 0xf0c7,

		/// <summary>
		/// Clamshell Mobile Phone.
		/// </summary>
		ClamshellMobilePhone_2 = 0xf0c8,

		/// <summary>
		/// Telephone On Top Of Modem.
		/// </summary>
		TelephoneOnTopOfModem_2 = 0xf0c9,

		/// <summary>
		/// Printer.
		/// </summary>
		Printer_2 = 0xf0ca,

		/// <summary>
		/// Pocket Calculator.
		/// </summary>
		PocketCalculator_2 = 0xf0cb,

		/// <summary>
		/// Black Folder.
		/// </summary>
		BlackFolder_2 = 0xf0cc,

		/// <summary>
		/// Black Hard Shell Floppy Disk.
		/// </summary>
		BlackHardShellFloppyDisk_2 = 0xf0cd,

		/// <summary>
		/// Compression.
		/// </summary>
		Compression_2 = 0xf0ce,

		/// <summary>
		/// Lock.
		/// </summary>
		Lock_2 = 0xf0cf,

		/// <summary>
		/// Open Lock.
		/// </summary>
		OpenLock_2 = 0xf0d0,

		/// <summary>
		/// Old Key.
		/// </summary>
		OldKey_2 = 0xf0d1,

		/// <summary>
		/// Inbox Tray.
		/// </summary>
		InboxTray_2 = 0xf0d2,

		/// <summary>
		/// North East Pointing Leaf.
		/// </summary>
		NorthEastPointingLeaf_2 = 0xf0d3,

		/// <summary>
		/// Hole.
		/// </summary>
		Hole_2 = 0xf0d4,

		/// <summary>
		/// White Sun.
		/// </summary>
		WhiteSun_2 = 0xf0d5,

		/// <summary>
		/// White Sun With Small Cloud.
		/// </summary>
		WhiteSunWithSmallCloud_2 = 0xf0d6,

		/// <summary>
		/// White Sun Behind Cloud.
		/// </summary>
		WhiteSunBehindCloud_2 = 0xf0d7,

		/// <summary>
		/// White Sun Behind Cloud With Rain.
		/// </summary>
		WhiteSunBehindCloudWithRain_2 = 0xf0d8,

		/// <summary>
		/// Cloud.
		/// </summary>
		Cloud_2 = 0xf0d9,

		/// <summary>
		/// Cloud With Rain.
		/// </summary>
		CloudWithRain_2 = 0xf0da,

		/// <summary>
		/// Cloud With Snow.
		/// </summary>
		CloudWithSnow_2 = 0xf0db,

		/// <summary>
		/// Cloud With Lightning.
		/// </summary>
		CloudWithLightning_2 = 0xf0dc,

		/// <summary>
		/// Cloud With Tornado.
		/// </summary>
		CloudWithTornado_2 = 0xf0dd,

		/// <summary>
		/// Wind Blowing Face.
		/// </summary>
		WindBlowingFace_2 = 0xf0de,

		/// <summary>
		/// Fog.
		/// </summary>
		Fog_2 = 0xf0df,

		/// <summary>
		/// Last Quarter Moon With Face.
		/// </summary>
		LastQuarterMoonWithFace_2 = 0xf0e0,

		/// <summary>
		/// Thermometer.
		/// </summary>
		Thermometer_2 = 0xf0e1,

		/// <summary>
		/// Couch And Lamp.
		/// </summary>
		CouchAndLamp_2 = 0xf0e2,

		/// <summary>
		/// Bed.
		/// </summary>
		Bed_2 = 0xf0e3,

		/// <summary>
		/// Fork And Knife With Plate.
		/// </summary>
		ForkAndKnifeWithPlate_2 = 0xf0e4,

		/// <summary>
		/// Cocktail Glass.
		/// </summary>
		CocktailGlass_2 = 0xf0e5,

		/// <summary>
		/// Bellhop Bell.
		/// </summary>
		BellhopBell_2 = 0xf0e6,

		/// <summary>
		/// Shopping Bags.
		/// </summary>
		ShoppingBags_2 = 0xf0e7,

		/// <summary>
		/// Circled Latin Capital Letter P.
		/// </summary>
		CircledLatinCapitalLetterP_2 = 0xf0e8,

		/// <summary>
		/// Wheelchair Symbol.
		/// </summary>
		WheelchairSymbol_2 = 0xf0e9,

		/// <summary>
		/// Triangle With Rounded Corners.
		/// </summary>
		TriangleWithRoundedCorners_2 = 0xf0ea,

		/// <summary>
		/// Black Pushpin.
		/// </summary>
		BlackPushpin_2 = 0xf0eb,

		/// <summary>
		/// Graduation Cap.
		/// </summary>
		GraduationCap_2 = 0xf0ec,

		/// <summary>
		/// Three Rays Above.
		/// </summary>
		ThreeRaysAbove_2 = 0xf0ed,

		/// <summary>
		/// Three Rays Below.
		/// </summary>
		ThreeRaysBelow_2 = 0xf0ee,

		/// <summary>
		/// Three Rays Left.
		/// </summary>
		ThreeRaysLeft_2 = 0xf0ef,

		/// <summary>
		/// Three Rays Right.
		/// </summary>
		ThreeRaysRight_2 = 0xf0f0,

		/// <summary>
		/// Northeast-Pointing Airplane.
		/// </summary>
		NortheastPointingAirplane_2 = 0xf0f1,

		/// <summary>
		/// Chipmunk.
		/// </summary>
		Chipmunk_2 = 0xf0f2,

		/// <summary>
		/// Bird.
		/// </summary>
		Bird_2 = 0xf0f3,

		/// <summary>
		/// Fish.
		/// </summary>
		Fish_2 = 0xf0f4,

		/// <summary>
		/// Dog.
		/// </summary>
		Dog_2 = 0xf0f5,

		/// <summary>
		/// Cat.
		/// </summary>
		Cat_2 = 0xf0f6,

		/// <summary>
		/// Leftwards Rocket.
		/// </summary>
		LeftwardsRocket_2 = 0xf0f7,

		/// <summary>
		/// Rightwards Rocket.
		/// </summary>
		RightwardsRocket_2 = 0xf0f8,

		/// <summary>
		/// Upwards Rocket.
		/// </summary>
		UpwardsRocket_2 = 0xf0f9,

		/// <summary>
		/// Downwards Rocket.
		/// </summary>
		DownwardsRocket_2 = 0xf0fa,

		/// <summary>
		/// World Map.
		/// </summary>
		WorldMap_2 = 0xf0fb,

		/// <summary>
		/// Earth Globe Europe-Africa.
		/// </summary>
		EarthGlobeEuropeAfrica_2 = 0xf0fc,

		/// <summary>
		/// Earth Globe Asia-Australia.
		/// </summary>
		EarthGlobeAsiaAustralia_2 = 0xf0fd,

		/// <summary>
		/// Earth Globe Americas.
		/// </summary>
		EarthGlobeAmericas_2 = 0xf0fe,

		/// <summary>
		/// Dove Of Peace.
		/// </summary>
		DoveOfPeace_2 = 0xf0ff
	}

	/// <summary>
	/// WebdingsGlyph Enums.
	/// </summary>
	public static partial class WebdingsGlyphResource
	{
		/// <summary>
		/// Device Control Four.
		/// </summary>
		public const string DeviceControlFour = "\u0014";

		/// <summary>
		/// Spider.
		/// </summary>
		public const string Spider = "\u0021";

		/// <summary>
		/// Spider Web.
		/// </summary>
		public const string SpiderWeb = "\u0022";

		/// <summary>
		/// No Piracy.
		/// </summary>
		public const string NoPiracy = "\u0023";

		/// <summary>
		/// Dark Sunglasses.
		/// </summary>
		public const string DarkSunglasses = "\u0024";

		/// <summary>
		/// Trophy.
		/// </summary>
		public const string Trophy = "\u0025";

		/// <summary>
		/// Military Medal.
		/// </summary>
		public const string MilitaryMedal = "\u0026";

		/// <summary>
		/// Linked Paperclips.
		/// </summary>
		public const string LinkedPaperclips = "\u0027";

		/// <summary>
		/// Left Speech Bubble.
		/// </summary>
		public const string LeftSpeechBubble = "\u0028";

		/// <summary>
		/// Right Speech Bubble.
		/// </summary>
		public const string RightSpeechBubble = "\u0029";

		/// <summary>
		/// Mood Bubble.
		/// </summary>
		public const string MoodBubble = "\u002a";

		/// <summary>
		/// Lightning Mood Bubble.
		/// </summary>
		public const string LightningMoodBubble = "\u002b";

		/// <summary>
		/// Hot Pepper.
		/// </summary>
		public const string HotPepper = "\u002c";

		/// <summary>
		/// Reminder Ribbon.
		/// </summary>
		public const string ReminderRibbon = "\u002d";

		/// <summary>
		/// Checker Board.
		/// </summary>
		public const string CheckerBoard = "\u002e";

		/// <summary>
		/// Very Heavy Solidus.
		/// </summary>
		public const string VeryHeavySolidus = "\u002f";

		/// <summary>
		/// Minimize.
		/// </summary>
		public const string Minimize = "\u0030";

		/// <summary>
		/// Maximize.
		/// </summary>
		public const string Maximize = "\u0031";

		/// <summary>
		/// Overlap.
		/// </summary>
		public const string Overlap = "\u0032";

		/// <summary>
		/// Black Medium Left-Pointing Triangle.
		/// </summary>
		public const string BlackMediumLeftPointingTriangle = "\u0033";

		/// <summary>
		/// Black Medium Right-Pointing Triangle.
		/// </summary>
		public const string BlackMediumRightPointingTriangle = "\u0034";

		/// <summary>
		/// Black Medium Up-Pointing Triangle.
		/// </summary>
		public const string BlackMediumUpPointingTriangle = "\u0035";

		/// <summary>
		/// Black Medium Down-Pointing Triangle.
		/// </summary>
		public const string BlackMediumDownPointingTriangle = "\u0036";

		/// <summary>
		/// Black Left-Pointing Double Triangle.
		/// </summary>
		public const string BlackLeftPointingDoubleTriangle = "\u0037";

		/// <summary>
		/// Black Right-Pointing Double Triangle.
		/// </summary>
		public const string BlackRightPointingDoubleTriangle = "\u0038";

		/// <summary>
		/// Black Left-Pointing Double Triangle With Vertical Bar.
		/// </summary>
		public const string BlackLeftPointingDoubleTriangleWithVerticalBar = "\u0039";

		/// <summary>
		/// Black Right-Pointing Double Triangle With Vertical Bar.
		/// </summary>
		public const string BlackRightPointingDoubleTriangleWithVerticalBar = "\u003a";

		/// <summary>
		/// Double Vertical Bar.
		/// </summary>
		public const string DoubleVerticalBar = "\u003b";

		/// <summary>
		/// Black Square For Stop.
		/// </summary>
		public const string BlackSquareForStop = "\u003c";

		/// <summary>
		/// Black Circle For Record.
		/// </summary>
		public const string BlackCircleForRecord = "\u003d";

		/// <summary>
		/// Increase Font Size Symbol.
		/// </summary>
		public const string IncreaseFontSizeSymbol = "\u003e";

		/// <summary>
		/// Ballot Box With Ballot.
		/// </summary>
		public const string BallotBoxWithBallot = "\u003f";

		/// <summary>
		/// Hammer And Wrench.
		/// </summary>
		public const string HammerAndWrench = "\u0040";

		/// <summary>
		/// Building Construction.
		/// </summary>
		public const string BuildingConstruction = "\u0041";

		/// <summary>
		/// House Buildings.
		/// </summary>
		public const string HouseBuildings = "\u0042";

		/// <summary>
		/// Cityscape.
		/// </summary>
		public const string Cityscape = "\u0043";

		/// <summary>
		/// Derelict House Building.
		/// </summary>
		public const string DerelictHouseBuilding = "\u0044";

		/// <summary>
		/// Desert.
		/// </summary>
		public const string Desert = "\u0045";

		/// <summary>
		/// Factory.
		/// </summary>
		public const string Factory = "\u0046";

		/// <summary>
		/// Classical Building.
		/// </summary>
		public const string ClassicalBuilding = "\u0047";

		/// <summary>
		/// House Building.
		/// </summary>
		public const string HouseBuilding = "\u0048";

		/// <summary>
		/// Beach With Umbrella.
		/// </summary>
		public const string BeachWithUmbrella = "\u0049";

		/// <summary>
		/// Desert Island.
		/// </summary>
		public const string DesertIsland = "\u004a";

		/// <summary>
		/// Motorway.
		/// </summary>
		public const string Motorway = "\u004b";

		/// <summary>
		/// Left-Pointing Magnifying Glass.
		/// </summary>
		public const string LeftPointingMagnifyingGlass = "\u004c";

		/// <summary>
		/// Snow Capped Mountain.
		/// </summary>
		public const string SnowCappedMountain = "\u004d";

		/// <summary>
		/// Eye.
		/// </summary>
		public const string Eye = "\u004e";

		/// <summary>
		/// Ear.
		/// </summary>
		public const string Ear = "\u004f";

		/// <summary>
		/// National Park.
		/// </summary>
		public const string NationalPark = "\u0050";

		/// <summary>
		/// Camping.
		/// </summary>
		public const string Camping = "\u0051";

		/// <summary>
		/// Railway Track.
		/// </summary>
		public const string RailwayTrack = "\u0052";

		/// <summary>
		/// Stadium.
		/// </summary>
		public const string Stadium = "\u0053";

		/// <summary>
		/// Passenger Ship.
		/// </summary>
		public const string PassengerShip = "\u0054";

		/// <summary>
		/// Bullhorn With Sound Waves.
		/// </summary>
		public const string BullhornWithSoundWaves = "\u0055";

		/// <summary>
		/// Bullhorn.
		/// </summary>
		public const string Bullhorn = "\u0056";

		/// <summary>
		/// Right Speaker.
		/// </summary>
		public const string RightSpeaker = "\u0057";

		/// <summary>
		/// Speaker.
		/// </summary>
		public const string Speaker = "\u0058";

		/// <summary>
		/// Heart With Tip On The Left.
		/// </summary>
		public const string HeartWithTipOnTheLeft = "\u0059";

		/// <summary>
		/// Bouquet Of Flowers.
		/// </summary>
		public const string BouquetOfFlowers = "\u005a";

		/// <summary>
		/// Left Thought Bubble.
		/// </summary>
		public const string LeftThoughtBubble = "\u005b";

		/// <summary>
		/// Very Heavy Reverse Solidus.
		/// </summary>
		public const string VeryHeavyReverseSolidus = "\u005c";

		/// <summary>
		/// Right Thought Bubble.
		/// </summary>
		public const string RightThoughtBubble = "\u005d";

		/// <summary>
		/// Two Speech Bubbles.
		/// </summary>
		public const string TwoSpeechBubbles = "\u005e";

		/// <summary>
		/// Three Speech Bubbles.
		/// </summary>
		public const string ThreeSpeechBubbles = "\u005f";

		/// <summary>
		/// Four Corner Arrows Circling Anticlockwise.
		/// </summary>
		public const string FourCornerArrowsCirclingAnticlockwise = "\u0060";

		/// <summary>
		/// Heavy Check Mark.
		/// </summary>
		public const string HeavyCheckMark = "\u0061";

		/// <summary>
		/// Bicycle.
		/// </summary>
		public const string Bicycle = "\u0062";

		/// <summary>
		/// White Square.
		/// </summary>
		public const string WhiteSquare = "\u0063";

		/// <summary>
		/// Shield.
		/// </summary>
		public const string Shield = "\u0064";

		/// <summary>
		/// Package.
		/// </summary>
		public const string Package = "\u0065";

		/// <summary>
		/// Oncoming Fire Engine.
		/// </summary>
		public const string OncomingFireEngine = "\u0066";

		/// <summary>
		/// Black Square.
		/// </summary>
		public const string BlackSquare = "\u0067";

		/// <summary>
		/// Ambulance.
		/// </summary>
		public const string Ambulance = "\u0068";

		/// <summary>
		/// Circled Information Source.
		/// </summary>
		public const string CircledInformationSource = "\u0069";

		/// <summary>
		/// Small Airplane.
		/// </summary>
		public const string SmallAirplane = "\u006a";

		/// <summary>
		/// Satellite.
		/// </summary>
		public const string Satellite = "\u006b";

		/// <summary>
		/// Reverse Light Four Pointed Pinwheel Star.
		/// </summary>
		public const string ReverseLightFourPointedPinwheelStar = "\u006c";

		/// <summary>
		/// Man In Business Suit Levitating.
		/// </summary>
		public const string ManInBusinessSuitLevitating = "\u006d";

		/// <summary>
		/// Medium Black Circle.
		/// </summary>
		public const string MediumBlackCircle = "\u006e";

		/// <summary>
		/// Motor Boat.
		/// </summary>
		public const string MotorBoat = "\u006f";

		/// <summary>
		/// Oncoming Police Car.
		/// </summary>
		public const string OncomingPoliceCar = "\u0070";

		/// <summary>
		/// Clockwise Right And Left Semicircle Arrows.
		/// </summary>
		public const string ClockwiseRightAndLeftSemicircleArrows = "\u0071";

		/// <summary>
		/// Cancellation X.
		/// </summary>
		public const string CancellationX = "\u0072";

		/// <summary>
		/// Black Question Mark Ornament.
		/// </summary>
		public const string BlackQuestionMarkOrnament = "\u0073";

		/// <summary>
		/// Diesel Locomotive.
		/// </summary>
		public const string DieselLocomotive = "\u0074";

		/// <summary>
		/// Metro.
		/// </summary>
		public const string Metro = "\u0075";

		/// <summary>
		/// Oncoming Bus.
		/// </summary>
		public const string OncomingBus = "\u0076";

		/// <summary>
		/// Flag In Hole.
		/// </summary>
		public const string FlagInHole = "\u0077";

		/// <summary>
		/// Prohibited Sign.
		/// </summary>
		public const string ProhibitedSign = "\u0078";

		/// <summary>
		/// Circled Minus.
		/// </summary>
		public const string CircledMinus = "\u0079";

		/// <summary>
		/// No Smoking Symbol.
		/// </summary>
		public const string NoSmokingSymbol = "\u007a";

		/// <summary>
		/// Left Anger Bubble.
		/// </summary>
		public const string LeftAngerBubble = "\u007b";

		/// <summary>
		/// Vertical Line.
		/// </summary>
		public const string VerticalLine = "\u007c";

		/// <summary>
		/// Right Anger Bubble.
		/// </summary>
		public const string RightAngerBubble = "\u007d";

		/// <summary>
		/// Lightning Mood.
		/// </summary>
		public const string LightningMood = "\u007e";

		/// <summary>
		/// Mens Symbol.
		/// </summary>
		public const string MensSymbol = "\u0080";

		/// <summary>
		/// Womens Symbol.
		/// </summary>
		public const string WomensSymbol = "\u0081";

		/// <summary>
		/// Boys Symbol.
		/// </summary>
		public const string BoysSymbol = "\u0082";

		/// <summary>
		/// Girls Symbol.
		/// </summary>
		public const string GirlsSymbol = "\u0083";

		/// <summary>
		/// Baby Symbol.
		/// </summary>
		public const string BabySymbol = "\u0084";

		/// <summary>
		/// Extraterrestrial Alien.
		/// </summary>
		public const string ExtraterrestrialAlien = "\u0085";

		/// <summary>
		/// Weight Lifter.
		/// </summary>
		public const string WeightLifter = "\u0086";

		/// <summary>
		/// Skier.
		/// </summary>
		public const string Skier = "\u0087";

		/// <summary>
		/// Snowboarder.
		/// </summary>
		public const string Snowboarder = "\u0088";

		/// <summary>
		/// Golfer.
		/// </summary>
		public const string Golfer = "\u0089";

		/// <summary>
		/// Swimmer.
		/// </summary>
		public const string Swimmer = "\u008a";

		/// <summary>
		/// Surfer.
		/// </summary>
		public const string Surfer = "\u008b";

		/// <summary>
		/// Racing Motorcycle.
		/// </summary>
		public const string RacingMotorcycle = "\u008c";

		/// <summary>
		/// Racing Car.
		/// </summary>
		public const string RacingCar = "\u008d";

		/// <summary>
		/// Oncoming Automobile.
		/// </summary>
		public const string OncomingAutomobile = "\u008e";

		/// <summary>
		/// Stock Chart.
		/// </summary>
		public const string StockChart = "\u008f";

		/// <summary>
		/// Oil Drum.
		/// </summary>
		public const string OilDrum = "\u0090";

		/// <summary>
		/// Money Bag.
		/// </summary>
		public const string MoneyBag = "\u0091";

		/// <summary>
		/// Label.
		/// </summary>
		public const string Label = "\u0092";

		/// <summary>
		/// Credit Card.
		/// </summary>
		public const string CreditCard = "\u0093";

		/// <summary>
		/// Family.
		/// </summary>
		public const string Family = "\u0094";

		/// <summary>
		/// Dagger Knife.
		/// </summary>
		public const string DaggerKnife = "\u0095";

		/// <summary>
		/// Lips.
		/// </summary>
		public const string Lips = "\u0096";

		/// <summary>
		/// Speaking Head In Silhouette.
		/// </summary>
		public const string SpeakingHeadInSilhouette = "\u0097";

		/// <summary>
		/// Pinwheel Star.
		/// </summary>
		public const string PinwheelStar = "\u0098";

		/// <summary>
		/// Envelope With Lightning.
		/// </summary>
		public const string EnvelopeWithLightning = "\u0099";

		/// <summary>
		/// Flying Envelope.
		/// </summary>
		public const string FlyingEnvelope = "\u009a";

		/// <summary>
		/// Stamped Envelope.
		/// </summary>
		public const string StampedEnvelope = "\u009b";

		/// <summary>
		/// Pen Over Stamped Envelope.
		/// </summary>
		public const string PenOverStampedEnvelope = "\u009c";

		/// <summary>
		/// Document With Text.
		/// </summary>
		public const string DocumentWithText = "\u009d";

		/// <summary>
		/// Document With Text And Picture.
		/// </summary>
		public const string DocumentWithTextAndPicture = "\u009e";

		/// <summary>
		/// Document With Picture.
		/// </summary>
		public const string DocumentWithPicture = "\u009f";

		/// <summary>
		/// Sleuth Or Spy.
		/// </summary>
		public const string SleuthOrSpy = "\u00a0";

		/// <summary>
		/// Mantelpiece Clock.
		/// </summary>
		public const string MantelpieceClock = "\u00a1";

		/// <summary>
		/// Frame With Tiles.
		/// </summary>
		public const string FrameWithTiles = "\u00a2";

		/// <summary>
		/// Frame With An X.
		/// </summary>
		public const string FrameWithAnX = "\u00a3";

		/// <summary>
		/// Clipboard.
		/// </summary>
		public const string Clipboard = "\u00a4";

		/// <summary>
		/// Spiral Note Pad.
		/// </summary>
		public const string SpiralNotePad = "\u00a5";

		/// <summary>
		/// Spiral Calendar Pad.
		/// </summary>
		public const string SpiralCalendarPad = "\u00a6";

		/// <summary>
		/// Open Book.
		/// </summary>
		public const string OpenBook = "\u00a7";

		/// <summary>
		/// Books.
		/// </summary>
		public const string Books = "\u00a8";

		/// <summary>
		/// Rolled-Up Newspaper.
		/// </summary>
		public const string RolledUpNewspaper = "\u00a9";

		/// <summary>
		/// Page With Circled Text.
		/// </summary>
		public const string PageWithCircledText = "\u00aa";

		/// <summary>
		/// Card File Box.
		/// </summary>
		public const string CardFileBox = "\u00ab";

		/// <summary>
		/// Card Index Dividers.
		/// </summary>
		public const string CardIndexDividers = "\u00ac";

		/// <summary>
		/// Frame With Picture.
		/// </summary>
		public const string FrameWithPicture = "\u00ad";

		/// <summary>
		/// Performing Arts.
		/// </summary>
		public const string PerformingArts = "\u00ae";

		/// <summary>
		/// Beamed Ascending Musical Notes.
		/// </summary>
		public const string BeamedAscendingMusicalNotes = "\u00af";

		/// <summary>
		/// Musical Keyboard With Jacks.
		/// </summary>
		public const string MusicalKeyboardWithJacks = "\u00b0";

		/// <summary>
		/// Studio Microphone.
		/// </summary>
		public const string StudioMicrophone = "\u00b1";

		/// <summary>
		/// Headphone.
		/// </summary>
		public const string Headphone = "\u00b2";

		/// <summary>
		/// Optical Disc.
		/// </summary>
		public const string OpticalDisc = "\u00b3";

		/// <summary>
		/// Film Frames.
		/// </summary>
		public const string FilmFrames = "\u00b4";

		/// <summary>
		/// Camera.
		/// </summary>
		public const string Camera = "\u00b5";

		/// <summary>
		/// Admission Tickets.
		/// </summary>
		public const string AdmissionTickets = "\u00b6";

		/// <summary>
		/// Clapper Board.
		/// </summary>
		public const string ClapperBoard = "\u00b7";

		/// <summary>
		/// Film Projector.
		/// </summary>
		public const string FilmProjector = "\u00b8";

		/// <summary>
		/// Video Camera.
		/// </summary>
		public const string VideoCamera = "\u00b9";

		/// <summary>
		/// Portable Stereo.
		/// </summary>
		public const string PortableStereo = "\u00ba";

		/// <summary>
		/// Radio.
		/// </summary>
		public const string Radio = "\u00bb";

		/// <summary>
		/// Level Slider.
		/// </summary>
		public const string LevelSlider = "\u00bc";

		/// <summary>
		/// Control Knobs.
		/// </summary>
		public const string ControlKnobs = "\u00bd";

		/// <summary>
		/// Television.
		/// </summary>
		public const string Television = "\u00be";

		/// <summary>
		/// Personal Computer.
		/// </summary>
		public const string PersonalComputer = "\u00bf";

		/// <summary>
		/// Desktop Computer.
		/// </summary>
		public const string DesktopComputer = "\u00c0";

		/// <summary>
		/// Keyboard And Mouse.
		/// </summary>
		public const string KeyboardAndMouse = "\u00c1";

		/// <summary>
		/// Three Networked Computers.
		/// </summary>
		public const string ThreeNetworkedComputers = "\u00c2";

		/// <summary>
		/// Joystick.
		/// </summary>
		public const string Joystick = "\u00c3";

		/// <summary>
		/// Video Game.
		/// </summary>
		public const string VideoGame = "\u00c4";

		/// <summary>
		/// Left Hand Telephone Receiver.
		/// </summary>
		public const string LeftHandTelephoneReceiver = "\u00c5";

		/// <summary>
		/// Telephone Receiver With Page.
		/// </summary>
		public const string TelephoneReceiverWithPage = "\u00c6";

		/// <summary>
		/// Pager.
		/// </summary>
		public const string Pager = "\u00c7";

		/// <summary>
		/// Clamshell Mobile Phone.
		/// </summary>
		public const string ClamshellMobilePhone = "\u00c8";

		/// <summary>
		/// Telephone On Top Of Modem.
		/// </summary>
		public const string TelephoneOnTopOfModem = "\u00c9";

		/// <summary>
		/// Printer.
		/// </summary>
		public const string Printer = "\u00ca";

		/// <summary>
		/// Pocket Calculator.
		/// </summary>
		public const string PocketCalculator = "\u00cb";

		/// <summary>
		/// Black Folder.
		/// </summary>
		public const string BlackFolder = "\u00cc";

		/// <summary>
		/// Black Hard Shell Floppy Disk.
		/// </summary>
		public const string BlackHardShellFloppyDisk = "\u00cd";

		/// <summary>
		/// Compression.
		/// </summary>
		public const string Compression = "\u00ce";

		/// <summary>
		/// Lock.
		/// </summary>
		public const string Lock = "\u00cf";

		/// <summary>
		/// Open Lock.
		/// </summary>
		public const string OpenLock = "\u00d0";

		/// <summary>
		/// Old Key.
		/// </summary>
		public const string OldKey = "\u00d1";

		/// <summary>
		/// Inbox Tray.
		/// </summary>
		public const string InboxTray = "\u00d2";

		/// <summary>
		/// North East Pointing Leaf.
		/// </summary>
		public const string NorthEastPointingLeaf = "\u00d3";

		/// <summary>
		/// Hole.
		/// </summary>
		public const string Hole = "\u00d4";

		/// <summary>
		/// White Sun.
		/// </summary>
		public const string WhiteSun = "\u00d5";

		/// <summary>
		/// White Sun With Small Cloud.
		/// </summary>
		public const string WhiteSunWithSmallCloud = "\u00d6";

		/// <summary>
		/// White Sun Behind Cloud.
		/// </summary>
		public const string WhiteSunBehindCloud = "\u00d7";

		/// <summary>
		/// White Sun Behind Cloud With Rain.
		/// </summary>
		public const string WhiteSunBehindCloudWithRain = "\u00d8";

		/// <summary>
		/// Cloud.
		/// </summary>
		public const string Cloud = "\u00d9";

		/// <summary>
		/// Cloud With Rain.
		/// </summary>
		public const string CloudWithRain = "\u00da";

		/// <summary>
		/// Cloud With Snow.
		/// </summary>
		public const string CloudWithSnow = "\u00db";

		/// <summary>
		/// Cloud With Lightning.
		/// </summary>
		public const string CloudWithLightning = "\u00dc";

		/// <summary>
		/// Cloud With Tornado.
		/// </summary>
		public const string CloudWithTornado = "\u00dd";

		/// <summary>
		/// Wind Blowing Face.
		/// </summary>
		public const string WindBlowingFace = "\u00de";

		/// <summary>
		/// Fog.
		/// </summary>
		public const string Fog = "\u00df";

		/// <summary>
		/// Last Quarter Moon With Face.
		/// </summary>
		public const string LastQuarterMoonWithFace = "\u00e0";

		/// <summary>
		/// Thermometer.
		/// </summary>
		public const string Thermometer = "\u00e1";

		/// <summary>
		/// Couch And Lamp.
		/// </summary>
		public const string CouchAndLamp = "\u00e2";

		/// <summary>
		/// Bed.
		/// </summary>
		public const string Bed = "\u00e3";

		/// <summary>
		/// Fork And Knife With Plate.
		/// </summary>
		public const string ForkAndKnifeWithPlate = "\u00e4";

		/// <summary>
		/// Cocktail Glass.
		/// </summary>
		public const string CocktailGlass = "\u00e5";

		/// <summary>
		/// Bellhop Bell.
		/// </summary>
		public const string BellhopBell = "\u00e6";

		/// <summary>
		/// Shopping Bags.
		/// </summary>
		public const string ShoppingBags = "\u00e7";

		/// <summary>
		/// Circled Latin Capital Letter P.
		/// </summary>
		public const string CircledLatinCapitalLetterP = "\u00e8";

		/// <summary>
		/// Wheelchair Symbol.
		/// </summary>
		public const string WheelchairSymbol = "\u00e9";

		/// <summary>
		/// Triangle With Rounded Corners.
		/// </summary>
		public const string TriangleWithRoundedCorners = "\u00ea";

		/// <summary>
		/// Black Pushpin.
		/// </summary>
		public const string BlackPushpin = "\u00eb";

		/// <summary>
		/// Graduation Cap.
		/// </summary>
		public const string GraduationCap = "\u00ec";

		/// <summary>
		/// Three Rays Above.
		/// </summary>
		public const string ThreeRaysAbove = "\u00ed";

		/// <summary>
		/// Three Rays Below.
		/// </summary>
		public const string ThreeRaysBelow = "\u00ee";

		/// <summary>
		/// Three Rays Left.
		/// </summary>
		public const string ThreeRaysLeft = "\u00ef";

		/// <summary>
		/// Three Rays Right.
		/// </summary>
		public const string ThreeRaysRight = "\u00f0";

		/// <summary>
		/// Northeast-Pointing Airplane.
		/// </summary>
		public const string NortheastPointingAirplane = "\u00f1";

		/// <summary>
		/// Chipmunk.
		/// </summary>
		public const string Chipmunk = "\u00f2";

		/// <summary>
		/// Bird.
		/// </summary>
		public const string Bird = "\u00f3";

		/// <summary>
		/// Fish.
		/// </summary>
		public const string Fish = "\u00f4";

		/// <summary>
		/// Dog.
		/// </summary>
		public const string Dog = "\u00f5";

		/// <summary>
		/// Cat.
		/// </summary>
		public const string Cat = "\u00f6";

		/// <summary>
		/// Leftwards Rocket.
		/// </summary>
		public const string LeftwardsRocket = "\u00f7";

		/// <summary>
		/// Rightwards Rocket.
		/// </summary>
		public const string RightwardsRocket = "\u00f8";

		/// <summary>
		/// Upwards Rocket.
		/// </summary>
		public const string UpwardsRocket = "\u00f9";

		/// <summary>
		/// Downwards Rocket.
		/// </summary>
		public const string DownwardsRocket = "\u00fa";

		/// <summary>
		/// World Map.
		/// </summary>
		public const string WorldMap = "\u00fb";

		/// <summary>
		/// Earth Globe Europe-Africa.
		/// </summary>
		public const string EarthGlobeEuropeAfrica = "\u00fc";

		/// <summary>
		/// Earth Globe Asia-Australia.
		/// </summary>
		public const string EarthGlobeAsiaAustralia = "\u00fd";

		/// <summary>
		/// Earth Globe Americas.
		/// </summary>
		public const string EarthGlobeAmericas = "\u00fe";

		/// <summary>
		/// Dove Of Peace.
		/// </summary>
		public const string DoveOfPeace = "\u00ff";

		/// <summary>
		/// Device Control Four.
		/// </summary>
		public const string DeviceControlFour_2 = "\uf014";

		/// <summary>
		/// Spider.
		/// </summary>
		public const string Spider_2 = "\uf021";

		/// <summary>
		/// Spider Web.
		/// </summary>
		public const string SpiderWeb_2 = "\uf022";

		/// <summary>
		/// No Piracy.
		/// </summary>
		public const string NoPiracy_2 = "\uf023";

		/// <summary>
		/// Dark Sunglasses.
		/// </summary>
		public const string DarkSunglasses_2 = "\uf024";

		/// <summary>
		/// Trophy.
		/// </summary>
		public const string Trophy_2 = "\uf025";

		/// <summary>
		/// Military Medal.
		/// </summary>
		public const string MilitaryMedal_2 = "\uf026";

		/// <summary>
		/// Linked Paperclips.
		/// </summary>
		public const string LinkedPaperclips_2 = "\uf027";

		/// <summary>
		/// Left Speech Bubble.
		/// </summary>
		public const string LeftSpeechBubble_2 = "\uf028";

		/// <summary>
		/// Right Speech Bubble.
		/// </summary>
		public const string RightSpeechBubble_2 = "\uf029";

		/// <summary>
		/// Mood Bubble.
		/// </summary>
		public const string MoodBubble_2 = "\uf02a";

		/// <summary>
		/// Lightning Mood Bubble.
		/// </summary>
		public const string LightningMoodBubble_2 = "\uf02b";

		/// <summary>
		/// Hot Pepper.
		/// </summary>
		public const string HotPepper_2 = "\uf02c";

		/// <summary>
		/// Reminder Ribbon.
		/// </summary>
		public const string ReminderRibbon_2 = "\uf02d";

		/// <summary>
		/// Checker Board.
		/// </summary>
		public const string CheckerBoard_2 = "\uf02e";

		/// <summary>
		/// Very Heavy Solidus.
		/// </summary>
		public const string VeryHeavySolidus_2 = "\uf02f";

		/// <summary>
		/// Minimize.
		/// </summary>
		public const string Minimize_2 = "\uf030";

		/// <summary>
		/// Maximize.
		/// </summary>
		public const string Maximize_2 = "\uf031";

		/// <summary>
		/// Overlap.
		/// </summary>
		public const string Overlap_2 = "\uf032";

		/// <summary>
		/// Black Medium Left-Pointing Triangle.
		/// </summary>
		public const string BlackMediumLeftPointingTriangle_2 = "\uf033";

		/// <summary>
		/// Black Medium Right-Pointing Triangle.
		/// </summary>
		public const string BlackMediumRightPointingTriangle_2 = "\uf034";

		/// <summary>
		/// Black Medium Up-Pointing Triangle.
		/// </summary>
		public const string BlackMediumUpPointingTriangle_2 = "\uf035";

		/// <summary>
		/// Black Medium Down-Pointing Triangle.
		/// </summary>
		public const string BlackMediumDownPointingTriangle_2 = "\uf036";

		/// <summary>
		/// Black Left-Pointing Double Triangle.
		/// </summary>
		public const string BlackLeftPointingDoubleTriangle_2 = "\uf037";

		/// <summary>
		/// Black Right-Pointing Double Triangle.
		/// </summary>
		public const string BlackRightPointingDoubleTriangle_2 = "\uf038";

		/// <summary>
		/// Black Left-Pointing Double Triangle With Vertical Bar.
		/// </summary>
		public const string BlackLeftPointingDoubleTriangleWithVerticalBar_2 = "\uf039";

		/// <summary>
		/// Black Right-Pointing Double Triangle With Vertical Bar.
		/// </summary>
		public const string BlackRightPointingDoubleTriangleWithVerticalBar_2 = "\uf03a";

		/// <summary>
		/// Double Vertical Bar.
		/// </summary>
		public const string DoubleVerticalBar_2 = "\uf03b";

		/// <summary>
		/// Black Square For Stop.
		/// </summary>
		public const string BlackSquareForStop_2 = "\uf03c";

		/// <summary>
		/// Black Circle For Record.
		/// </summary>
		public const string BlackCircleForRecord_2 = "\uf03d";

		/// <summary>
		/// Increase Font Size Symbol.
		/// </summary>
		public const string IncreaseFontSizeSymbol_2 = "\uf03e";

		/// <summary>
		/// Ballot Box With Ballot.
		/// </summary>
		public const string BallotBoxWithBallot_2 = "\uf03f";

		/// <summary>
		/// Hammer And Wrench.
		/// </summary>
		public const string HammerAndWrench_2 = "\uf040";

		/// <summary>
		/// Building Construction.
		/// </summary>
		public const string BuildingConstruction_2 = "\uf041";

		/// <summary>
		/// House Buildings.
		/// </summary>
		public const string HouseBuildings_2 = "\uf042";

		/// <summary>
		/// Cityscape.
		/// </summary>
		public const string Cityscape_2 = "\uf043";

		/// <summary>
		/// Derelict House Building.
		/// </summary>
		public const string DerelictHouseBuilding_2 = "\uf044";

		/// <summary>
		/// Desert.
		/// </summary>
		public const string Desert_2 = "\uf045";

		/// <summary>
		/// Factory.
		/// </summary>
		public const string Factory_2 = "\uf046";

		/// <summary>
		/// Classical Building.
		/// </summary>
		public const string ClassicalBuilding_2 = "\uf047";

		/// <summary>
		/// House Building.
		/// </summary>
		public const string HouseBuilding_2 = "\uf048";

		/// <summary>
		/// Beach With Umbrella.
		/// </summary>
		public const string BeachWithUmbrella_2 = "\uf049";

		/// <summary>
		/// Desert Island.
		/// </summary>
		public const string DesertIsland_2 = "\uf04a";

		/// <summary>
		/// Motorway.
		/// </summary>
		public const string Motorway_2 = "\uf04b";

		/// <summary>
		/// Left-Pointing Magnifying Glass.
		/// </summary>
		public const string LeftPointingMagnifyingGlass_2 = "\uf04c";

		/// <summary>
		/// Snow Capped Mountain.
		/// </summary>
		public const string SnowCappedMountain_2 = "\uf04d";

		/// <summary>
		/// Eye.
		/// </summary>
		public const string Eye_2 = "\uf04e";

		/// <summary>
		/// Ear.
		/// </summary>
		public const string Ear_2 = "\uf04f";

		/// <summary>
		/// National Park.
		/// </summary>
		public const string NationalPark_2 = "\uf050";

		/// <summary>
		/// Camping.
		/// </summary>
		public const string Camping_2 = "\uf051";

		/// <summary>
		/// Railway Track.
		/// </summary>
		public const string RailwayTrack_2 = "\uf052";

		/// <summary>
		/// Stadium.
		/// </summary>
		public const string Stadium_2 = "\uf053";

		/// <summary>
		/// Passenger Ship.
		/// </summary>
		public const string PassengerShip_2 = "\uf054";

		/// <summary>
		/// Bullhorn With Sound Waves.
		/// </summary>
		public const string BullhornWithSoundWaves_2 = "\uf055";

		/// <summary>
		/// Bullhorn.
		/// </summary>
		public const string Bullhorn_2 = "\uf056";

		/// <summary>
		/// Right Speaker.
		/// </summary>
		public const string RightSpeaker_2 = "\uf057";

		/// <summary>
		/// Speaker.
		/// </summary>
		public const string Speaker_2 = "\uf058";

		/// <summary>
		/// Heart With Tip On The Left.
		/// </summary>
		public const string HeartWithTipOnTheLeft_2 = "\uf059";

		/// <summary>
		/// Bouquet Of Flowers.
		/// </summary>
		public const string BouquetOfFlowers_2 = "\uf05a";

		/// <summary>
		/// Left Thought Bubble.
		/// </summary>
		public const string LeftThoughtBubble_2 = "\uf05b";

		/// <summary>
		/// Very Heavy Reverse Solidus.
		/// </summary>
		public const string VeryHeavyReverseSolidus_2 = "\uf05c";

		/// <summary>
		/// Right Thought Bubble.
		/// </summary>
		public const string RightThoughtBubble_2 = "\uf05d";

		/// <summary>
		/// Two Speech Bubbles.
		/// </summary>
		public const string TwoSpeechBubbles_2 = "\uf05e";

		/// <summary>
		/// Three Speech Bubbles.
		/// </summary>
		public const string ThreeSpeechBubbles_2 = "\uf05f";

		/// <summary>
		/// Four Corner Arrows Circling Anticlockwise.
		/// </summary>
		public const string FourCornerArrowsCirclingAnticlockwise_2 = "\uf060";

		/// <summary>
		/// Heavy Check Mark.
		/// </summary>
		public const string HeavyCheckMark_2 = "\uf061";

		/// <summary>
		/// Bicycle.
		/// </summary>
		public const string Bicycle_2 = "\uf062";

		/// <summary>
		/// White Square.
		/// </summary>
		public const string WhiteSquare_2 = "\uf063";

		/// <summary>
		/// Shield.
		/// </summary>
		public const string Shield_2 = "\uf064";

		/// <summary>
		/// Package.
		/// </summary>
		public const string Package_2 = "\uf065";

		/// <summary>
		/// Oncoming Fire Engine.
		/// </summary>
		public const string OncomingFireEngine_2 = "\uf066";

		/// <summary>
		/// Black Square.
		/// </summary>
		public const string BlackSquare_2 = "\uf067";

		/// <summary>
		/// Ambulance.
		/// </summary>
		public const string Ambulance_2 = "\uf068";

		/// <summary>
		/// Circled Information Source.
		/// </summary>
		public const string CircledInformationSource_2 = "\uf069";

		/// <summary>
		/// Small Airplane.
		/// </summary>
		public const string SmallAirplane_2 = "\uf06a";

		/// <summary>
		/// Satellite.
		/// </summary>
		public const string Satellite_2 = "\uf06b";

		/// <summary>
		/// Reverse Light Four Pointed Pinwheel Star.
		/// </summary>
		public const string ReverseLightFourPointedPinwheelStar_2 = "\uf06c";

		/// <summary>
		/// Man In Business Suit Levitating.
		/// </summary>
		public const string ManInBusinessSuitLevitating_2 = "\uf06d";

		/// <summary>
		/// Medium Black Circle.
		/// </summary>
		public const string MediumBlackCircle_2 = "\uf06e";

		/// <summary>
		/// Motor Boat.
		/// </summary>
		public const string MotorBoat_2 = "\uf06f";

		/// <summary>
		/// Oncoming Police Car.
		/// </summary>
		public const string OncomingPoliceCar_2 = "\uf070";

		/// <summary>
		/// Clockwise Right And Left Semicircle Arrows.
		/// </summary>
		public const string ClockwiseRightAndLeftSemicircleArrows_2 = "\uf071";

		/// <summary>
		/// Cancellation X.
		/// </summary>
		public const string CancellationX_2 = "\uf072";

		/// <summary>
		/// Black Question Mark Ornament.
		/// </summary>
		public const string BlackQuestionMarkOrnament_2 = "\uf073";

		/// <summary>
		/// Diesel Locomotive.
		/// </summary>
		public const string DieselLocomotive_2 = "\uf074";

		/// <summary>
		/// Metro.
		/// </summary>
		public const string Metro_2 = "\uf075";

		/// <summary>
		/// Oncoming Bus.
		/// </summary>
		public const string OncomingBus_2 = "\uf076";

		/// <summary>
		/// Flag In Hole.
		/// </summary>
		public const string FlagInHole_2 = "\uf077";

		/// <summary>
		/// Prohibited Sign.
		/// </summary>
		public const string ProhibitedSign_2 = "\uf078";

		/// <summary>
		/// Circled Minus.
		/// </summary>
		public const string CircledMinus_2 = "\uf079";

		/// <summary>
		/// No Smoking Symbol.
		/// </summary>
		public const string NoSmokingSymbol_2 = "\uf07a";

		/// <summary>
		/// Left Anger Bubble.
		/// </summary>
		public const string LeftAngerBubble_2 = "\uf07b";

		/// <summary>
		/// Vertical Line.
		/// </summary>
		public const string VerticalLine_2 = "\uf07c";

		/// <summary>
		/// Right Anger Bubble.
		/// </summary>
		public const string RightAngerBubble_2 = "\uf07d";

		/// <summary>
		/// Lightning Mood.
		/// </summary>
		public const string LightningMood_2 = "\uf07e";

		/// <summary>
		/// Mens Symbol.
		/// </summary>
		public const string MensSymbol_2 = "\uf080";

		/// <summary>
		/// Womens Symbol.
		/// </summary>
		public const string WomensSymbol_2 = "\uf081";

		/// <summary>
		/// Boys Symbol.
		/// </summary>
		public const string BoysSymbol_2 = "\uf082";

		/// <summary>
		/// Girls Symbol.
		/// </summary>
		public const string GirlsSymbol_2 = "\uf083";

		/// <summary>
		/// Baby Symbol.
		/// </summary>
		public const string BabySymbol_2 = "\uf084";

		/// <summary>
		/// Extraterrestrial Alien.
		/// </summary>
		public const string ExtraterrestrialAlien_2 = "\uf085";

		/// <summary>
		/// Weight Lifter.
		/// </summary>
		public const string WeightLifter_2 = "\uf086";

		/// <summary>
		/// Skier.
		/// </summary>
		public const string Skier_2 = "\uf087";

		/// <summary>
		/// Snowboarder.
		/// </summary>
		public const string Snowboarder_2 = "\uf088";

		/// <summary>
		/// Golfer.
		/// </summary>
		public const string Golfer_2 = "\uf089";

		/// <summary>
		/// Swimmer.
		/// </summary>
		public const string Swimmer_2 = "\uf08a";

		/// <summary>
		/// Surfer.
		/// </summary>
		public const string Surfer_2 = "\uf08b";

		/// <summary>
		/// Racing Motorcycle.
		/// </summary>
		public const string RacingMotorcycle_2 = "\uf08c";

		/// <summary>
		/// Racing Car.
		/// </summary>
		public const string RacingCar_2 = "\uf08d";

		/// <summary>
		/// Oncoming Automobile.
		/// </summary>
		public const string OncomingAutomobile_2 = "\uf08e";

		/// <summary>
		/// Stock Chart.
		/// </summary>
		public const string StockChart_2 = "\uf08f";

		/// <summary>
		/// Oil Drum.
		/// </summary>
		public const string OilDrum_2 = "\uf090";

		/// <summary>
		/// Money Bag.
		/// </summary>
		public const string MoneyBag_2 = "\uf091";

		/// <summary>
		/// Label.
		/// </summary>
		public const string Label_2 = "\uf092";

		/// <summary>
		/// Credit Card.
		/// </summary>
		public const string CreditCard_2 = "\uf093";

		/// <summary>
		/// Family.
		/// </summary>
		public const string Family_2 = "\uf094";

		/// <summary>
		/// Dagger Knife.
		/// </summary>
		public const string DaggerKnife_2 = "\uf095";

		/// <summary>
		/// Lips.
		/// </summary>
		public const string Lips_2 = "\uf096";

		/// <summary>
		/// Speaking Head In Silhouette.
		/// </summary>
		public const string SpeakingHeadInSilhouette_2 = "\uf097";

		/// <summary>
		/// Pinwheel Star.
		/// </summary>
		public const string PinwheelStar_2 = "\uf098";

		/// <summary>
		/// Envelope With Lightning.
		/// </summary>
		public const string EnvelopeWithLightning_2 = "\uf099";

		/// <summary>
		/// Flying Envelope.
		/// </summary>
		public const string FlyingEnvelope_2 = "\uf09a";

		/// <summary>
		/// Stamped Envelope.
		/// </summary>
		public const string StampedEnvelope_2 = "\uf09b";

		/// <summary>
		/// Pen Over Stamped Envelope.
		/// </summary>
		public const string PenOverStampedEnvelope_2 = "\uf09c";

		/// <summary>
		/// Document With Text.
		/// </summary>
		public const string DocumentWithText_2 = "\uf09d";

		/// <summary>
		/// Document With Text And Picture.
		/// </summary>
		public const string DocumentWithTextAndPicture_2 = "\uf09e";

		/// <summary>
		/// Document With Picture.
		/// </summary>
		public const string DocumentWithPicture_2 = "\uf09f";

		/// <summary>
		/// Sleuth Or Spy.
		/// </summary>
		public const string SleuthOrSpy_2 = "\uf0a0";

		/// <summary>
		/// Mantelpiece Clock.
		/// </summary>
		public const string MantelpieceClock_2 = "\uf0a1";

		/// <summary>
		/// Frame With Tiles.
		/// </summary>
		public const string FrameWithTiles_2 = "\uf0a2";

		/// <summary>
		/// Frame With An X.
		/// </summary>
		public const string FrameWithAnX_2 = "\uf0a3";

		/// <summary>
		/// Clipboard.
		/// </summary>
		public const string Clipboard_2 = "\uf0a4";

		/// <summary>
		/// Spiral Note Pad.
		/// </summary>
		public const string SpiralNotePad_2 = "\uf0a5";

		/// <summary>
		/// Spiral Calendar Pad.
		/// </summary>
		public const string SpiralCalendarPad_2 = "\uf0a6";

		/// <summary>
		/// Open Book.
		/// </summary>
		public const string OpenBook_2 = "\uf0a7";

		/// <summary>
		/// Books.
		/// </summary>
		public const string Books_2 = "\uf0a8";

		/// <summary>
		/// Rolled-Up Newspaper.
		/// </summary>
		public const string RolledUpNewspaper_2 = "\uf0a9";

		/// <summary>
		/// Page With Circled Text.
		/// </summary>
		public const string PageWithCircledText_2 = "\uf0aa";

		/// <summary>
		/// Card File Box.
		/// </summary>
		public const string CardFileBox_2 = "\uf0ab";

		/// <summary>
		/// Card Index Dividers.
		/// </summary>
		public const string CardIndexDividers_2 = "\uf0ac";

		/// <summary>
		/// Frame With Picture.
		/// </summary>
		public const string FrameWithPicture_2 = "\uf0ad";

		/// <summary>
		/// Performing Arts.
		/// </summary>
		public const string PerformingArts_2 = "\uf0ae";

		/// <summary>
		/// Beamed Ascending Musical Notes.
		/// </summary>
		public const string BeamedAscendingMusicalNotes_2 = "\uf0af";

		/// <summary>
		/// Musical Keyboard With Jacks.
		/// </summary>
		public const string MusicalKeyboardWithJacks_2 = "\uf0b0";

		/// <summary>
		/// Studio Microphone.
		/// </summary>
		public const string StudioMicrophone_2 = "\uf0b1";

		/// <summary>
		/// Headphone.
		/// </summary>
		public const string Headphone_2 = "\uf0b2";

		/// <summary>
		/// Optical Disc.
		/// </summary>
		public const string OpticalDisc_2 = "\uf0b3";

		/// <summary>
		/// Film Frames.
		/// </summary>
		public const string FilmFrames_2 = "\uf0b4";

		/// <summary>
		/// Camera.
		/// </summary>
		public const string Camera_2 = "\uf0b5";

		/// <summary>
		/// Admission Tickets.
		/// </summary>
		public const string AdmissionTickets_2 = "\uf0b6";

		/// <summary>
		/// Clapper Board.
		/// </summary>
		public const string ClapperBoard_2 = "\uf0b7";

		/// <summary>
		/// Film Projector.
		/// </summary>
		public const string FilmProjector_2 = "\uf0b8";

		/// <summary>
		/// Video Camera.
		/// </summary>
		public const string VideoCamera_2 = "\uf0b9";

		/// <summary>
		/// Portable Stereo.
		/// </summary>
		public const string PortableStereo_2 = "\uf0ba";

		/// <summary>
		/// Radio.
		/// </summary>
		public const string Radio_2 = "\uf0bb";

		/// <summary>
		/// Level Slider.
		/// </summary>
		public const string LevelSlider_2 = "\uf0bc";

		/// <summary>
		/// Control Knobs.
		/// </summary>
		public const string ControlKnobs_2 = "\uf0bd";

		/// <summary>
		/// Television.
		/// </summary>
		public const string Television_2 = "\uf0be";

		/// <summary>
		/// Personal Computer.
		/// </summary>
		public const string PersonalComputer_2 = "\uf0bf";

		/// <summary>
		/// Desktop Computer.
		/// </summary>
		public const string DesktopComputer_2 = "\uf0c0";

		/// <summary>
		/// Keyboard And Mouse.
		/// </summary>
		public const string KeyboardAndMouse_2 = "\uf0c1";

		/// <summary>
		/// Three Networked Computers.
		/// </summary>
		public const string ThreeNetworkedComputers_2 = "\uf0c2";

		/// <summary>
		/// Joystick.
		/// </summary>
		public const string Joystick_2 = "\uf0c3";

		/// <summary>
		/// Video Game.
		/// </summary>
		public const string VideoGame_2 = "\uf0c4";

		/// <summary>
		/// Left Hand Telephone Receiver.
		/// </summary>
		public const string LeftHandTelephoneReceiver_2 = "\uf0c5";

		/// <summary>
		/// Telephone Receiver With Page.
		/// </summary>
		public const string TelephoneReceiverWithPage_2 = "\uf0c6";

		/// <summary>
		/// Pager.
		/// </summary>
		public const string Pager_2 = "\uf0c7";

		/// <summary>
		/// Clamshell Mobile Phone.
		/// </summary>
		public const string ClamshellMobilePhone_2 = "\uf0c8";

		/// <summary>
		/// Telephone On Top Of Modem.
		/// </summary>
		public const string TelephoneOnTopOfModem_2 = "\uf0c9";

		/// <summary>
		/// Printer.
		/// </summary>
		public const string Printer_2 = "\uf0ca";

		/// <summary>
		/// Pocket Calculator.
		/// </summary>
		public const string PocketCalculator_2 = "\uf0cb";

		/// <summary>
		/// Black Folder.
		/// </summary>
		public const string BlackFolder_2 = "\uf0cc";

		/// <summary>
		/// Black Hard Shell Floppy Disk.
		/// </summary>
		public const string BlackHardShellFloppyDisk_2 = "\uf0cd";

		/// <summary>
		/// Compression.
		/// </summary>
		public const string Compression_2 = "\uf0ce";

		/// <summary>
		/// Lock.
		/// </summary>
		public const string Lock_2 = "\uf0cf";

		/// <summary>
		/// Open Lock.
		/// </summary>
		public const string OpenLock_2 = "\uf0d0";

		/// <summary>
		/// Old Key.
		/// </summary>
		public const string OldKey_2 = "\uf0d1";

		/// <summary>
		/// Inbox Tray.
		/// </summary>
		public const string InboxTray_2 = "\uf0d2";

		/// <summary>
		/// North East Pointing Leaf.
		/// </summary>
		public const string NorthEastPointingLeaf_2 = "\uf0d3";

		/// <summary>
		/// Hole.
		/// </summary>
		public const string Hole_2 = "\uf0d4";

		/// <summary>
		/// White Sun.
		/// </summary>
		public const string WhiteSun_2 = "\uf0d5";

		/// <summary>
		/// White Sun With Small Cloud.
		/// </summary>
		public const string WhiteSunWithSmallCloud_2 = "\uf0d6";

		/// <summary>
		/// White Sun Behind Cloud.
		/// </summary>
		public const string WhiteSunBehindCloud_2 = "\uf0d7";

		/// <summary>
		/// White Sun Behind Cloud With Rain.
		/// </summary>
		public const string WhiteSunBehindCloudWithRain_2 = "\uf0d8";

		/// <summary>
		/// Cloud.
		/// </summary>
		public const string Cloud_2 = "\uf0d9";

		/// <summary>
		/// Cloud With Rain.
		/// </summary>
		public const string CloudWithRain_2 = "\uf0da";

		/// <summary>
		/// Cloud With Snow.
		/// </summary>
		public const string CloudWithSnow_2 = "\uf0db";

		/// <summary>
		/// Cloud With Lightning.
		/// </summary>
		public const string CloudWithLightning_2 = "\uf0dc";

		/// <summary>
		/// Cloud With Tornado.
		/// </summary>
		public const string CloudWithTornado_2 = "\uf0dd";

		/// <summary>
		/// Wind Blowing Face.
		/// </summary>
		public const string WindBlowingFace_2 = "\uf0de";

		/// <summary>
		/// Fog.
		/// </summary>
		public const string Fog_2 = "\uf0df";

		/// <summary>
		/// Last Quarter Moon With Face.
		/// </summary>
		public const string LastQuarterMoonWithFace_2 = "\uf0e0";

		/// <summary>
		/// Thermometer.
		/// </summary>
		public const string Thermometer_2 = "\uf0e1";

		/// <summary>
		/// Couch And Lamp.
		/// </summary>
		public const string CouchAndLamp_2 = "\uf0e2";

		/// <summary>
		/// Bed.
		/// </summary>
		public const string Bed_2 = "\uf0e3";

		/// <summary>
		/// Fork And Knife With Plate.
		/// </summary>
		public const string ForkAndKnifeWithPlate_2 = "\uf0e4";

		/// <summary>
		/// Cocktail Glass.
		/// </summary>
		public const string CocktailGlass_2 = "\uf0e5";

		/// <summary>
		/// Bellhop Bell.
		/// </summary>
		public const string BellhopBell_2 = "\uf0e6";

		/// <summary>
		/// Shopping Bags.
		/// </summary>
		public const string ShoppingBags_2 = "\uf0e7";

		/// <summary>
		/// Circled Latin Capital Letter P.
		/// </summary>
		public const string CircledLatinCapitalLetterP_2 = "\uf0e8";

		/// <summary>
		/// Wheelchair Symbol.
		/// </summary>
		public const string WheelchairSymbol_2 = "\uf0e9";

		/// <summary>
		/// Triangle With Rounded Corners.
		/// </summary>
		public const string TriangleWithRoundedCorners_2 = "\uf0ea";

		/// <summary>
		/// Black Pushpin.
		/// </summary>
		public const string BlackPushpin_2 = "\uf0eb";

		/// <summary>
		/// Graduation Cap.
		/// </summary>
		public const string GraduationCap_2 = "\uf0ec";

		/// <summary>
		/// Three Rays Above.
		/// </summary>
		public const string ThreeRaysAbove_2 = "\uf0ed";

		/// <summary>
		/// Three Rays Below.
		/// </summary>
		public const string ThreeRaysBelow_2 = "\uf0ee";

		/// <summary>
		/// Three Rays Left.
		/// </summary>
		public const string ThreeRaysLeft_2 = "\uf0ef";

		/// <summary>
		/// Three Rays Right.
		/// </summary>
		public const string ThreeRaysRight_2 = "\uf0f0";

		/// <summary>
		/// Northeast-Pointing Airplane.
		/// </summary>
		public const string NortheastPointingAirplane_2 = "\uf0f1";

		/// <summary>
		/// Chipmunk.
		/// </summary>
		public const string Chipmunk_2 = "\uf0f2";

		/// <summary>
		/// Bird.
		/// </summary>
		public const string Bird_2 = "\uf0f3";

		/// <summary>
		/// Fish.
		/// </summary>
		public const string Fish_2 = "\uf0f4";

		/// <summary>
		/// Dog.
		/// </summary>
		public const string Dog_2 = "\uf0f5";

		/// <summary>
		/// Cat.
		/// </summary>
		public const string Cat_2 = "\uf0f6";

		/// <summary>
		/// Leftwards Rocket.
		/// </summary>
		public const string LeftwardsRocket_2 = "\uf0f7";

		/// <summary>
		/// Rightwards Rocket.
		/// </summary>
		public const string RightwardsRocket_2 = "\uf0f8";

		/// <summary>
		/// Upwards Rocket.
		/// </summary>
		public const string UpwardsRocket_2 = "\uf0f9";

		/// <summary>
		/// Downwards Rocket.
		/// </summary>
		public const string DownwardsRocket_2 = "\uf0fa";

		/// <summary>
		/// World Map.
		/// </summary>
		public const string WorldMap_2 = "\uf0fb";

		/// <summary>
		/// Earth Globe Europe-Africa.
		/// </summary>
		public const string EarthGlobeEuropeAfrica_2 = "\uf0fc";

		/// <summary>
		/// Earth Globe Asia-Australia.
		/// </summary>
		public const string EarthGlobeAsiaAustralia_2 = "\uf0fd";

		/// <summary>
		/// Earth Globe Americas.
		/// </summary>
		public const string EarthGlobeAmericas_2 = "\uf0fe";

		/// <summary>
		/// Dove Of Peace.
		/// </summary>
		public const string DoveOfPeace_2 = "\uf0ff";
	}
}
