//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirectN
{
	/// <summary>
	/// WingdingsGlyph Enums.
	/// </summary>
	public enum WingdingsGlyphEnum
	{
		/// <summary>
		/// Device Control Four.
		/// </summary>
		DeviceControlFour = 0x0014,

		/// <summary>
		/// Lower Left Pencil.
		/// </summary>
		LowerLeftPencil = 0x0021,

		/// <summary>
		/// Black Scissors.
		/// </summary>
		BlackScissors = 0x0022,

		/// <summary>
		/// Upper Blade Scissors.
		/// </summary>
		UpperBladeScissors = 0x0023,

		/// <summary>
		/// Eyeglasses.
		/// </summary>
		Eyeglasses = 0x0024,

		/// <summary>
		/// Ringing Bell.
		/// </summary>
		RingingBell = 0x0025,

		/// <summary>
		/// Book.
		/// </summary>
		Book = 0x0026,

		/// <summary>
		/// Candle.
		/// </summary>
		Candle = 0x0027,

		/// <summary>
		/// Black Touchtone Telephone.
		/// </summary>
		BlackTouchtoneTelephone = 0x0028,

		/// <summary>
		/// Telephone Location Sign.
		/// </summary>
		TelephoneLocationSign = 0x0029,

		/// <summary>
		/// Back Of Envelope.
		/// </summary>
		BackOfEnvelope = 0x002a,

		/// <summary>
		/// Stamped Envelope.
		/// </summary>
		StampedEnvelope = 0x002b,

		/// <summary>
		/// Closed Mailbox With Lowered Flag.
		/// </summary>
		ClosedMailboxWithLoweredFlag = 0x002c,

		/// <summary>
		/// Closed Mailbox With Raised Flag.
		/// </summary>
		ClosedMailboxWithRaisedFlag = 0x002d,

		/// <summary>
		/// Open Mailbox With Raised Flag.
		/// </summary>
		OpenMailboxWithRaisedFlag = 0x002e,

		/// <summary>
		/// Open Mailbox With Lowered Flag.
		/// </summary>
		OpenMailboxWithLoweredFlag = 0x002f,

		/// <summary>
		/// File Folder.
		/// </summary>
		FileFolder = 0x0030,

		/// <summary>
		/// Open File Folder.
		/// </summary>
		OpenFileFolder = 0x0031,

		/// <summary>
		/// Page Facing Up.
		/// </summary>
		PageFacingUp = 0x0032,

		/// <summary>
		/// Page.
		/// </summary>
		Page = 0x0033,

		/// <summary>
		/// Pages.
		/// </summary>
		Pages = 0x0034,

		/// <summary>
		/// File Cabinet.
		/// </summary>
		FileCabinet = 0x0035,

		/// <summary>
		/// Hourglass.
		/// </summary>
		Hourglass = 0x0036,

		/// <summary>
		/// Wired Keyboard.
		/// </summary>
		WiredKeyboard = 0x0037,

		/// <summary>
		/// Two Button Mouse.
		/// </summary>
		TwoButtonMouse = 0x0038,

		/// <summary>
		/// Trackball.
		/// </summary>
		Trackball = 0x0039,

		/// <summary>
		/// Old Personal Computer.
		/// </summary>
		OldPersonalComputer = 0x003a,

		/// <summary>
		/// Hard Disk.
		/// </summary>
		HardDisk = 0x003b,

		/// <summary>
		/// White Hard Shell Floppy Disk.
		/// </summary>
		WhiteHardShellFloppyDisk = 0x003c,

		/// <summary>
		/// Soft Shell Floppy Disk.
		/// </summary>
		SoftShellFloppyDisk = 0x003d,

		/// <summary>
		/// Tape Drive.
		/// </summary>
		TapeDrive = 0x003e,

		/// <summary>
		/// Writing Hand.
		/// </summary>
		WritingHand = 0x003f,

		/// <summary>
		/// Left Writing Hand.
		/// </summary>
		LeftWritingHand = 0x0040,

		/// <summary>
		/// Victory Hand.
		/// </summary>
		VictoryHand = 0x0041,

		/// <summary>
		/// Ok Hand Sign.
		/// </summary>
		OkHandSign = 0x0042,

		/// <summary>
		/// Thumbs Up Sign.
		/// </summary>
		ThumbsUpSign = 0x0043,

		/// <summary>
		/// Thumbs Down Sign.
		/// </summary>
		ThumbsDownSign = 0x0044,

		/// <summary>
		/// White Left Pointing Index.
		/// </summary>
		WhiteLeftPointingIndex = 0x0045,

		/// <summary>
		/// White Right Pointing Index.
		/// </summary>
		WhiteRightPointingIndex = 0x0046,

		/// <summary>
		/// White Up Pointing Index.
		/// </summary>
		WhiteUpPointingIndex = 0x0047,

		/// <summary>
		/// White Down Pointing Index.
		/// </summary>
		WhiteDownPointingIndex = 0x0048,

		/// <summary>
		/// Raised Hand With Fingers Splayed.
		/// </summary>
		RaisedHandWithFingersSplayed = 0x0049,

		/// <summary>
		/// White Smiling Face.
		/// </summary>
		WhiteSmilingFace = 0x004a,

		/// <summary>
		/// Neutral Face.
		/// </summary>
		NeutralFace = 0x004b,

		/// <summary>
		/// White Frowning Face.
		/// </summary>
		WhiteFrowningFace = 0x004c,

		/// <summary>
		/// Bomb.
		/// </summary>
		Bomb = 0x004d,

		/// <summary>
		/// Skull And Crossbones.
		/// </summary>
		SkullAndCrossbones = 0x004e,

		/// <summary>
		/// Waving White Flag.
		/// </summary>
		WavingWhiteFlag = 0x004f,

		/// <summary>
		/// White Pennant.
		/// </summary>
		WhitePennant = 0x0050,

		/// <summary>
		/// Airplane.
		/// </summary>
		Airplane = 0x0051,

		/// <summary>
		/// White Sun With Rays.
		/// </summary>
		WhiteSunWithRays = 0x0052,

		/// <summary>
		/// Droplet.
		/// </summary>
		Droplet = 0x0053,

		/// <summary>
		/// Snowflake.
		/// </summary>
		Snowflake = 0x0054,

		/// <summary>
		/// White Latin Cross.
		/// </summary>
		WhiteLatinCross = 0x0055,

		/// <summary>
		/// Shadowed White Latin Cross.
		/// </summary>
		ShadowedWhiteLatinCross = 0x0056,

		/// <summary>
		/// Celtic Cross.
		/// </summary>
		CelticCross = 0x0057,

		/// <summary>
		/// Maltese Cross.
		/// </summary>
		MalteseCross = 0x0058,

		/// <summary>
		/// Star Of David.
		/// </summary>
		StarOfDavid = 0x0059,

		/// <summary>
		/// Star And Crescent.
		/// </summary>
		StarAndCrescent = 0x005a,

		/// <summary>
		/// Yin Yang.
		/// </summary>
		YinYang = 0x005b,

		/// <summary>
		/// Devanagari Om.
		/// </summary>
		DevanagariOm = 0x005c,

		/// <summary>
		/// Wheel Of Dharma.
		/// </summary>
		WheelOfDharma = 0x005d,

		/// <summary>
		/// Aries.
		/// </summary>
		Aries = 0x005e,

		/// <summary>
		/// Taurus.
		/// </summary>
		Taurus = 0x005f,

		/// <summary>
		/// Gemini.
		/// </summary>
		Gemini = 0x0060,

		/// <summary>
		/// Cancer.
		/// </summary>
		Cancer = 0x0061,

		/// <summary>
		/// Leo.
		/// </summary>
		Leo = 0x0062,

		/// <summary>
		/// Virgo.
		/// </summary>
		Virgo = 0x0063,

		/// <summary>
		/// Libra.
		/// </summary>
		Libra = 0x0064,

		/// <summary>
		/// Scorpius.
		/// </summary>
		Scorpius = 0x0065,

		/// <summary>
		/// Sagittarius.
		/// </summary>
		Sagittarius = 0x0066,

		/// <summary>
		/// Capricorn.
		/// </summary>
		Capricorn = 0x0067,

		/// <summary>
		/// Aquarius.
		/// </summary>
		Aquarius = 0x0068,

		/// <summary>
		/// Pisces.
		/// </summary>
		Pisces = 0x0069,

		/// <summary>
		/// Script Ligature Et Ornament.
		/// </summary>
		ScriptLigatureEtOrnament = 0x006a,

		/// <summary>
		/// Swash Ampersand Ornament.
		/// </summary>
		SwashAmpersandOrnament = 0x006b,

		/// <summary>
		/// Black Circle.
		/// </summary>
		BlackCircle = 0x006c,

		/// <summary>
		/// Lower Right Shadowed White Circle.
		/// </summary>
		LowerRightShadowedWhiteCircle = 0x006d,

		/// <summary>
		/// Black Square.
		/// </summary>
		BlackSquare = 0x006e,

		/// <summary>
		/// White Square.
		/// </summary>
		WhiteSquare = 0x006f,

		/// <summary>
		/// Bold White Square.
		/// </summary>
		BoldWhiteSquare = 0x0070,

		/// <summary>
		/// Lower Right Shadowed White Square.
		/// </summary>
		LowerRightShadowedWhiteSquare = 0x0071,

		/// <summary>
		/// Upper Right Shadowed White Square.
		/// </summary>
		UpperRightShadowedWhiteSquare = 0x0072,

		/// <summary>
		/// Black Medium Lozenge.
		/// </summary>
		BlackMediumLozenge = 0x0073,

		/// <summary>
		/// Black Lozenge.
		/// </summary>
		BlackLozenge = 0x0074,

		/// <summary>
		/// Black Diamond.
		/// </summary>
		BlackDiamond = 0x0075,

		/// <summary>
		/// Black Diamond Minus White X.
		/// </summary>
		BlackDiamondMinusWhiteX = 0x0076,

		/// <summary>
		/// Black Medium Diamond.
		/// </summary>
		BlackMediumDiamond = 0x0077,

		/// <summary>
		/// X In A Rectangle Box.
		/// </summary>
		XInARectangleBox = 0x0078,

		/// <summary>
		/// Up Arrowhead In A Rectangle Box.
		/// </summary>
		UpArrowheadInARectangleBox = 0x0079,

		/// <summary>
		/// Place Of Interest Sign.
		/// </summary>
		PlaceOfInterestSign = 0x007a,

		/// <summary>
		/// Rosette.
		/// </summary>
		Rosette = 0x007b,

		/// <summary>
		/// Black Rosette.
		/// </summary>
		BlackRosette = 0x007c,

		/// <summary>
		/// Sans-Serif Heavy Double Turned Comma Quotation Mark Ornament.
		/// </summary>
		SansSerifHeavyDoubleTurnedCommaQuotationMarkOrnament = 0x007d,

		/// <summary>
		/// Sans-Serif Heavy Double Comma Quotation Mark Ornament.
		/// </summary>
		SansSerifHeavyDoubleCommaQuotationMarkOrnament = 0x007e,

		/// <summary>
		/// Circled Digit Zero.
		/// </summary>
		CircledDigitZero = 0x0080,

		/// <summary>
		/// Circled Digit One.
		/// </summary>
		CircledDigitOne = 0x0081,

		/// <summary>
		/// Circled Digit Two.
		/// </summary>
		CircledDigitTwo = 0x0082,

		/// <summary>
		/// Circled Digit Three.
		/// </summary>
		CircledDigitThree = 0x0083,

		/// <summary>
		/// Circled Digit Four.
		/// </summary>
		CircledDigitFour = 0x0084,

		/// <summary>
		/// Circled Digit Five.
		/// </summary>
		CircledDigitFive = 0x0085,

		/// <summary>
		/// Circled Digit Six.
		/// </summary>
		CircledDigitSix = 0x0086,

		/// <summary>
		/// Circled Digit Seven.
		/// </summary>
		CircledDigitSeven = 0x0087,

		/// <summary>
		/// Circled Digit Eight.
		/// </summary>
		CircledDigitEight = 0x0088,

		/// <summary>
		/// Circled Digit Nine.
		/// </summary>
		CircledDigitNine = 0x0089,

		/// <summary>
		/// Circled Number Ten.
		/// </summary>
		CircledNumberTen = 0x008a,

		/// <summary>
		/// Negative Circled Digit Zero.
		/// </summary>
		NegativeCircledDigitZero = 0x008b,

		/// <summary>
		/// Dingbat Negative Circled Digit One.
		/// </summary>
		DingbatNegativeCircledDigitOne = 0x008c,

		/// <summary>
		/// Dingbat Negative Circled Digit Two.
		/// </summary>
		DingbatNegativeCircledDigitTwo = 0x008d,

		/// <summary>
		/// Dingbat Negative Circled Digit Three.
		/// </summary>
		DingbatNegativeCircledDigitThree = 0x008e,

		/// <summary>
		/// Dingbat Negative Circled Digit Four.
		/// </summary>
		DingbatNegativeCircledDigitFour = 0x008f,

		/// <summary>
		/// Dingbat Negative Circled Digit Five.
		/// </summary>
		DingbatNegativeCircledDigitFive = 0x0090,

		/// <summary>
		/// Dingbat Negative Circled Digit Six.
		/// </summary>
		DingbatNegativeCircledDigitSix = 0x0091,

		/// <summary>
		/// Dingbat Negative Circled Digit Seven.
		/// </summary>
		DingbatNegativeCircledDigitSeven = 0x0092,

		/// <summary>
		/// Dingbat Negative Circled Digit Eight.
		/// </summary>
		DingbatNegativeCircledDigitEight = 0x0093,

		/// <summary>
		/// Dingbat Negative Circled Digit Nine.
		/// </summary>
		DingbatNegativeCircledDigitNine = 0x0094,

		/// <summary>
		/// Dingbat Negative Circled Number Ten.
		/// </summary>
		DingbatNegativeCircledNumberTen = 0x0095,

		/// <summary>
		/// North East Pointing Bud.
		/// </summary>
		NorthEastPointingBud = 0x0096,

		/// <summary>
		/// North West Pointing Bud.
		/// </summary>
		NorthWestPointingBud = 0x0097,

		/// <summary>
		/// South West Pointing Bud.
		/// </summary>
		SouthWestPointingBud = 0x0098,

		/// <summary>
		/// South East Pointing Bud.
		/// </summary>
		SouthEastPointingBud = 0x0099,

		/// <summary>
		/// Heavy North East Pointing Vine Leaf.
		/// </summary>
		HeavyNorthEastPointingVineLeaf = 0x009a,

		/// <summary>
		/// Heavy North West Pointing Vine Leaf.
		/// </summary>
		HeavyNorthWestPointingVineLeaf = 0x009b,

		/// <summary>
		/// Heavy South West Pointing Vine Leaf.
		/// </summary>
		HeavySouthWestPointingVineLeaf = 0x009c,

		/// <summary>
		/// Heavy South East Pointing Vine Leaf.
		/// </summary>
		HeavySouthEastPointingVineLeaf = 0x009d,

		/// <summary>
		/// Middle Dot.
		/// </summary>
		MiddleDot = 0x009e,

		/// <summary>
		/// Bullet.
		/// </summary>
		Bullet = 0x009f,

		/// <summary>
		/// Black Small Square.
		/// </summary>
		BlackSmallSquare = 0x00a0,

		/// <summary>
		/// Medium White Circle.
		/// </summary>
		MediumWhiteCircle = 0x00a1,

		/// <summary>
		/// Bold White Circle.
		/// </summary>
		BoldWhiteCircle = 0x00a2,

		/// <summary>
		/// Very Heavy White Circle.
		/// </summary>
		VeryHeavyWhiteCircle = 0x00a3,

		/// <summary>
		/// Fisheye.
		/// </summary>
		Fisheye = 0x00a4,

		/// <summary>
		/// Bullseye.
		/// </summary>
		Bullseye = 0x00a5,

		/// <summary>
		/// Upper Right Shadowed White Circle.
		/// </summary>
		UpperRightShadowedWhiteCircle = 0x00a6,

		/// <summary>
		/// Black Small Square.
		/// </summary>
		BlackSmallSquare_2 = 0x00a7,

		/// <summary>
		/// White Medium Square.
		/// </summary>
		WhiteMediumSquare = 0x00a8,

		/// <summary>
		/// Three Pointed Black Star.
		/// </summary>
		ThreePointedBlackStar = 0x00a9,

		/// <summary>
		/// Black Four Pointed Star.
		/// </summary>
		BlackFourPointedStar = 0x00aa,

		/// <summary>
		/// Black Star.
		/// </summary>
		BlackStar = 0x00ab,

		/// <summary>
		/// Six Pointed Black Star.
		/// </summary>
		SixPointedBlackStar = 0x00ac,

		/// <summary>
		/// Eight Pointed Black Star.
		/// </summary>
		EightPointedBlackStar = 0x00ad,

		/// <summary>
		/// Twelve Pointed Black Star.
		/// </summary>
		TwelvePointedBlackStar = 0x00ae,

		/// <summary>
		/// Eight Pointed Pinwheel Star.
		/// </summary>
		EightPointedPinwheelStar = 0x00af,

		/// <summary>
		/// Square Position Indicator.
		/// </summary>
		SquarePositionIndicator = 0x00b0,

		/// <summary>
		/// Position Indicator.
		/// </summary>
		PositionIndicator = 0x00b1,

		/// <summary>
		/// White Concave-Sided Diamond.
		/// </summary>
		WhiteConcaveSidedDiamond = 0x00b2,

		/// <summary>
		/// Square Lozenge.
		/// </summary>
		SquareLozenge = 0x00b3,

		/// <summary>
		/// Uncertainty Sign.
		/// </summary>
		UncertaintySign = 0x00b4,

		/// <summary>
		/// Circled White Star.
		/// </summary>
		CircledWhiteStar = 0x00b5,

		/// <summary>
		/// Shadowed White Star.
		/// </summary>
		ShadowedWhiteStar = 0x00b6,

		/// <summary>
		/// Clock Face One Oclock.
		/// </summary>
		ClockFaceOneOclock = 0x00b7,

		/// <summary>
		/// Clock Face Two Oclock.
		/// </summary>
		ClockFaceTwoOclock = 0x00b8,

		/// <summary>
		/// Clock Face Three Oclock.
		/// </summary>
		ClockFaceThreeOclock = 0x00b9,

		/// <summary>
		/// Clock Face Four Oclock.
		/// </summary>
		ClockFaceFourOclock = 0x00ba,

		/// <summary>
		/// Clock Face Five Oclock.
		/// </summary>
		ClockFaceFiveOclock = 0x00bb,

		/// <summary>
		/// Clock Face Six Oclock.
		/// </summary>
		ClockFaceSixOclock = 0x00bc,

		/// <summary>
		/// Clock Face Seven Oclock.
		/// </summary>
		ClockFaceSevenOclock = 0x00bd,

		/// <summary>
		/// Clock Face Eight Oclock.
		/// </summary>
		ClockFaceEightOclock = 0x00be,

		/// <summary>
		/// Clock Face Nine Oclock.
		/// </summary>
		ClockFaceNineOclock = 0x00bf,

		/// <summary>
		/// Clock Face Ten Oclock.
		/// </summary>
		ClockFaceTenOclock = 0x00c0,

		/// <summary>
		/// Clock Face Eleven Oclock.
		/// </summary>
		ClockFaceElevenOclock = 0x00c1,

		/// <summary>
		/// Clock Face Twelve Oclock.
		/// </summary>
		ClockFaceTwelveOclock = 0x00c2,

		/// <summary>
		/// Ribbon Arrow Down Left.
		/// </summary>
		RibbonArrowDownLeft = 0x00c3,

		/// <summary>
		/// Ribbon Arrow Down Right.
		/// </summary>
		RibbonArrowDownRight = 0x00c4,

		/// <summary>
		/// Ribbon Arrow Up Left.
		/// </summary>
		RibbonArrowUpLeft = 0x00c5,

		/// <summary>
		/// Ribbon Arrow Up Right.
		/// </summary>
		RibbonArrowUpRight = 0x00c6,

		/// <summary>
		/// Ribbon Arrow Left Up.
		/// </summary>
		RibbonArrowLeftUp = 0x00c7,

		/// <summary>
		/// Ribbon Arrow Right Up.
		/// </summary>
		RibbonArrowRightUp = 0x00c8,

		/// <summary>
		/// Ribbon Arrow Left Down.
		/// </summary>
		RibbonArrowLeftDown = 0x00c9,

		/// <summary>
		/// Ribbon Arrow Right Down.
		/// </summary>
		RibbonArrowRightDown = 0x00ca,

		/// <summary>
		/// Solid Quilt Square Ornament.
		/// </summary>
		SolidQuiltSquareOrnament = 0x00cb,

		/// <summary>
		/// Solid Quilt Square Ornament In Black Square.
		/// </summary>
		SolidQuiltSquareOrnamentInBlackSquare = 0x00cc,

		/// <summary>
		/// Turned South West Pointing Leaf.
		/// </summary>
		TurnedSouthWestPointingLeaf = 0x00cd,

		/// <summary>
		/// Turned North West Pointing Leaf.
		/// </summary>
		TurnedNorthWestPointingLeaf = 0x00ce,

		/// <summary>
		/// Turned South East Pointing Leaf.
		/// </summary>
		TurnedSouthEastPointingLeaf = 0x00cf,

		/// <summary>
		/// Turned North East Pointing Leaf.
		/// </summary>
		TurnedNorthEastPointingLeaf = 0x00d0,

		/// <summary>
		/// North West Pointing Leaf.
		/// </summary>
		NorthWestPointingLeaf = 0x00d1,

		/// <summary>
		/// South West Pointing Leaf.
		/// </summary>
		SouthWestPointingLeaf = 0x00d2,

		/// <summary>
		/// North East Pointing Leaf.
		/// </summary>
		NorthEastPointingLeaf = 0x00d3,

		/// <summary>
		/// South East Pointing Leaf.
		/// </summary>
		SouthEastPointingLeaf = 0x00d4,

		/// <summary>
		/// Erase To The Left.
		/// </summary>
		EraseToTheLeft = 0x00d5,

		/// <summary>
		/// Erase To The Right.
		/// </summary>
		EraseToTheRight = 0x00d6,

		/// <summary>
		/// Three-D Top-Lighted Leftwards Equilateral Arrowhead.
		/// </summary>
		ThreeDTopLightedLeftwardsEquilateralArrowhead = 0x00d7,

		/// <summary>
		/// Three-D Top-Lighted Rightwards Equilateral Arrowhead.
		/// </summary>
		ThreeDTopLightedRightwardsEquilateralArrowhead = 0x00d8,

		/// <summary>
		/// Three-D Right-Lighted Upwards Equilateral Arrowhead.
		/// </summary>
		ThreeDRightLightedUpwardsEquilateralArrowhead = 0x00d9,

		/// <summary>
		/// Three-D Left-Lighted Downwards Equilateral Arrowhead.
		/// </summary>
		ThreeDLeftLightedDownwardsEquilateralArrowhead = 0x00da,

		/// <summary>
		/// Leftwards Black Circled White Arrow.
		/// </summary>
		LeftwardsBlackCircledWhiteArrow = 0x00db,

		/// <summary>
		/// Rightwards Black Circled White Arrow.
		/// </summary>
		RightwardsBlackCircledWhiteArrow = 0x00dc,

		/// <summary>
		/// Upwards Black Circled White Arrow.
		/// </summary>
		UpwardsBlackCircledWhiteArrow = 0x00dd,

		/// <summary>
		/// Downwards Black Circled White Arrow.
		/// </summary>
		DownwardsBlackCircledWhiteArrow = 0x00de,

		/// <summary>
		/// Wide-Headed Leftwards Barb Arrow.
		/// </summary>
		WideHeadedLeftwardsBarbArrow = 0x00df,

		/// <summary>
		/// Wide-Headed Rightwards Barb Arrow.
		/// </summary>
		WideHeadedRightwardsBarbArrow = 0x00e0,

		/// <summary>
		/// Wide-Headed Upwards Barb Arrow.
		/// </summary>
		WideHeadedUpwardsBarbArrow = 0x00e1,

		/// <summary>
		/// Wide-Headed Downwards Barb Arrow.
		/// </summary>
		WideHeadedDownwardsBarbArrow = 0x00e2,

		/// <summary>
		/// Wide-Headed North West Barb Arrow.
		/// </summary>
		WideHeadedNorthWestBarbArrow = 0x00e3,

		/// <summary>
		/// Wide-Headed North East Barb Arrow.
		/// </summary>
		WideHeadedNorthEastBarbArrow = 0x00e4,

		/// <summary>
		/// Wide-Headed South West Barb Arrow.
		/// </summary>
		WideHeadedSouthWestBarbArrow = 0x00e5,

		/// <summary>
		/// Wide-Headed South East Barb Arrow.
		/// </summary>
		WideHeadedSouthEastBarbArrow = 0x00e6,

		/// <summary>
		/// Wide-Headed Leftwards Heavy Barb Arrow.
		/// </summary>
		WideHeadedLeftwardsHeavyBarbArrow = 0x00e7,

		/// <summary>
		/// Wide-Headed Rightwards Heavy Barb Arrow.
		/// </summary>
		WideHeadedRightwardsHeavyBarbArrow = 0x00e8,

		/// <summary>
		/// Wide-Headed Upwards Heavy Barb Arrow.
		/// </summary>
		WideHeadedUpwardsHeavyBarbArrow = 0x00e9,

		/// <summary>
		/// Wide-Headed Downwards Heavy Barb Arrow.
		/// </summary>
		WideHeadedDownwardsHeavyBarbArrow = 0x00ea,

		/// <summary>
		/// Wide-Headed North West Heavy Barb Arrow.
		/// </summary>
		WideHeadedNorthWestHeavyBarbArrow = 0x00eb,

		/// <summary>
		/// Wide-Headed North East Heavy Barb Arrow.
		/// </summary>
		WideHeadedNorthEastHeavyBarbArrow = 0x00ec,

		/// <summary>
		/// Wide-Headed South West Heavy Barb Arrow.
		/// </summary>
		WideHeadedSouthWestHeavyBarbArrow = 0x00ed,

		/// <summary>
		/// Wide-Headed South East Heavy Barb Arrow.
		/// </summary>
		WideHeadedSouthEastHeavyBarbArrow = 0x00ee,

		/// <summary>
		/// Leftwards White Arrow.
		/// </summary>
		LeftwardsWhiteArrow = 0x00ef,

		/// <summary>
		/// Rightwards White Arrow.
		/// </summary>
		RightwardsWhiteArrow = 0x00f0,

		/// <summary>
		/// Upwards White Arrow.
		/// </summary>
		UpwardsWhiteArrow = 0x00f1,

		/// <summary>
		/// Downwards White Arrow.
		/// </summary>
		DownwardsWhiteArrow = 0x00f2,

		/// <summary>
		/// Left Right White Arrow.
		/// </summary>
		LeftRightWhiteArrow = 0x00f3,

		/// <summary>
		/// Up Down White Arrow.
		/// </summary>
		UpDownWhiteArrow = 0x00f4,

		/// <summary>
		/// North East White Arrow.
		/// </summary>
		NorthEastWhiteArrow = 0x00f5,

		/// <summary>
		/// North West White Arrow.
		/// </summary>
		NorthWestWhiteArrow = 0x00f6,

		/// <summary>
		/// South West White Arrow.
		/// </summary>
		SouthWestWhiteArrow = 0x00f7,

		/// <summary>
		/// South East White Arrow.
		/// </summary>
		SouthEastWhiteArrow = 0x00f8,

		/// <summary>
		/// White Arrow Shaft Width One.
		/// </summary>
		WhiteArrowShaftWidthOne = 0x00f9,

		/// <summary>
		/// White Arrow Shaft Width Two Thirds.
		/// </summary>
		WhiteArrowShaftWidthTwoThirds = 0x00fa,

		/// <summary>
		/// Ballot Bold Script X.
		/// </summary>
		BallotBoldScriptX = 0x00fb,

		/// <summary>
		/// Heavy Check Mark.
		/// </summary>
		HeavyCheckMark = 0x00fc,

		/// <summary>
		/// Ballot Box With Bold Script X.
		/// </summary>
		BallotBoxWithBoldScriptX = 0x00fd,

		/// <summary>
		/// Ballot Box With Bold Check.
		/// </summary>
		BallotBoxWithBoldCheck = 0x00fe,

		/// <summary>
		/// Windows Flag.
		/// </summary>
		WindowsFlag = 0x00ff,

		/// <summary>
		/// Device Control Four.
		/// </summary>
		DeviceControlFour_2 = 0xf014,

		/// <summary>
		/// Lower Left Pencil.
		/// </summary>
		LowerLeftPencil_2 = 0xf021,

		/// <summary>
		/// Black Scissors.
		/// </summary>
		BlackScissors_2 = 0xf022,

		/// <summary>
		/// Upper Blade Scissors.
		/// </summary>
		UpperBladeScissors_2 = 0xf023,

		/// <summary>
		/// Eyeglasses.
		/// </summary>
		Eyeglasses_2 = 0xf024,

		/// <summary>
		/// Ringing Bell.
		/// </summary>
		RingingBell_2 = 0xf025,

		/// <summary>
		/// Book.
		/// </summary>
		Book_2 = 0xf026,

		/// <summary>
		/// Candle.
		/// </summary>
		Candle_2 = 0xf027,

		/// <summary>
		/// Black Touchtone Telephone.
		/// </summary>
		BlackTouchtoneTelephone_2 = 0xf028,

		/// <summary>
		/// Telephone Location Sign.
		/// </summary>
		TelephoneLocationSign_2 = 0xf029,

		/// <summary>
		/// Back Of Envelope.
		/// </summary>
		BackOfEnvelope_2 = 0xf02a,

		/// <summary>
		/// Stamped Envelope.
		/// </summary>
		StampedEnvelope_2 = 0xf02b,

		/// <summary>
		/// Closed Mailbox With Lowered Flag.
		/// </summary>
		ClosedMailboxWithLoweredFlag_2 = 0xf02c,

		/// <summary>
		/// Closed Mailbox With Raised Flag.
		/// </summary>
		ClosedMailboxWithRaisedFlag_2 = 0xf02d,

		/// <summary>
		/// Open Mailbox With Raised Flag.
		/// </summary>
		OpenMailboxWithRaisedFlag_2 = 0xf02e,

		/// <summary>
		/// Open Mailbox With Lowered Flag.
		/// </summary>
		OpenMailboxWithLoweredFlag_2 = 0xf02f,

		/// <summary>
		/// File Folder.
		/// </summary>
		FileFolder_2 = 0xf030,

		/// <summary>
		/// Open File Folder.
		/// </summary>
		OpenFileFolder_2 = 0xf031,

		/// <summary>
		/// Page Facing Up.
		/// </summary>
		PageFacingUp_2 = 0xf032,

		/// <summary>
		/// Page.
		/// </summary>
		Page_2 = 0xf033,

		/// <summary>
		/// Pages.
		/// </summary>
		Pages_2 = 0xf034,

		/// <summary>
		/// File Cabinet.
		/// </summary>
		FileCabinet_2 = 0xf035,

		/// <summary>
		/// Hourglass.
		/// </summary>
		Hourglass_2 = 0xf036,

		/// <summary>
		/// Wired Keyboard.
		/// </summary>
		WiredKeyboard_2 = 0xf037,

		/// <summary>
		/// Two Button Mouse.
		/// </summary>
		TwoButtonMouse_2 = 0xf038,

		/// <summary>
		/// Trackball.
		/// </summary>
		Trackball_2 = 0xf039,

		/// <summary>
		/// Old Personal Computer.
		/// </summary>
		OldPersonalComputer_2 = 0xf03a,

		/// <summary>
		/// Hard Disk.
		/// </summary>
		HardDisk_2 = 0xf03b,

		/// <summary>
		/// White Hard Shell Floppy Disk.
		/// </summary>
		WhiteHardShellFloppyDisk_2 = 0xf03c,

		/// <summary>
		/// Soft Shell Floppy Disk.
		/// </summary>
		SoftShellFloppyDisk_2 = 0xf03d,

		/// <summary>
		/// Tape Drive.
		/// </summary>
		TapeDrive_2 = 0xf03e,

		/// <summary>
		/// Writing Hand.
		/// </summary>
		WritingHand_2 = 0xf03f,

		/// <summary>
		/// Left Writing Hand.
		/// </summary>
		LeftWritingHand_2 = 0xf040,

		/// <summary>
		/// Victory Hand.
		/// </summary>
		VictoryHand_2 = 0xf041,

		/// <summary>
		/// Ok Hand Sign.
		/// </summary>
		OkHandSign_2 = 0xf042,

		/// <summary>
		/// Thumbs Up Sign.
		/// </summary>
		ThumbsUpSign_2 = 0xf043,

		/// <summary>
		/// Thumbs Down Sign.
		/// </summary>
		ThumbsDownSign_2 = 0xf044,

		/// <summary>
		/// White Left Pointing Index.
		/// </summary>
		WhiteLeftPointingIndex_2 = 0xf045,

		/// <summary>
		/// White Right Pointing Index.
		/// </summary>
		WhiteRightPointingIndex_2 = 0xf046,

		/// <summary>
		/// White Up Pointing Index.
		/// </summary>
		WhiteUpPointingIndex_2 = 0xf047,

		/// <summary>
		/// White Down Pointing Index.
		/// </summary>
		WhiteDownPointingIndex_2 = 0xf048,

		/// <summary>
		/// Raised Hand With Fingers Splayed.
		/// </summary>
		RaisedHandWithFingersSplayed_2 = 0xf049,

		/// <summary>
		/// White Smiling Face.
		/// </summary>
		WhiteSmilingFace_2 = 0xf04a,

		/// <summary>
		/// Neutral Face.
		/// </summary>
		NeutralFace_2 = 0xf04b,

		/// <summary>
		/// White Frowning Face.
		/// </summary>
		WhiteFrowningFace_2 = 0xf04c,

		/// <summary>
		/// Bomb.
		/// </summary>
		Bomb_2 = 0xf04d,

		/// <summary>
		/// Skull And Crossbones.
		/// </summary>
		SkullAndCrossbones_2 = 0xf04e,

		/// <summary>
		/// Waving White Flag.
		/// </summary>
		WavingWhiteFlag_2 = 0xf04f,

		/// <summary>
		/// White Pennant.
		/// </summary>
		WhitePennant_2 = 0xf050,

		/// <summary>
		/// Airplane.
		/// </summary>
		Airplane_2 = 0xf051,

		/// <summary>
		/// White Sun With Rays.
		/// </summary>
		WhiteSunWithRays_2 = 0xf052,

		/// <summary>
		/// Droplet.
		/// </summary>
		Droplet_2 = 0xf053,

		/// <summary>
		/// Snowflake.
		/// </summary>
		Snowflake_2 = 0xf054,

		/// <summary>
		/// White Latin Cross.
		/// </summary>
		WhiteLatinCross_2 = 0xf055,

		/// <summary>
		/// Shadowed White Latin Cross.
		/// </summary>
		ShadowedWhiteLatinCross_2 = 0xf056,

		/// <summary>
		/// Celtic Cross.
		/// </summary>
		CelticCross_2 = 0xf057,

		/// <summary>
		/// Maltese Cross.
		/// </summary>
		MalteseCross_2 = 0xf058,

		/// <summary>
		/// Star Of David.
		/// </summary>
		StarOfDavid_2 = 0xf059,

		/// <summary>
		/// Star And Crescent.
		/// </summary>
		StarAndCrescent_2 = 0xf05a,

		/// <summary>
		/// Yin Yang.
		/// </summary>
		YinYang_2 = 0xf05b,

		/// <summary>
		/// Devanagari Om.
		/// </summary>
		DevanagariOm_2 = 0xf05c,

		/// <summary>
		/// Wheel Of Dharma.
		/// </summary>
		WheelOfDharma_2 = 0xf05d,

		/// <summary>
		/// Aries.
		/// </summary>
		Aries_2 = 0xf05e,

		/// <summary>
		/// Taurus.
		/// </summary>
		Taurus_2 = 0xf05f,

		/// <summary>
		/// Gemini.
		/// </summary>
		Gemini_2 = 0xf060,

		/// <summary>
		/// Cancer.
		/// </summary>
		Cancer_2 = 0xf061,

		/// <summary>
		/// Leo.
		/// </summary>
		Leo_2 = 0xf062,

		/// <summary>
		/// Virgo.
		/// </summary>
		Virgo_2 = 0xf063,

		/// <summary>
		/// Libra.
		/// </summary>
		Libra_2 = 0xf064,

		/// <summary>
		/// Scorpius.
		/// </summary>
		Scorpius_2 = 0xf065,

		/// <summary>
		/// Sagittarius.
		/// </summary>
		Sagittarius_2 = 0xf066,

		/// <summary>
		/// Capricorn.
		/// </summary>
		Capricorn_2 = 0xf067,

		/// <summary>
		/// Aquarius.
		/// </summary>
		Aquarius_2 = 0xf068,

		/// <summary>
		/// Pisces.
		/// </summary>
		Pisces_2 = 0xf069,

		/// <summary>
		/// Script Ligature Et Ornament.
		/// </summary>
		ScriptLigatureEtOrnament_2 = 0xf06a,

		/// <summary>
		/// Swash Ampersand Ornament.
		/// </summary>
		SwashAmpersandOrnament_2 = 0xf06b,

		/// <summary>
		/// Black Circle.
		/// </summary>
		BlackCircle_2 = 0xf06c,

		/// <summary>
		/// Lower Right Shadowed White Circle.
		/// </summary>
		LowerRightShadowedWhiteCircle_2 = 0xf06d,

		/// <summary>
		/// Black Square.
		/// </summary>
		BlackSquare_2 = 0xf06e,

		/// <summary>
		/// White Square.
		/// </summary>
		WhiteSquare_2 = 0xf06f,

		/// <summary>
		/// Bold White Square.
		/// </summary>
		BoldWhiteSquare_2 = 0xf070,

		/// <summary>
		/// Lower Right Shadowed White Square.
		/// </summary>
		LowerRightShadowedWhiteSquare_2 = 0xf071,

		/// <summary>
		/// Upper Right Shadowed White Square.
		/// </summary>
		UpperRightShadowedWhiteSquare_2 = 0xf072,

		/// <summary>
		/// Black Medium Lozenge.
		/// </summary>
		BlackMediumLozenge_2 = 0xf073,

		/// <summary>
		/// Black Lozenge.
		/// </summary>
		BlackLozenge_2 = 0xf074,

		/// <summary>
		/// Black Diamond.
		/// </summary>
		BlackDiamond_2 = 0xf075,

		/// <summary>
		/// Black Diamond Minus White X.
		/// </summary>
		BlackDiamondMinusWhiteX_2 = 0xf076,

		/// <summary>
		/// Black Medium Diamond.
		/// </summary>
		BlackMediumDiamond_2 = 0xf077,

		/// <summary>
		/// X In A Rectangle Box.
		/// </summary>
		XInARectangleBox_2 = 0xf078,

		/// <summary>
		/// Up Arrowhead In A Rectangle Box.
		/// </summary>
		UpArrowheadInARectangleBox_2 = 0xf079,

		/// <summary>
		/// Place Of Interest Sign.
		/// </summary>
		PlaceOfInterestSign_2 = 0xf07a,

		/// <summary>
		/// Rosette.
		/// </summary>
		Rosette_2 = 0xf07b,

		/// <summary>
		/// Black Rosette.
		/// </summary>
		BlackRosette_2 = 0xf07c,

		/// <summary>
		/// Sans-Serif Heavy Double Turned Comma Quotation Mark Ornament.
		/// </summary>
		SansSerifHeavyDoubleTurnedCommaQuotationMarkOrnament_2 = 0xf07d,

		/// <summary>
		/// Sans-Serif Heavy Double Comma Quotation Mark Ornament.
		/// </summary>
		SansSerifHeavyDoubleCommaQuotationMarkOrnament_2 = 0xf07e,

		/// <summary>
		/// Circled Digit Zero.
		/// </summary>
		CircledDigitZero_2 = 0xf080,

		/// <summary>
		/// Circled Digit One.
		/// </summary>
		CircledDigitOne_2 = 0xf081,

		/// <summary>
		/// Circled Digit Two.
		/// </summary>
		CircledDigitTwo_2 = 0xf082,

		/// <summary>
		/// Circled Digit Three.
		/// </summary>
		CircledDigitThree_2 = 0xf083,

		/// <summary>
		/// Circled Digit Four.
		/// </summary>
		CircledDigitFour_2 = 0xf084,

		/// <summary>
		/// Circled Digit Five.
		/// </summary>
		CircledDigitFive_2 = 0xf085,

		/// <summary>
		/// Circled Digit Six.
		/// </summary>
		CircledDigitSix_2 = 0xf086,

		/// <summary>
		/// Circled Digit Seven.
		/// </summary>
		CircledDigitSeven_2 = 0xf087,

		/// <summary>
		/// Circled Digit Eight.
		/// </summary>
		CircledDigitEight_2 = 0xf088,

		/// <summary>
		/// Circled Digit Nine.
		/// </summary>
		CircledDigitNine_2 = 0xf089,

		/// <summary>
		/// Circled Number Ten.
		/// </summary>
		CircledNumberTen_2 = 0xf08a,

		/// <summary>
		/// Negative Circled Digit Zero.
		/// </summary>
		NegativeCircledDigitZero_2 = 0xf08b,

		/// <summary>
		/// Dingbat Negative Circled Digit One.
		/// </summary>
		DingbatNegativeCircledDigitOne_2 = 0xf08c,

		/// <summary>
		/// Dingbat Negative Circled Digit Two.
		/// </summary>
		DingbatNegativeCircledDigitTwo_2 = 0xf08d,

		/// <summary>
		/// Dingbat Negative Circled Digit Three.
		/// </summary>
		DingbatNegativeCircledDigitThree_2 = 0xf08e,

		/// <summary>
		/// Dingbat Negative Circled Digit Four.
		/// </summary>
		DingbatNegativeCircledDigitFour_2 = 0xf08f,

		/// <summary>
		/// Dingbat Negative Circled Digit Five.
		/// </summary>
		DingbatNegativeCircledDigitFive_2 = 0xf090,

		/// <summary>
		/// Dingbat Negative Circled Digit Six.
		/// </summary>
		DingbatNegativeCircledDigitSix_2 = 0xf091,

		/// <summary>
		/// Dingbat Negative Circled Digit Seven.
		/// </summary>
		DingbatNegativeCircledDigitSeven_2 = 0xf092,

		/// <summary>
		/// Dingbat Negative Circled Digit Eight.
		/// </summary>
		DingbatNegativeCircledDigitEight_2 = 0xf093,

		/// <summary>
		/// Dingbat Negative Circled Digit Nine.
		/// </summary>
		DingbatNegativeCircledDigitNine_2 = 0xf094,

		/// <summary>
		/// Dingbat Negative Circled Number Ten.
		/// </summary>
		DingbatNegativeCircledNumberTen_2 = 0xf095,

		/// <summary>
		/// North East Pointing Bud.
		/// </summary>
		NorthEastPointingBud_2 = 0xf096,

		/// <summary>
		/// North West Pointing Bud.
		/// </summary>
		NorthWestPointingBud_2 = 0xf097,

		/// <summary>
		/// South West Pointing Bud.
		/// </summary>
		SouthWestPointingBud_2 = 0xf098,

		/// <summary>
		/// South East Pointing Bud.
		/// </summary>
		SouthEastPointingBud_2 = 0xf099,

		/// <summary>
		/// Heavy North East Pointing Vine Leaf.
		/// </summary>
		HeavyNorthEastPointingVineLeaf_2 = 0xf09a,

		/// <summary>
		/// Heavy North West Pointing Vine Leaf.
		/// </summary>
		HeavyNorthWestPointingVineLeaf_2 = 0xf09b,

		/// <summary>
		/// Heavy South West Pointing Vine Leaf.
		/// </summary>
		HeavySouthWestPointingVineLeaf_2 = 0xf09c,

		/// <summary>
		/// Heavy South East Pointing Vine Leaf.
		/// </summary>
		HeavySouthEastPointingVineLeaf_2 = 0xf09d,

		/// <summary>
		/// Middle Dot.
		/// </summary>
		MiddleDot_2 = 0xf09e,

		/// <summary>
		/// Bullet.
		/// </summary>
		Bullet_2 = 0xf09f,

		/// <summary>
		/// Black Small Square.
		/// </summary>
		BlackSmallSquare_3 = 0xf0a0,

		/// <summary>
		/// Medium White Circle.
		/// </summary>
		MediumWhiteCircle_2 = 0xf0a1,

		/// <summary>
		/// Bold White Circle.
		/// </summary>
		BoldWhiteCircle_2 = 0xf0a2,

		/// <summary>
		/// Very Heavy White Circle.
		/// </summary>
		VeryHeavyWhiteCircle_2 = 0xf0a3,

		/// <summary>
		/// Fisheye.
		/// </summary>
		Fisheye_2 = 0xf0a4,

		/// <summary>
		/// Bullseye.
		/// </summary>
		Bullseye_2 = 0xf0a5,

		/// <summary>
		/// Upper Right Shadowed White Circle.
		/// </summary>
		UpperRightShadowedWhiteCircle_2 = 0xf0a6,

		/// <summary>
		/// Black Small Square.
		/// </summary>
		BlackSmallSquare_4 = 0xf0a7,

		/// <summary>
		/// White Medium Square.
		/// </summary>
		WhiteMediumSquare_2 = 0xf0a8,

		/// <summary>
		/// Three Pointed Black Star.
		/// </summary>
		ThreePointedBlackStar_2 = 0xf0a9,

		/// <summary>
		/// Black Four Pointed Star.
		/// </summary>
		BlackFourPointedStar_2 = 0xf0aa,

		/// <summary>
		/// Black Star.
		/// </summary>
		BlackStar_2 = 0xf0ab,

		/// <summary>
		/// Six Pointed Black Star.
		/// </summary>
		SixPointedBlackStar_2 = 0xf0ac,

		/// <summary>
		/// Eight Pointed Black Star.
		/// </summary>
		EightPointedBlackStar_2 = 0xf0ad,

		/// <summary>
		/// Twelve Pointed Black Star.
		/// </summary>
		TwelvePointedBlackStar_2 = 0xf0ae,

		/// <summary>
		/// Eight Pointed Pinwheel Star.
		/// </summary>
		EightPointedPinwheelStar_2 = 0xf0af,

		/// <summary>
		/// Square Position Indicator.
		/// </summary>
		SquarePositionIndicator_2 = 0xf0b0,

		/// <summary>
		/// Position Indicator.
		/// </summary>
		PositionIndicator_2 = 0xf0b1,

		/// <summary>
		/// White Concave-Sided Diamond.
		/// </summary>
		WhiteConcaveSidedDiamond_2 = 0xf0b2,

		/// <summary>
		/// Square Lozenge.
		/// </summary>
		SquareLozenge_2 = 0xf0b3,

		/// <summary>
		/// Uncertainty Sign.
		/// </summary>
		UncertaintySign_2 = 0xf0b4,

		/// <summary>
		/// Circled White Star.
		/// </summary>
		CircledWhiteStar_2 = 0xf0b5,

		/// <summary>
		/// Shadowed White Star.
		/// </summary>
		ShadowedWhiteStar_2 = 0xf0b6,

		/// <summary>
		/// Clock Face One Oclock.
		/// </summary>
		ClockFaceOneOclock_2 = 0xf0b7,

		/// <summary>
		/// Clock Face Two Oclock.
		/// </summary>
		ClockFaceTwoOclock_2 = 0xf0b8,

		/// <summary>
		/// Clock Face Three Oclock.
		/// </summary>
		ClockFaceThreeOclock_2 = 0xf0b9,

		/// <summary>
		/// Clock Face Four Oclock.
		/// </summary>
		ClockFaceFourOclock_2 = 0xf0ba,

		/// <summary>
		/// Clock Face Five Oclock.
		/// </summary>
		ClockFaceFiveOclock_2 = 0xf0bb,

		/// <summary>
		/// Clock Face Six Oclock.
		/// </summary>
		ClockFaceSixOclock_2 = 0xf0bc,

		/// <summary>
		/// Clock Face Seven Oclock.
		/// </summary>
		ClockFaceSevenOclock_2 = 0xf0bd,

		/// <summary>
		/// Clock Face Eight Oclock.
		/// </summary>
		ClockFaceEightOclock_2 = 0xf0be,

		/// <summary>
		/// Clock Face Nine Oclock.
		/// </summary>
		ClockFaceNineOclock_2 = 0xf0bf,

		/// <summary>
		/// Clock Face Ten Oclock.
		/// </summary>
		ClockFaceTenOclock_2 = 0xf0c0,

		/// <summary>
		/// Clock Face Eleven Oclock.
		/// </summary>
		ClockFaceElevenOclock_2 = 0xf0c1,

		/// <summary>
		/// Clock Face Twelve Oclock.
		/// </summary>
		ClockFaceTwelveOclock_2 = 0xf0c2,

		/// <summary>
		/// Ribbon Arrow Down Left.
		/// </summary>
		RibbonArrowDownLeft_2 = 0xf0c3,

		/// <summary>
		/// Ribbon Arrow Down Right.
		/// </summary>
		RibbonArrowDownRight_2 = 0xf0c4,

		/// <summary>
		/// Ribbon Arrow Up Left.
		/// </summary>
		RibbonArrowUpLeft_2 = 0xf0c5,

		/// <summary>
		/// Ribbon Arrow Up Right.
		/// </summary>
		RibbonArrowUpRight_2 = 0xf0c6,

		/// <summary>
		/// Ribbon Arrow Left Up.
		/// </summary>
		RibbonArrowLeftUp_2 = 0xf0c7,

		/// <summary>
		/// Ribbon Arrow Right Up.
		/// </summary>
		RibbonArrowRightUp_2 = 0xf0c8,

		/// <summary>
		/// Ribbon Arrow Left Down.
		/// </summary>
		RibbonArrowLeftDown_2 = 0xf0c9,

		/// <summary>
		/// Ribbon Arrow Right Down.
		/// </summary>
		RibbonArrowRightDown_2 = 0xf0ca,

		/// <summary>
		/// Solid Quilt Square Ornament.
		/// </summary>
		SolidQuiltSquareOrnament_2 = 0xf0cb,

		/// <summary>
		/// Solid Quilt Square Ornament In Black Square.
		/// </summary>
		SolidQuiltSquareOrnamentInBlackSquare_2 = 0xf0cc,

		/// <summary>
		/// Turned South West Pointing Leaf.
		/// </summary>
		TurnedSouthWestPointingLeaf_2 = 0xf0cd,

		/// <summary>
		/// Turned North West Pointing Leaf.
		/// </summary>
		TurnedNorthWestPointingLeaf_2 = 0xf0ce,

		/// <summary>
		/// Turned South East Pointing Leaf.
		/// </summary>
		TurnedSouthEastPointingLeaf_2 = 0xf0cf,

		/// <summary>
		/// Turned North East Pointing Leaf.
		/// </summary>
		TurnedNorthEastPointingLeaf_2 = 0xf0d0,

		/// <summary>
		/// North West Pointing Leaf.
		/// </summary>
		NorthWestPointingLeaf_2 = 0xf0d1,

		/// <summary>
		/// South West Pointing Leaf.
		/// </summary>
		SouthWestPointingLeaf_2 = 0xf0d2,

		/// <summary>
		/// North East Pointing Leaf.
		/// </summary>
		NorthEastPointingLeaf_2 = 0xf0d3,

		/// <summary>
		/// South East Pointing Leaf.
		/// </summary>
		SouthEastPointingLeaf_2 = 0xf0d4,

		/// <summary>
		/// Erase To The Left.
		/// </summary>
		EraseToTheLeft_2 = 0xf0d5,

		/// <summary>
		/// Erase To The Right.
		/// </summary>
		EraseToTheRight_2 = 0xf0d6,

		/// <summary>
		/// Three-D Top-Lighted Leftwards Equilateral Arrowhead.
		/// </summary>
		ThreeDTopLightedLeftwardsEquilateralArrowhead_2 = 0xf0d7,

		/// <summary>
		/// Three-D Top-Lighted Rightwards Equilateral Arrowhead.
		/// </summary>
		ThreeDTopLightedRightwardsEquilateralArrowhead_2 = 0xf0d8,

		/// <summary>
		/// Three-D Right-Lighted Upwards Equilateral Arrowhead.
		/// </summary>
		ThreeDRightLightedUpwardsEquilateralArrowhead_2 = 0xf0d9,

		/// <summary>
		/// Three-D Left-Lighted Downwards Equilateral Arrowhead.
		/// </summary>
		ThreeDLeftLightedDownwardsEquilateralArrowhead_2 = 0xf0da,

		/// <summary>
		/// Leftwards Black Circled White Arrow.
		/// </summary>
		LeftwardsBlackCircledWhiteArrow_2 = 0xf0db,

		/// <summary>
		/// Rightwards Black Circled White Arrow.
		/// </summary>
		RightwardsBlackCircledWhiteArrow_2 = 0xf0dc,

		/// <summary>
		/// Upwards Black Circled White Arrow.
		/// </summary>
		UpwardsBlackCircledWhiteArrow_2 = 0xf0dd,

		/// <summary>
		/// Downwards Black Circled White Arrow.
		/// </summary>
		DownwardsBlackCircledWhiteArrow_2 = 0xf0de,

		/// <summary>
		/// Wide-Headed Leftwards Barb Arrow.
		/// </summary>
		WideHeadedLeftwardsBarbArrow_2 = 0xf0df,

		/// <summary>
		/// Wide-Headed Rightwards Barb Arrow.
		/// </summary>
		WideHeadedRightwardsBarbArrow_2 = 0xf0e0,

		/// <summary>
		/// Wide-Headed Upwards Barb Arrow.
		/// </summary>
		WideHeadedUpwardsBarbArrow_2 = 0xf0e1,

		/// <summary>
		/// Wide-Headed Downwards Barb Arrow.
		/// </summary>
		WideHeadedDownwardsBarbArrow_2 = 0xf0e2,

		/// <summary>
		/// Wide-Headed North West Barb Arrow.
		/// </summary>
		WideHeadedNorthWestBarbArrow_2 = 0xf0e3,

		/// <summary>
		/// Wide-Headed North East Barb Arrow.
		/// </summary>
		WideHeadedNorthEastBarbArrow_2 = 0xf0e4,

		/// <summary>
		/// Wide-Headed South West Barb Arrow.
		/// </summary>
		WideHeadedSouthWestBarbArrow_2 = 0xf0e5,

		/// <summary>
		/// Wide-Headed South East Barb Arrow.
		/// </summary>
		WideHeadedSouthEastBarbArrow_2 = 0xf0e6,

		/// <summary>
		/// Wide-Headed Leftwards Heavy Barb Arrow.
		/// </summary>
		WideHeadedLeftwardsHeavyBarbArrow_2 = 0xf0e7,

		/// <summary>
		/// Wide-Headed Rightwards Heavy Barb Arrow.
		/// </summary>
		WideHeadedRightwardsHeavyBarbArrow_2 = 0xf0e8,

		/// <summary>
		/// Wide-Headed Upwards Heavy Barb Arrow.
		/// </summary>
		WideHeadedUpwardsHeavyBarbArrow_2 = 0xf0e9,

		/// <summary>
		/// Wide-Headed Downwards Heavy Barb Arrow.
		/// </summary>
		WideHeadedDownwardsHeavyBarbArrow_2 = 0xf0ea,

		/// <summary>
		/// Wide-Headed North West Heavy Barb Arrow.
		/// </summary>
		WideHeadedNorthWestHeavyBarbArrow_2 = 0xf0eb,

		/// <summary>
		/// Wide-Headed North East Heavy Barb Arrow.
		/// </summary>
		WideHeadedNorthEastHeavyBarbArrow_2 = 0xf0ec,

		/// <summary>
		/// Wide-Headed South West Heavy Barb Arrow.
		/// </summary>
		WideHeadedSouthWestHeavyBarbArrow_2 = 0xf0ed,

		/// <summary>
		/// Wide-Headed South East Heavy Barb Arrow.
		/// </summary>
		WideHeadedSouthEastHeavyBarbArrow_2 = 0xf0ee,

		/// <summary>
		/// Leftwards White Arrow.
		/// </summary>
		LeftwardsWhiteArrow_2 = 0xf0ef,

		/// <summary>
		/// Rightwards White Arrow.
		/// </summary>
		RightwardsWhiteArrow_2 = 0xf0f0,

		/// <summary>
		/// Upwards White Arrow.
		/// </summary>
		UpwardsWhiteArrow_2 = 0xf0f1,

		/// <summary>
		/// Downwards White Arrow.
		/// </summary>
		DownwardsWhiteArrow_2 = 0xf0f2,

		/// <summary>
		/// Left Right White Arrow.
		/// </summary>
		LeftRightWhiteArrow_2 = 0xf0f3,

		/// <summary>
		/// Up Down White Arrow.
		/// </summary>
		UpDownWhiteArrow_2 = 0xf0f4,

		/// <summary>
		/// North East White Arrow.
		/// </summary>
		NorthEastWhiteArrow_2 = 0xf0f5,

		/// <summary>
		/// North West White Arrow.
		/// </summary>
		NorthWestWhiteArrow_2 = 0xf0f6,

		/// <summary>
		/// South West White Arrow.
		/// </summary>
		SouthWestWhiteArrow_2 = 0xf0f7,

		/// <summary>
		/// South East White Arrow.
		/// </summary>
		SouthEastWhiteArrow_2 = 0xf0f8,

		/// <summary>
		/// White Arrow Shaft Width One.
		/// </summary>
		WhiteArrowShaftWidthOne_2 = 0xf0f9,

		/// <summary>
		/// White Arrow Shaft Width Two Thirds.
		/// </summary>
		WhiteArrowShaftWidthTwoThirds_2 = 0xf0fa,

		/// <summary>
		/// Ballot Bold Script X.
		/// </summary>
		BallotBoldScriptX_2 = 0xf0fb,

		/// <summary>
		/// Heavy Check Mark.
		/// </summary>
		HeavyCheckMark_2 = 0xf0fc,

		/// <summary>
		/// Ballot Box With Bold Script X.
		/// </summary>
		BallotBoxWithBoldScriptX_2 = 0xf0fd,

		/// <summary>
		/// Ballot Box With Bold Check.
		/// </summary>
		BallotBoxWithBoldCheck_2 = 0xf0fe,

		/// <summary>
		/// Windows Flag.
		/// </summary>
		WindowsFlag_2 = 0xf0ff
	}

	/// <summary>
	/// WingdingsGlyph Enums.
	/// </summary>
	public static partial class WingdingsGlyphResource
	{
		/// <summary>
		/// Device Control Four.
		/// </summary>
		public const string DeviceControlFour = "\u0014";

		/// <summary>
		/// Lower Left Pencil.
		/// </summary>
		public const string LowerLeftPencil = "\u0021";

		/// <summary>
		/// Black Scissors.
		/// </summary>
		public const string BlackScissors = "\u0022";

		/// <summary>
		/// Upper Blade Scissors.
		/// </summary>
		public const string UpperBladeScissors = "\u0023";

		/// <summary>
		/// Eyeglasses.
		/// </summary>
		public const string Eyeglasses = "\u0024";

		/// <summary>
		/// Ringing Bell.
		/// </summary>
		public const string RingingBell = "\u0025";

		/// <summary>
		/// Book.
		/// </summary>
		public const string Book = "\u0026";

		/// <summary>
		/// Candle.
		/// </summary>
		public const string Candle = "\u0027";

		/// <summary>
		/// Black Touchtone Telephone.
		/// </summary>
		public const string BlackTouchtoneTelephone = "\u0028";

		/// <summary>
		/// Telephone Location Sign.
		/// </summary>
		public const string TelephoneLocationSign = "\u0029";

		/// <summary>
		/// Back Of Envelope.
		/// </summary>
		public const string BackOfEnvelope = "\u002a";

		/// <summary>
		/// Stamped Envelope.
		/// </summary>
		public const string StampedEnvelope = "\u002b";

		/// <summary>
		/// Closed Mailbox With Lowered Flag.
		/// </summary>
		public const string ClosedMailboxWithLoweredFlag = "\u002c";

		/// <summary>
		/// Closed Mailbox With Raised Flag.
		/// </summary>
		public const string ClosedMailboxWithRaisedFlag = "\u002d";

		/// <summary>
		/// Open Mailbox With Raised Flag.
		/// </summary>
		public const string OpenMailboxWithRaisedFlag = "\u002e";

		/// <summary>
		/// Open Mailbox With Lowered Flag.
		/// </summary>
		public const string OpenMailboxWithLoweredFlag = "\u002f";

		/// <summary>
		/// File Folder.
		/// </summary>
		public const string FileFolder = "\u0030";

		/// <summary>
		/// Open File Folder.
		/// </summary>
		public const string OpenFileFolder = "\u0031";

		/// <summary>
		/// Page Facing Up.
		/// </summary>
		public const string PageFacingUp = "\u0032";

		/// <summary>
		/// Page.
		/// </summary>
		public const string Page = "\u0033";

		/// <summary>
		/// Pages.
		/// </summary>
		public const string Pages = "\u0034";

		/// <summary>
		/// File Cabinet.
		/// </summary>
		public const string FileCabinet = "\u0035";

		/// <summary>
		/// Hourglass.
		/// </summary>
		public const string Hourglass = "\u0036";

		/// <summary>
		/// Wired Keyboard.
		/// </summary>
		public const string WiredKeyboard = "\u0037";

		/// <summary>
		/// Two Button Mouse.
		/// </summary>
		public const string TwoButtonMouse = "\u0038";

		/// <summary>
		/// Trackball.
		/// </summary>
		public const string Trackball = "\u0039";

		/// <summary>
		/// Old Personal Computer.
		/// </summary>
		public const string OldPersonalComputer = "\u003a";

		/// <summary>
		/// Hard Disk.
		/// </summary>
		public const string HardDisk = "\u003b";

		/// <summary>
		/// White Hard Shell Floppy Disk.
		/// </summary>
		public const string WhiteHardShellFloppyDisk = "\u003c";

		/// <summary>
		/// Soft Shell Floppy Disk.
		/// </summary>
		public const string SoftShellFloppyDisk = "\u003d";

		/// <summary>
		/// Tape Drive.
		/// </summary>
		public const string TapeDrive = "\u003e";

		/// <summary>
		/// Writing Hand.
		/// </summary>
		public const string WritingHand = "\u003f";

		/// <summary>
		/// Left Writing Hand.
		/// </summary>
		public const string LeftWritingHand = "\u0040";

		/// <summary>
		/// Victory Hand.
		/// </summary>
		public const string VictoryHand = "\u0041";

		/// <summary>
		/// Ok Hand Sign.
		/// </summary>
		public const string OkHandSign = "\u0042";

		/// <summary>
		/// Thumbs Up Sign.
		/// </summary>
		public const string ThumbsUpSign = "\u0043";

		/// <summary>
		/// Thumbs Down Sign.
		/// </summary>
		public const string ThumbsDownSign = "\u0044";

		/// <summary>
		/// White Left Pointing Index.
		/// </summary>
		public const string WhiteLeftPointingIndex = "\u0045";

		/// <summary>
		/// White Right Pointing Index.
		/// </summary>
		public const string WhiteRightPointingIndex = "\u0046";

		/// <summary>
		/// White Up Pointing Index.
		/// </summary>
		public const string WhiteUpPointingIndex = "\u0047";

		/// <summary>
		/// White Down Pointing Index.
		/// </summary>
		public const string WhiteDownPointingIndex = "\u0048";

		/// <summary>
		/// Raised Hand With Fingers Splayed.
		/// </summary>
		public const string RaisedHandWithFingersSplayed = "\u0049";

		/// <summary>
		/// White Smiling Face.
		/// </summary>
		public const string WhiteSmilingFace = "\u004a";

		/// <summary>
		/// Neutral Face.
		/// </summary>
		public const string NeutralFace = "\u004b";

		/// <summary>
		/// White Frowning Face.
		/// </summary>
		public const string WhiteFrowningFace = "\u004c";

		/// <summary>
		/// Bomb.
		/// </summary>
		public const string Bomb = "\u004d";

		/// <summary>
		/// Skull And Crossbones.
		/// </summary>
		public const string SkullAndCrossbones = "\u004e";

		/// <summary>
		/// Waving White Flag.
		/// </summary>
		public const string WavingWhiteFlag = "\u004f";

		/// <summary>
		/// White Pennant.
		/// </summary>
		public const string WhitePennant = "\u0050";

		/// <summary>
		/// Airplane.
		/// </summary>
		public const string Airplane = "\u0051";

		/// <summary>
		/// White Sun With Rays.
		/// </summary>
		public const string WhiteSunWithRays = "\u0052";

		/// <summary>
		/// Droplet.
		/// </summary>
		public const string Droplet = "\u0053";

		/// <summary>
		/// Snowflake.
		/// </summary>
		public const string Snowflake = "\u0054";

		/// <summary>
		/// White Latin Cross.
		/// </summary>
		public const string WhiteLatinCross = "\u0055";

		/// <summary>
		/// Shadowed White Latin Cross.
		/// </summary>
		public const string ShadowedWhiteLatinCross = "\u0056";

		/// <summary>
		/// Celtic Cross.
		/// </summary>
		public const string CelticCross = "\u0057";

		/// <summary>
		/// Maltese Cross.
		/// </summary>
		public const string MalteseCross = "\u0058";

		/// <summary>
		/// Star Of David.
		/// </summary>
		public const string StarOfDavid = "\u0059";

		/// <summary>
		/// Star And Crescent.
		/// </summary>
		public const string StarAndCrescent = "\u005a";

		/// <summary>
		/// Yin Yang.
		/// </summary>
		public const string YinYang = "\u005b";

		/// <summary>
		/// Devanagari Om.
		/// </summary>
		public const string DevanagariOm = "\u005c";

		/// <summary>
		/// Wheel Of Dharma.
		/// </summary>
		public const string WheelOfDharma = "\u005d";

		/// <summary>
		/// Aries.
		/// </summary>
		public const string Aries = "\u005e";

		/// <summary>
		/// Taurus.
		/// </summary>
		public const string Taurus = "\u005f";

		/// <summary>
		/// Gemini.
		/// </summary>
		public const string Gemini = "\u0060";

		/// <summary>
		/// Cancer.
		/// </summary>
		public const string Cancer = "\u0061";

		/// <summary>
		/// Leo.
		/// </summary>
		public const string Leo = "\u0062";

		/// <summary>
		/// Virgo.
		/// </summary>
		public const string Virgo = "\u0063";

		/// <summary>
		/// Libra.
		/// </summary>
		public const string Libra = "\u0064";

		/// <summary>
		/// Scorpius.
		/// </summary>
		public const string Scorpius = "\u0065";

		/// <summary>
		/// Sagittarius.
		/// </summary>
		public const string Sagittarius = "\u0066";

		/// <summary>
		/// Capricorn.
		/// </summary>
		public const string Capricorn = "\u0067";

		/// <summary>
		/// Aquarius.
		/// </summary>
		public const string Aquarius = "\u0068";

		/// <summary>
		/// Pisces.
		/// </summary>
		public const string Pisces = "\u0069";

		/// <summary>
		/// Script Ligature Et Ornament.
		/// </summary>
		public const string ScriptLigatureEtOrnament = "\u006a";

		/// <summary>
		/// Swash Ampersand Ornament.
		/// </summary>
		public const string SwashAmpersandOrnament = "\u006b";

		/// <summary>
		/// Black Circle.
		/// </summary>
		public const string BlackCircle = "\u006c";

		/// <summary>
		/// Lower Right Shadowed White Circle.
		/// </summary>
		public const string LowerRightShadowedWhiteCircle = "\u006d";

		/// <summary>
		/// Black Square.
		/// </summary>
		public const string BlackSquare = "\u006e";

		/// <summary>
		/// White Square.
		/// </summary>
		public const string WhiteSquare = "\u006f";

		/// <summary>
		/// Bold White Square.
		/// </summary>
		public const string BoldWhiteSquare = "\u0070";

		/// <summary>
		/// Lower Right Shadowed White Square.
		/// </summary>
		public const string LowerRightShadowedWhiteSquare = "\u0071";

		/// <summary>
		/// Upper Right Shadowed White Square.
		/// </summary>
		public const string UpperRightShadowedWhiteSquare = "\u0072";

		/// <summary>
		/// Black Medium Lozenge.
		/// </summary>
		public const string BlackMediumLozenge = "\u0073";

		/// <summary>
		/// Black Lozenge.
		/// </summary>
		public const string BlackLozenge = "\u0074";

		/// <summary>
		/// Black Diamond.
		/// </summary>
		public const string BlackDiamond = "\u0075";

		/// <summary>
		/// Black Diamond Minus White X.
		/// </summary>
		public const string BlackDiamondMinusWhiteX = "\u0076";

		/// <summary>
		/// Black Medium Diamond.
		/// </summary>
		public const string BlackMediumDiamond = "\u0077";

		/// <summary>
		/// X In A Rectangle Box.
		/// </summary>
		public const string XInARectangleBox = "\u0078";

		/// <summary>
		/// Up Arrowhead In A Rectangle Box.
		/// </summary>
		public const string UpArrowheadInARectangleBox = "\u0079";

		/// <summary>
		/// Place Of Interest Sign.
		/// </summary>
		public const string PlaceOfInterestSign = "\u007a";

		/// <summary>
		/// Rosette.
		/// </summary>
		public const string Rosette = "\u007b";

		/// <summary>
		/// Black Rosette.
		/// </summary>
		public const string BlackRosette = "\u007c";

		/// <summary>
		/// Sans-Serif Heavy Double Turned Comma Quotation Mark Ornament.
		/// </summary>
		public const string SansSerifHeavyDoubleTurnedCommaQuotationMarkOrnament = "\u007d";

		/// <summary>
		/// Sans-Serif Heavy Double Comma Quotation Mark Ornament.
		/// </summary>
		public const string SansSerifHeavyDoubleCommaQuotationMarkOrnament = "\u007e";

		/// <summary>
		/// Circled Digit Zero.
		/// </summary>
		public const string CircledDigitZero = "\u0080";

		/// <summary>
		/// Circled Digit One.
		/// </summary>
		public const string CircledDigitOne = "\u0081";

		/// <summary>
		/// Circled Digit Two.
		/// </summary>
		public const string CircledDigitTwo = "\u0082";

		/// <summary>
		/// Circled Digit Three.
		/// </summary>
		public const string CircledDigitThree = "\u0083";

		/// <summary>
		/// Circled Digit Four.
		/// </summary>
		public const string CircledDigitFour = "\u0084";

		/// <summary>
		/// Circled Digit Five.
		/// </summary>
		public const string CircledDigitFive = "\u0085";

		/// <summary>
		/// Circled Digit Six.
		/// </summary>
		public const string CircledDigitSix = "\u0086";

		/// <summary>
		/// Circled Digit Seven.
		/// </summary>
		public const string CircledDigitSeven = "\u0087";

		/// <summary>
		/// Circled Digit Eight.
		/// </summary>
		public const string CircledDigitEight = "\u0088";

		/// <summary>
		/// Circled Digit Nine.
		/// </summary>
		public const string CircledDigitNine = "\u0089";

		/// <summary>
		/// Circled Number Ten.
		/// </summary>
		public const string CircledNumberTen = "\u008a";

		/// <summary>
		/// Negative Circled Digit Zero.
		/// </summary>
		public const string NegativeCircledDigitZero = "\u008b";

		/// <summary>
		/// Dingbat Negative Circled Digit One.
		/// </summary>
		public const string DingbatNegativeCircledDigitOne = "\u008c";

		/// <summary>
		/// Dingbat Negative Circled Digit Two.
		/// </summary>
		public const string DingbatNegativeCircledDigitTwo = "\u008d";

		/// <summary>
		/// Dingbat Negative Circled Digit Three.
		/// </summary>
		public const string DingbatNegativeCircledDigitThree = "\u008e";

		/// <summary>
		/// Dingbat Negative Circled Digit Four.
		/// </summary>
		public const string DingbatNegativeCircledDigitFour = "\u008f";

		/// <summary>
		/// Dingbat Negative Circled Digit Five.
		/// </summary>
		public const string DingbatNegativeCircledDigitFive = "\u0090";

		/// <summary>
		/// Dingbat Negative Circled Digit Six.
		/// </summary>
		public const string DingbatNegativeCircledDigitSix = "\u0091";

		/// <summary>
		/// Dingbat Negative Circled Digit Seven.
		/// </summary>
		public const string DingbatNegativeCircledDigitSeven = "\u0092";

		/// <summary>
		/// Dingbat Negative Circled Digit Eight.
		/// </summary>
		public const string DingbatNegativeCircledDigitEight = "\u0093";

		/// <summary>
		/// Dingbat Negative Circled Digit Nine.
		/// </summary>
		public const string DingbatNegativeCircledDigitNine = "\u0094";

		/// <summary>
		/// Dingbat Negative Circled Number Ten.
		/// </summary>
		public const string DingbatNegativeCircledNumberTen = "\u0095";

		/// <summary>
		/// North East Pointing Bud.
		/// </summary>
		public const string NorthEastPointingBud = "\u0096";

		/// <summary>
		/// North West Pointing Bud.
		/// </summary>
		public const string NorthWestPointingBud = "\u0097";

		/// <summary>
		/// South West Pointing Bud.
		/// </summary>
		public const string SouthWestPointingBud = "\u0098";

		/// <summary>
		/// South East Pointing Bud.
		/// </summary>
		public const string SouthEastPointingBud = "\u0099";

		/// <summary>
		/// Heavy North East Pointing Vine Leaf.
		/// </summary>
		public const string HeavyNorthEastPointingVineLeaf = "\u009a";

		/// <summary>
		/// Heavy North West Pointing Vine Leaf.
		/// </summary>
		public const string HeavyNorthWestPointingVineLeaf = "\u009b";

		/// <summary>
		/// Heavy South West Pointing Vine Leaf.
		/// </summary>
		public const string HeavySouthWestPointingVineLeaf = "\u009c";

		/// <summary>
		/// Heavy South East Pointing Vine Leaf.
		/// </summary>
		public const string HeavySouthEastPointingVineLeaf = "\u009d";

		/// <summary>
		/// Middle Dot.
		/// </summary>
		public const string MiddleDot = "\u009e";

		/// <summary>
		/// Bullet.
		/// </summary>
		public const string Bullet = "\u009f";

		/// <summary>
		/// Black Small Square.
		/// </summary>
		public const string BlackSmallSquare = "\u00a0";

		/// <summary>
		/// Medium White Circle.
		/// </summary>
		public const string MediumWhiteCircle = "\u00a1";

		/// <summary>
		/// Bold White Circle.
		/// </summary>
		public const string BoldWhiteCircle = "\u00a2";

		/// <summary>
		/// Very Heavy White Circle.
		/// </summary>
		public const string VeryHeavyWhiteCircle = "\u00a3";

		/// <summary>
		/// Fisheye.
		/// </summary>
		public const string Fisheye = "\u00a4";

		/// <summary>
		/// Bullseye.
		/// </summary>
		public const string Bullseye = "\u00a5";

		/// <summary>
		/// Upper Right Shadowed White Circle.
		/// </summary>
		public const string UpperRightShadowedWhiteCircle = "\u00a6";

		/// <summary>
		/// Black Small Square.
		/// </summary>
		public const string BlackSmallSquare_2 = "\u00a7";

		/// <summary>
		/// White Medium Square.
		/// </summary>
		public const string WhiteMediumSquare = "\u00a8";

		/// <summary>
		/// Three Pointed Black Star.
		/// </summary>
		public const string ThreePointedBlackStar = "\u00a9";

		/// <summary>
		/// Black Four Pointed Star.
		/// </summary>
		public const string BlackFourPointedStar = "\u00aa";

		/// <summary>
		/// Black Star.
		/// </summary>
		public const string BlackStar = "\u00ab";

		/// <summary>
		/// Six Pointed Black Star.
		/// </summary>
		public const string SixPointedBlackStar = "\u00ac";

		/// <summary>
		/// Eight Pointed Black Star.
		/// </summary>
		public const string EightPointedBlackStar = "\u00ad";

		/// <summary>
		/// Twelve Pointed Black Star.
		/// </summary>
		public const string TwelvePointedBlackStar = "\u00ae";

		/// <summary>
		/// Eight Pointed Pinwheel Star.
		/// </summary>
		public const string EightPointedPinwheelStar = "\u00af";

		/// <summary>
		/// Square Position Indicator.
		/// </summary>
		public const string SquarePositionIndicator = "\u00b0";

		/// <summary>
		/// Position Indicator.
		/// </summary>
		public const string PositionIndicator = "\u00b1";

		/// <summary>
		/// White Concave-Sided Diamond.
		/// </summary>
		public const string WhiteConcaveSidedDiamond = "\u00b2";

		/// <summary>
		/// Square Lozenge.
		/// </summary>
		public const string SquareLozenge = "\u00b3";

		/// <summary>
		/// Uncertainty Sign.
		/// </summary>
		public const string UncertaintySign = "\u00b4";

		/// <summary>
		/// Circled White Star.
		/// </summary>
		public const string CircledWhiteStar = "\u00b5";

		/// <summary>
		/// Shadowed White Star.
		/// </summary>
		public const string ShadowedWhiteStar = "\u00b6";

		/// <summary>
		/// Clock Face One Oclock.
		/// </summary>
		public const string ClockFaceOneOclock = "\u00b7";

		/// <summary>
		/// Clock Face Two Oclock.
		/// </summary>
		public const string ClockFaceTwoOclock = "\u00b8";

		/// <summary>
		/// Clock Face Three Oclock.
		/// </summary>
		public const string ClockFaceThreeOclock = "\u00b9";

		/// <summary>
		/// Clock Face Four Oclock.
		/// </summary>
		public const string ClockFaceFourOclock = "\u00ba";

		/// <summary>
		/// Clock Face Five Oclock.
		/// </summary>
		public const string ClockFaceFiveOclock = "\u00bb";

		/// <summary>
		/// Clock Face Six Oclock.
		/// </summary>
		public const string ClockFaceSixOclock = "\u00bc";

		/// <summary>
		/// Clock Face Seven Oclock.
		/// </summary>
		public const string ClockFaceSevenOclock = "\u00bd";

		/// <summary>
		/// Clock Face Eight Oclock.
		/// </summary>
		public const string ClockFaceEightOclock = "\u00be";

		/// <summary>
		/// Clock Face Nine Oclock.
		/// </summary>
		public const string ClockFaceNineOclock = "\u00bf";

		/// <summary>
		/// Clock Face Ten Oclock.
		/// </summary>
		public const string ClockFaceTenOclock = "\u00c0";

		/// <summary>
		/// Clock Face Eleven Oclock.
		/// </summary>
		public const string ClockFaceElevenOclock = "\u00c1";

		/// <summary>
		/// Clock Face Twelve Oclock.
		/// </summary>
		public const string ClockFaceTwelveOclock = "\u00c2";

		/// <summary>
		/// Ribbon Arrow Down Left.
		/// </summary>
		public const string RibbonArrowDownLeft = "\u00c3";

		/// <summary>
		/// Ribbon Arrow Down Right.
		/// </summary>
		public const string RibbonArrowDownRight = "\u00c4";

		/// <summary>
		/// Ribbon Arrow Up Left.
		/// </summary>
		public const string RibbonArrowUpLeft = "\u00c5";

		/// <summary>
		/// Ribbon Arrow Up Right.
		/// </summary>
		public const string RibbonArrowUpRight = "\u00c6";

		/// <summary>
		/// Ribbon Arrow Left Up.
		/// </summary>
		public const string RibbonArrowLeftUp = "\u00c7";

		/// <summary>
		/// Ribbon Arrow Right Up.
		/// </summary>
		public const string RibbonArrowRightUp = "\u00c8";

		/// <summary>
		/// Ribbon Arrow Left Down.
		/// </summary>
		public const string RibbonArrowLeftDown = "\u00c9";

		/// <summary>
		/// Ribbon Arrow Right Down.
		/// </summary>
		public const string RibbonArrowRightDown = "\u00ca";

		/// <summary>
		/// Solid Quilt Square Ornament.
		/// </summary>
		public const string SolidQuiltSquareOrnament = "\u00cb";

		/// <summary>
		/// Solid Quilt Square Ornament In Black Square.
		/// </summary>
		public const string SolidQuiltSquareOrnamentInBlackSquare = "\u00cc";

		/// <summary>
		/// Turned South West Pointing Leaf.
		/// </summary>
		public const string TurnedSouthWestPointingLeaf = "\u00cd";

		/// <summary>
		/// Turned North West Pointing Leaf.
		/// </summary>
		public const string TurnedNorthWestPointingLeaf = "\u00ce";

		/// <summary>
		/// Turned South East Pointing Leaf.
		/// </summary>
		public const string TurnedSouthEastPointingLeaf = "\u00cf";

		/// <summary>
		/// Turned North East Pointing Leaf.
		/// </summary>
		public const string TurnedNorthEastPointingLeaf = "\u00d0";

		/// <summary>
		/// North West Pointing Leaf.
		/// </summary>
		public const string NorthWestPointingLeaf = "\u00d1";

		/// <summary>
		/// South West Pointing Leaf.
		/// </summary>
		public const string SouthWestPointingLeaf = "\u00d2";

		/// <summary>
		/// North East Pointing Leaf.
		/// </summary>
		public const string NorthEastPointingLeaf = "\u00d3";

		/// <summary>
		/// South East Pointing Leaf.
		/// </summary>
		public const string SouthEastPointingLeaf = "\u00d4";

		/// <summary>
		/// Erase To The Left.
		/// </summary>
		public const string EraseToTheLeft = "\u00d5";

		/// <summary>
		/// Erase To The Right.
		/// </summary>
		public const string EraseToTheRight = "\u00d6";

		/// <summary>
		/// Three-D Top-Lighted Leftwards Equilateral Arrowhead.
		/// </summary>
		public const string ThreeDTopLightedLeftwardsEquilateralArrowhead = "\u00d7";

		/// <summary>
		/// Three-D Top-Lighted Rightwards Equilateral Arrowhead.
		/// </summary>
		public const string ThreeDTopLightedRightwardsEquilateralArrowhead = "\u00d8";

		/// <summary>
		/// Three-D Right-Lighted Upwards Equilateral Arrowhead.
		/// </summary>
		public const string ThreeDRightLightedUpwardsEquilateralArrowhead = "\u00d9";

		/// <summary>
		/// Three-D Left-Lighted Downwards Equilateral Arrowhead.
		/// </summary>
		public const string ThreeDLeftLightedDownwardsEquilateralArrowhead = "\u00da";

		/// <summary>
		/// Leftwards Black Circled White Arrow.
		/// </summary>
		public const string LeftwardsBlackCircledWhiteArrow = "\u00db";

		/// <summary>
		/// Rightwards Black Circled White Arrow.
		/// </summary>
		public const string RightwardsBlackCircledWhiteArrow = "\u00dc";

		/// <summary>
		/// Upwards Black Circled White Arrow.
		/// </summary>
		public const string UpwardsBlackCircledWhiteArrow = "\u00dd";

		/// <summary>
		/// Downwards Black Circled White Arrow.
		/// </summary>
		public const string DownwardsBlackCircledWhiteArrow = "\u00de";

		/// <summary>
		/// Wide-Headed Leftwards Barb Arrow.
		/// </summary>
		public const string WideHeadedLeftwardsBarbArrow = "\u00df";

		/// <summary>
		/// Wide-Headed Rightwards Barb Arrow.
		/// </summary>
		public const string WideHeadedRightwardsBarbArrow = "\u00e0";

		/// <summary>
		/// Wide-Headed Upwards Barb Arrow.
		/// </summary>
		public const string WideHeadedUpwardsBarbArrow = "\u00e1";

		/// <summary>
		/// Wide-Headed Downwards Barb Arrow.
		/// </summary>
		public const string WideHeadedDownwardsBarbArrow = "\u00e2";

		/// <summary>
		/// Wide-Headed North West Barb Arrow.
		/// </summary>
		public const string WideHeadedNorthWestBarbArrow = "\u00e3";

		/// <summary>
		/// Wide-Headed North East Barb Arrow.
		/// </summary>
		public const string WideHeadedNorthEastBarbArrow = "\u00e4";

		/// <summary>
		/// Wide-Headed South West Barb Arrow.
		/// </summary>
		public const string WideHeadedSouthWestBarbArrow = "\u00e5";

		/// <summary>
		/// Wide-Headed South East Barb Arrow.
		/// </summary>
		public const string WideHeadedSouthEastBarbArrow = "\u00e6";

		/// <summary>
		/// Wide-Headed Leftwards Heavy Barb Arrow.
		/// </summary>
		public const string WideHeadedLeftwardsHeavyBarbArrow = "\u00e7";

		/// <summary>
		/// Wide-Headed Rightwards Heavy Barb Arrow.
		/// </summary>
		public const string WideHeadedRightwardsHeavyBarbArrow = "\u00e8";

		/// <summary>
		/// Wide-Headed Upwards Heavy Barb Arrow.
		/// </summary>
		public const string WideHeadedUpwardsHeavyBarbArrow = "\u00e9";

		/// <summary>
		/// Wide-Headed Downwards Heavy Barb Arrow.
		/// </summary>
		public const string WideHeadedDownwardsHeavyBarbArrow = "\u00ea";

		/// <summary>
		/// Wide-Headed North West Heavy Barb Arrow.
		/// </summary>
		public const string WideHeadedNorthWestHeavyBarbArrow = "\u00eb";

		/// <summary>
		/// Wide-Headed North East Heavy Barb Arrow.
		/// </summary>
		public const string WideHeadedNorthEastHeavyBarbArrow = "\u00ec";

		/// <summary>
		/// Wide-Headed South West Heavy Barb Arrow.
		/// </summary>
		public const string WideHeadedSouthWestHeavyBarbArrow = "\u00ed";

		/// <summary>
		/// Wide-Headed South East Heavy Barb Arrow.
		/// </summary>
		public const string WideHeadedSouthEastHeavyBarbArrow = "\u00ee";

		/// <summary>
		/// Leftwards White Arrow.
		/// </summary>
		public const string LeftwardsWhiteArrow = "\u00ef";

		/// <summary>
		/// Rightwards White Arrow.
		/// </summary>
		public const string RightwardsWhiteArrow = "\u00f0";

		/// <summary>
		/// Upwards White Arrow.
		/// </summary>
		public const string UpwardsWhiteArrow = "\u00f1";

		/// <summary>
		/// Downwards White Arrow.
		/// </summary>
		public const string DownwardsWhiteArrow = "\u00f2";

		/// <summary>
		/// Left Right White Arrow.
		/// </summary>
		public const string LeftRightWhiteArrow = "\u00f3";

		/// <summary>
		/// Up Down White Arrow.
		/// </summary>
		public const string UpDownWhiteArrow = "\u00f4";

		/// <summary>
		/// North East White Arrow.
		/// </summary>
		public const string NorthEastWhiteArrow = "\u00f5";

		/// <summary>
		/// North West White Arrow.
		/// </summary>
		public const string NorthWestWhiteArrow = "\u00f6";

		/// <summary>
		/// South West White Arrow.
		/// </summary>
		public const string SouthWestWhiteArrow = "\u00f7";

		/// <summary>
		/// South East White Arrow.
		/// </summary>
		public const string SouthEastWhiteArrow = "\u00f8";

		/// <summary>
		/// White Arrow Shaft Width One.
		/// </summary>
		public const string WhiteArrowShaftWidthOne = "\u00f9";

		/// <summary>
		/// White Arrow Shaft Width Two Thirds.
		/// </summary>
		public const string WhiteArrowShaftWidthTwoThirds = "\u00fa";

		/// <summary>
		/// Ballot Bold Script X.
		/// </summary>
		public const string BallotBoldScriptX = "\u00fb";

		/// <summary>
		/// Heavy Check Mark.
		/// </summary>
		public const string HeavyCheckMark = "\u00fc";

		/// <summary>
		/// Ballot Box With Bold Script X.
		/// </summary>
		public const string BallotBoxWithBoldScriptX = "\u00fd";

		/// <summary>
		/// Ballot Box With Bold Check.
		/// </summary>
		public const string BallotBoxWithBoldCheck = "\u00fe";

		/// <summary>
		/// Windows Flag.
		/// </summary>
		public const string WindowsFlag = "\u00ff";

		/// <summary>
		/// Device Control Four.
		/// </summary>
		public const string DeviceControlFour_2 = "\uf014";

		/// <summary>
		/// Lower Left Pencil.
		/// </summary>
		public const string LowerLeftPencil_2 = "\uf021";

		/// <summary>
		/// Black Scissors.
		/// </summary>
		public const string BlackScissors_2 = "\uf022";

		/// <summary>
		/// Upper Blade Scissors.
		/// </summary>
		public const string UpperBladeScissors_2 = "\uf023";

		/// <summary>
		/// Eyeglasses.
		/// </summary>
		public const string Eyeglasses_2 = "\uf024";

		/// <summary>
		/// Ringing Bell.
		/// </summary>
		public const string RingingBell_2 = "\uf025";

		/// <summary>
		/// Book.
		/// </summary>
		public const string Book_2 = "\uf026";

		/// <summary>
		/// Candle.
		/// </summary>
		public const string Candle_2 = "\uf027";

		/// <summary>
		/// Black Touchtone Telephone.
		/// </summary>
		public const string BlackTouchtoneTelephone_2 = "\uf028";

		/// <summary>
		/// Telephone Location Sign.
		/// </summary>
		public const string TelephoneLocationSign_2 = "\uf029";

		/// <summary>
		/// Back Of Envelope.
		/// </summary>
		public const string BackOfEnvelope_2 = "\uf02a";

		/// <summary>
		/// Stamped Envelope.
		/// </summary>
		public const string StampedEnvelope_2 = "\uf02b";

		/// <summary>
		/// Closed Mailbox With Lowered Flag.
		/// </summary>
		public const string ClosedMailboxWithLoweredFlag_2 = "\uf02c";

		/// <summary>
		/// Closed Mailbox With Raised Flag.
		/// </summary>
		public const string ClosedMailboxWithRaisedFlag_2 = "\uf02d";

		/// <summary>
		/// Open Mailbox With Raised Flag.
		/// </summary>
		public const string OpenMailboxWithRaisedFlag_2 = "\uf02e";

		/// <summary>
		/// Open Mailbox With Lowered Flag.
		/// </summary>
		public const string OpenMailboxWithLoweredFlag_2 = "\uf02f";

		/// <summary>
		/// File Folder.
		/// </summary>
		public const string FileFolder_2 = "\uf030";

		/// <summary>
		/// Open File Folder.
		/// </summary>
		public const string OpenFileFolder_2 = "\uf031";

		/// <summary>
		/// Page Facing Up.
		/// </summary>
		public const string PageFacingUp_2 = "\uf032";

		/// <summary>
		/// Page.
		/// </summary>
		public const string Page_2 = "\uf033";

		/// <summary>
		/// Pages.
		/// </summary>
		public const string Pages_2 = "\uf034";

		/// <summary>
		/// File Cabinet.
		/// </summary>
		public const string FileCabinet_2 = "\uf035";

		/// <summary>
		/// Hourglass.
		/// </summary>
		public const string Hourglass_2 = "\uf036";

		/// <summary>
		/// Wired Keyboard.
		/// </summary>
		public const string WiredKeyboard_2 = "\uf037";

		/// <summary>
		/// Two Button Mouse.
		/// </summary>
		public const string TwoButtonMouse_2 = "\uf038";

		/// <summary>
		/// Trackball.
		/// </summary>
		public const string Trackball_2 = "\uf039";

		/// <summary>
		/// Old Personal Computer.
		/// </summary>
		public const string OldPersonalComputer_2 = "\uf03a";

		/// <summary>
		/// Hard Disk.
		/// </summary>
		public const string HardDisk_2 = "\uf03b";

		/// <summary>
		/// White Hard Shell Floppy Disk.
		/// </summary>
		public const string WhiteHardShellFloppyDisk_2 = "\uf03c";

		/// <summary>
		/// Soft Shell Floppy Disk.
		/// </summary>
		public const string SoftShellFloppyDisk_2 = "\uf03d";

		/// <summary>
		/// Tape Drive.
		/// </summary>
		public const string TapeDrive_2 = "\uf03e";

		/// <summary>
		/// Writing Hand.
		/// </summary>
		public const string WritingHand_2 = "\uf03f";

		/// <summary>
		/// Left Writing Hand.
		/// </summary>
		public const string LeftWritingHand_2 = "\uf040";

		/// <summary>
		/// Victory Hand.
		/// </summary>
		public const string VictoryHand_2 = "\uf041";

		/// <summary>
		/// Ok Hand Sign.
		/// </summary>
		public const string OkHandSign_2 = "\uf042";

		/// <summary>
		/// Thumbs Up Sign.
		/// </summary>
		public const string ThumbsUpSign_2 = "\uf043";

		/// <summary>
		/// Thumbs Down Sign.
		/// </summary>
		public const string ThumbsDownSign_2 = "\uf044";

		/// <summary>
		/// White Left Pointing Index.
		/// </summary>
		public const string WhiteLeftPointingIndex_2 = "\uf045";

		/// <summary>
		/// White Right Pointing Index.
		/// </summary>
		public const string WhiteRightPointingIndex_2 = "\uf046";

		/// <summary>
		/// White Up Pointing Index.
		/// </summary>
		public const string WhiteUpPointingIndex_2 = "\uf047";

		/// <summary>
		/// White Down Pointing Index.
		/// </summary>
		public const string WhiteDownPointingIndex_2 = "\uf048";

		/// <summary>
		/// Raised Hand With Fingers Splayed.
		/// </summary>
		public const string RaisedHandWithFingersSplayed_2 = "\uf049";

		/// <summary>
		/// White Smiling Face.
		/// </summary>
		public const string WhiteSmilingFace_2 = "\uf04a";

		/// <summary>
		/// Neutral Face.
		/// </summary>
		public const string NeutralFace_2 = "\uf04b";

		/// <summary>
		/// White Frowning Face.
		/// </summary>
		public const string WhiteFrowningFace_2 = "\uf04c";

		/// <summary>
		/// Bomb.
		/// </summary>
		public const string Bomb_2 = "\uf04d";

		/// <summary>
		/// Skull And Crossbones.
		/// </summary>
		public const string SkullAndCrossbones_2 = "\uf04e";

		/// <summary>
		/// Waving White Flag.
		/// </summary>
		public const string WavingWhiteFlag_2 = "\uf04f";

		/// <summary>
		/// White Pennant.
		/// </summary>
		public const string WhitePennant_2 = "\uf050";

		/// <summary>
		/// Airplane.
		/// </summary>
		public const string Airplane_2 = "\uf051";

		/// <summary>
		/// White Sun With Rays.
		/// </summary>
		public const string WhiteSunWithRays_2 = "\uf052";

		/// <summary>
		/// Droplet.
		/// </summary>
		public const string Droplet_2 = "\uf053";

		/// <summary>
		/// Snowflake.
		/// </summary>
		public const string Snowflake_2 = "\uf054";

		/// <summary>
		/// White Latin Cross.
		/// </summary>
		public const string WhiteLatinCross_2 = "\uf055";

		/// <summary>
		/// Shadowed White Latin Cross.
		/// </summary>
		public const string ShadowedWhiteLatinCross_2 = "\uf056";

		/// <summary>
		/// Celtic Cross.
		/// </summary>
		public const string CelticCross_2 = "\uf057";

		/// <summary>
		/// Maltese Cross.
		/// </summary>
		public const string MalteseCross_2 = "\uf058";

		/// <summary>
		/// Star Of David.
		/// </summary>
		public const string StarOfDavid_2 = "\uf059";

		/// <summary>
		/// Star And Crescent.
		/// </summary>
		public const string StarAndCrescent_2 = "\uf05a";

		/// <summary>
		/// Yin Yang.
		/// </summary>
		public const string YinYang_2 = "\uf05b";

		/// <summary>
		/// Devanagari Om.
		/// </summary>
		public const string DevanagariOm_2 = "\uf05c";

		/// <summary>
		/// Wheel Of Dharma.
		/// </summary>
		public const string WheelOfDharma_2 = "\uf05d";

		/// <summary>
		/// Aries.
		/// </summary>
		public const string Aries_2 = "\uf05e";

		/// <summary>
		/// Taurus.
		/// </summary>
		public const string Taurus_2 = "\uf05f";

		/// <summary>
		/// Gemini.
		/// </summary>
		public const string Gemini_2 = "\uf060";

		/// <summary>
		/// Cancer.
		/// </summary>
		public const string Cancer_2 = "\uf061";

		/// <summary>
		/// Leo.
		/// </summary>
		public const string Leo_2 = "\uf062";

		/// <summary>
		/// Virgo.
		/// </summary>
		public const string Virgo_2 = "\uf063";

		/// <summary>
		/// Libra.
		/// </summary>
		public const string Libra_2 = "\uf064";

		/// <summary>
		/// Scorpius.
		/// </summary>
		public const string Scorpius_2 = "\uf065";

		/// <summary>
		/// Sagittarius.
		/// </summary>
		public const string Sagittarius_2 = "\uf066";

		/// <summary>
		/// Capricorn.
		/// </summary>
		public const string Capricorn_2 = "\uf067";

		/// <summary>
		/// Aquarius.
		/// </summary>
		public const string Aquarius_2 = "\uf068";

		/// <summary>
		/// Pisces.
		/// </summary>
		public const string Pisces_2 = "\uf069";

		/// <summary>
		/// Script Ligature Et Ornament.
		/// </summary>
		public const string ScriptLigatureEtOrnament_2 = "\uf06a";

		/// <summary>
		/// Swash Ampersand Ornament.
		/// </summary>
		public const string SwashAmpersandOrnament_2 = "\uf06b";

		/// <summary>
		/// Black Circle.
		/// </summary>
		public const string BlackCircle_2 = "\uf06c";

		/// <summary>
		/// Lower Right Shadowed White Circle.
		/// </summary>
		public const string LowerRightShadowedWhiteCircle_2 = "\uf06d";

		/// <summary>
		/// Black Square.
		/// </summary>
		public const string BlackSquare_2 = "\uf06e";

		/// <summary>
		/// White Square.
		/// </summary>
		public const string WhiteSquare_2 = "\uf06f";

		/// <summary>
		/// Bold White Square.
		/// </summary>
		public const string BoldWhiteSquare_2 = "\uf070";

		/// <summary>
		/// Lower Right Shadowed White Square.
		/// </summary>
		public const string LowerRightShadowedWhiteSquare_2 = "\uf071";

		/// <summary>
		/// Upper Right Shadowed White Square.
		/// </summary>
		public const string UpperRightShadowedWhiteSquare_2 = "\uf072";

		/// <summary>
		/// Black Medium Lozenge.
		/// </summary>
		public const string BlackMediumLozenge_2 = "\uf073";

		/// <summary>
		/// Black Lozenge.
		/// </summary>
		public const string BlackLozenge_2 = "\uf074";

		/// <summary>
		/// Black Diamond.
		/// </summary>
		public const string BlackDiamond_2 = "\uf075";

		/// <summary>
		/// Black Diamond Minus White X.
		/// </summary>
		public const string BlackDiamondMinusWhiteX_2 = "\uf076";

		/// <summary>
		/// Black Medium Diamond.
		/// </summary>
		public const string BlackMediumDiamond_2 = "\uf077";

		/// <summary>
		/// X In A Rectangle Box.
		/// </summary>
		public const string XInARectangleBox_2 = "\uf078";

		/// <summary>
		/// Up Arrowhead In A Rectangle Box.
		/// </summary>
		public const string UpArrowheadInARectangleBox_2 = "\uf079";

		/// <summary>
		/// Place Of Interest Sign.
		/// </summary>
		public const string PlaceOfInterestSign_2 = "\uf07a";

		/// <summary>
		/// Rosette.
		/// </summary>
		public const string Rosette_2 = "\uf07b";

		/// <summary>
		/// Black Rosette.
		/// </summary>
		public const string BlackRosette_2 = "\uf07c";

		/// <summary>
		/// Sans-Serif Heavy Double Turned Comma Quotation Mark Ornament.
		/// </summary>
		public const string SansSerifHeavyDoubleTurnedCommaQuotationMarkOrnament_2 = "\uf07d";

		/// <summary>
		/// Sans-Serif Heavy Double Comma Quotation Mark Ornament.
		/// </summary>
		public const string SansSerifHeavyDoubleCommaQuotationMarkOrnament_2 = "\uf07e";

		/// <summary>
		/// Circled Digit Zero.
		/// </summary>
		public const string CircledDigitZero_2 = "\uf080";

		/// <summary>
		/// Circled Digit One.
		/// </summary>
		public const string CircledDigitOne_2 = "\uf081";

		/// <summary>
		/// Circled Digit Two.
		/// </summary>
		public const string CircledDigitTwo_2 = "\uf082";

		/// <summary>
		/// Circled Digit Three.
		/// </summary>
		public const string CircledDigitThree_2 = "\uf083";

		/// <summary>
		/// Circled Digit Four.
		/// </summary>
		public const string CircledDigitFour_2 = "\uf084";

		/// <summary>
		/// Circled Digit Five.
		/// </summary>
		public const string CircledDigitFive_2 = "\uf085";

		/// <summary>
		/// Circled Digit Six.
		/// </summary>
		public const string CircledDigitSix_2 = "\uf086";

		/// <summary>
		/// Circled Digit Seven.
		/// </summary>
		public const string CircledDigitSeven_2 = "\uf087";

		/// <summary>
		/// Circled Digit Eight.
		/// </summary>
		public const string CircledDigitEight_2 = "\uf088";

		/// <summary>
		/// Circled Digit Nine.
		/// </summary>
		public const string CircledDigitNine_2 = "\uf089";

		/// <summary>
		/// Circled Number Ten.
		/// </summary>
		public const string CircledNumberTen_2 = "\uf08a";

		/// <summary>
		/// Negative Circled Digit Zero.
		/// </summary>
		public const string NegativeCircledDigitZero_2 = "\uf08b";

		/// <summary>
		/// Dingbat Negative Circled Digit One.
		/// </summary>
		public const string DingbatNegativeCircledDigitOne_2 = "\uf08c";

		/// <summary>
		/// Dingbat Negative Circled Digit Two.
		/// </summary>
		public const string DingbatNegativeCircledDigitTwo_2 = "\uf08d";

		/// <summary>
		/// Dingbat Negative Circled Digit Three.
		/// </summary>
		public const string DingbatNegativeCircledDigitThree_2 = "\uf08e";

		/// <summary>
		/// Dingbat Negative Circled Digit Four.
		/// </summary>
		public const string DingbatNegativeCircledDigitFour_2 = "\uf08f";

		/// <summary>
		/// Dingbat Negative Circled Digit Five.
		/// </summary>
		public const string DingbatNegativeCircledDigitFive_2 = "\uf090";

		/// <summary>
		/// Dingbat Negative Circled Digit Six.
		/// </summary>
		public const string DingbatNegativeCircledDigitSix_2 = "\uf091";

		/// <summary>
		/// Dingbat Negative Circled Digit Seven.
		/// </summary>
		public const string DingbatNegativeCircledDigitSeven_2 = "\uf092";

		/// <summary>
		/// Dingbat Negative Circled Digit Eight.
		/// </summary>
		public const string DingbatNegativeCircledDigitEight_2 = "\uf093";

		/// <summary>
		/// Dingbat Negative Circled Digit Nine.
		/// </summary>
		public const string DingbatNegativeCircledDigitNine_2 = "\uf094";

		/// <summary>
		/// Dingbat Negative Circled Number Ten.
		/// </summary>
		public const string DingbatNegativeCircledNumberTen_2 = "\uf095";

		/// <summary>
		/// North East Pointing Bud.
		/// </summary>
		public const string NorthEastPointingBud_2 = "\uf096";

		/// <summary>
		/// North West Pointing Bud.
		/// </summary>
		public const string NorthWestPointingBud_2 = "\uf097";

		/// <summary>
		/// South West Pointing Bud.
		/// </summary>
		public const string SouthWestPointingBud_2 = "\uf098";

		/// <summary>
		/// South East Pointing Bud.
		/// </summary>
		public const string SouthEastPointingBud_2 = "\uf099";

		/// <summary>
		/// Heavy North East Pointing Vine Leaf.
		/// </summary>
		public const string HeavyNorthEastPointingVineLeaf_2 = "\uf09a";

		/// <summary>
		/// Heavy North West Pointing Vine Leaf.
		/// </summary>
		public const string HeavyNorthWestPointingVineLeaf_2 = "\uf09b";

		/// <summary>
		/// Heavy South West Pointing Vine Leaf.
		/// </summary>
		public const string HeavySouthWestPointingVineLeaf_2 = "\uf09c";

		/// <summary>
		/// Heavy South East Pointing Vine Leaf.
		/// </summary>
		public const string HeavySouthEastPointingVineLeaf_2 = "\uf09d";

		/// <summary>
		/// Middle Dot.
		/// </summary>
		public const string MiddleDot_2 = "\uf09e";

		/// <summary>
		/// Bullet.
		/// </summary>
		public const string Bullet_2 = "\uf09f";

		/// <summary>
		/// Black Small Square.
		/// </summary>
		public const string BlackSmallSquare_3 = "\uf0a0";

		/// <summary>
		/// Medium White Circle.
		/// </summary>
		public const string MediumWhiteCircle_2 = "\uf0a1";

		/// <summary>
		/// Bold White Circle.
		/// </summary>
		public const string BoldWhiteCircle_2 = "\uf0a2";

		/// <summary>
		/// Very Heavy White Circle.
		/// </summary>
		public const string VeryHeavyWhiteCircle_2 = "\uf0a3";

		/// <summary>
		/// Fisheye.
		/// </summary>
		public const string Fisheye_2 = "\uf0a4";

		/// <summary>
		/// Bullseye.
		/// </summary>
		public const string Bullseye_2 = "\uf0a5";

		/// <summary>
		/// Upper Right Shadowed White Circle.
		/// </summary>
		public const string UpperRightShadowedWhiteCircle_2 = "\uf0a6";

		/// <summary>
		/// Black Small Square.
		/// </summary>
		public const string BlackSmallSquare_4 = "\uf0a7";

		/// <summary>
		/// White Medium Square.
		/// </summary>
		public const string WhiteMediumSquare_2 = "\uf0a8";

		/// <summary>
		/// Three Pointed Black Star.
		/// </summary>
		public const string ThreePointedBlackStar_2 = "\uf0a9";

		/// <summary>
		/// Black Four Pointed Star.
		/// </summary>
		public const string BlackFourPointedStar_2 = "\uf0aa";

		/// <summary>
		/// Black Star.
		/// </summary>
		public const string BlackStar_2 = "\uf0ab";

		/// <summary>
		/// Six Pointed Black Star.
		/// </summary>
		public const string SixPointedBlackStar_2 = "\uf0ac";

		/// <summary>
		/// Eight Pointed Black Star.
		/// </summary>
		public const string EightPointedBlackStar_2 = "\uf0ad";

		/// <summary>
		/// Twelve Pointed Black Star.
		/// </summary>
		public const string TwelvePointedBlackStar_2 = "\uf0ae";

		/// <summary>
		/// Eight Pointed Pinwheel Star.
		/// </summary>
		public const string EightPointedPinwheelStar_2 = "\uf0af";

		/// <summary>
		/// Square Position Indicator.
		/// </summary>
		public const string SquarePositionIndicator_2 = "\uf0b0";

		/// <summary>
		/// Position Indicator.
		/// </summary>
		public const string PositionIndicator_2 = "\uf0b1";

		/// <summary>
		/// White Concave-Sided Diamond.
		/// </summary>
		public const string WhiteConcaveSidedDiamond_2 = "\uf0b2";

		/// <summary>
		/// Square Lozenge.
		/// </summary>
		public const string SquareLozenge_2 = "\uf0b3";

		/// <summary>
		/// Uncertainty Sign.
		/// </summary>
		public const string UncertaintySign_2 = "\uf0b4";

		/// <summary>
		/// Circled White Star.
		/// </summary>
		public const string CircledWhiteStar_2 = "\uf0b5";

		/// <summary>
		/// Shadowed White Star.
		/// </summary>
		public const string ShadowedWhiteStar_2 = "\uf0b6";

		/// <summary>
		/// Clock Face One Oclock.
		/// </summary>
		public const string ClockFaceOneOclock_2 = "\uf0b7";

		/// <summary>
		/// Clock Face Two Oclock.
		/// </summary>
		public const string ClockFaceTwoOclock_2 = "\uf0b8";

		/// <summary>
		/// Clock Face Three Oclock.
		/// </summary>
		public const string ClockFaceThreeOclock_2 = "\uf0b9";

		/// <summary>
		/// Clock Face Four Oclock.
		/// </summary>
		public const string ClockFaceFourOclock_2 = "\uf0ba";

		/// <summary>
		/// Clock Face Five Oclock.
		/// </summary>
		public const string ClockFaceFiveOclock_2 = "\uf0bb";

		/// <summary>
		/// Clock Face Six Oclock.
		/// </summary>
		public const string ClockFaceSixOclock_2 = "\uf0bc";

		/// <summary>
		/// Clock Face Seven Oclock.
		/// </summary>
		public const string ClockFaceSevenOclock_2 = "\uf0bd";

		/// <summary>
		/// Clock Face Eight Oclock.
		/// </summary>
		public const string ClockFaceEightOclock_2 = "\uf0be";

		/// <summary>
		/// Clock Face Nine Oclock.
		/// </summary>
		public const string ClockFaceNineOclock_2 = "\uf0bf";

		/// <summary>
		/// Clock Face Ten Oclock.
		/// </summary>
		public const string ClockFaceTenOclock_2 = "\uf0c0";

		/// <summary>
		/// Clock Face Eleven Oclock.
		/// </summary>
		public const string ClockFaceElevenOclock_2 = "\uf0c1";

		/// <summary>
		/// Clock Face Twelve Oclock.
		/// </summary>
		public const string ClockFaceTwelveOclock_2 = "\uf0c2";

		/// <summary>
		/// Ribbon Arrow Down Left.
		/// </summary>
		public const string RibbonArrowDownLeft_2 = "\uf0c3";

		/// <summary>
		/// Ribbon Arrow Down Right.
		/// </summary>
		public const string RibbonArrowDownRight_2 = "\uf0c4";

		/// <summary>
		/// Ribbon Arrow Up Left.
		/// </summary>
		public const string RibbonArrowUpLeft_2 = "\uf0c5";

		/// <summary>
		/// Ribbon Arrow Up Right.
		/// </summary>
		public const string RibbonArrowUpRight_2 = "\uf0c6";

		/// <summary>
		/// Ribbon Arrow Left Up.
		/// </summary>
		public const string RibbonArrowLeftUp_2 = "\uf0c7";

		/// <summary>
		/// Ribbon Arrow Right Up.
		/// </summary>
		public const string RibbonArrowRightUp_2 = "\uf0c8";

		/// <summary>
		/// Ribbon Arrow Left Down.
		/// </summary>
		public const string RibbonArrowLeftDown_2 = "\uf0c9";

		/// <summary>
		/// Ribbon Arrow Right Down.
		/// </summary>
		public const string RibbonArrowRightDown_2 = "\uf0ca";

		/// <summary>
		/// Solid Quilt Square Ornament.
		/// </summary>
		public const string SolidQuiltSquareOrnament_2 = "\uf0cb";

		/// <summary>
		/// Solid Quilt Square Ornament In Black Square.
		/// </summary>
		public const string SolidQuiltSquareOrnamentInBlackSquare_2 = "\uf0cc";

		/// <summary>
		/// Turned South West Pointing Leaf.
		/// </summary>
		public const string TurnedSouthWestPointingLeaf_2 = "\uf0cd";

		/// <summary>
		/// Turned North West Pointing Leaf.
		/// </summary>
		public const string TurnedNorthWestPointingLeaf_2 = "\uf0ce";

		/// <summary>
		/// Turned South East Pointing Leaf.
		/// </summary>
		public const string TurnedSouthEastPointingLeaf_2 = "\uf0cf";

		/// <summary>
		/// Turned North East Pointing Leaf.
		/// </summary>
		public const string TurnedNorthEastPointingLeaf_2 = "\uf0d0";

		/// <summary>
		/// North West Pointing Leaf.
		/// </summary>
		public const string NorthWestPointingLeaf_2 = "\uf0d1";

		/// <summary>
		/// South West Pointing Leaf.
		/// </summary>
		public const string SouthWestPointingLeaf_2 = "\uf0d2";

		/// <summary>
		/// North East Pointing Leaf.
		/// </summary>
		public const string NorthEastPointingLeaf_2 = "\uf0d3";

		/// <summary>
		/// South East Pointing Leaf.
		/// </summary>
		public const string SouthEastPointingLeaf_2 = "\uf0d4";

		/// <summary>
		/// Erase To The Left.
		/// </summary>
		public const string EraseToTheLeft_2 = "\uf0d5";

		/// <summary>
		/// Erase To The Right.
		/// </summary>
		public const string EraseToTheRight_2 = "\uf0d6";

		/// <summary>
		/// Three-D Top-Lighted Leftwards Equilateral Arrowhead.
		/// </summary>
		public const string ThreeDTopLightedLeftwardsEquilateralArrowhead_2 = "\uf0d7";

		/// <summary>
		/// Three-D Top-Lighted Rightwards Equilateral Arrowhead.
		/// </summary>
		public const string ThreeDTopLightedRightwardsEquilateralArrowhead_2 = "\uf0d8";

		/// <summary>
		/// Three-D Right-Lighted Upwards Equilateral Arrowhead.
		/// </summary>
		public const string ThreeDRightLightedUpwardsEquilateralArrowhead_2 = "\uf0d9";

		/// <summary>
		/// Three-D Left-Lighted Downwards Equilateral Arrowhead.
		/// </summary>
		public const string ThreeDLeftLightedDownwardsEquilateralArrowhead_2 = "\uf0da";

		/// <summary>
		/// Leftwards Black Circled White Arrow.
		/// </summary>
		public const string LeftwardsBlackCircledWhiteArrow_2 = "\uf0db";

		/// <summary>
		/// Rightwards Black Circled White Arrow.
		/// </summary>
		public const string RightwardsBlackCircledWhiteArrow_2 = "\uf0dc";

		/// <summary>
		/// Upwards Black Circled White Arrow.
		/// </summary>
		public const string UpwardsBlackCircledWhiteArrow_2 = "\uf0dd";

		/// <summary>
		/// Downwards Black Circled White Arrow.
		/// </summary>
		public const string DownwardsBlackCircledWhiteArrow_2 = "\uf0de";

		/// <summary>
		/// Wide-Headed Leftwards Barb Arrow.
		/// </summary>
		public const string WideHeadedLeftwardsBarbArrow_2 = "\uf0df";

		/// <summary>
		/// Wide-Headed Rightwards Barb Arrow.
		/// </summary>
		public const string WideHeadedRightwardsBarbArrow_2 = "\uf0e0";

		/// <summary>
		/// Wide-Headed Upwards Barb Arrow.
		/// </summary>
		public const string WideHeadedUpwardsBarbArrow_2 = "\uf0e1";

		/// <summary>
		/// Wide-Headed Downwards Barb Arrow.
		/// </summary>
		public const string WideHeadedDownwardsBarbArrow_2 = "\uf0e2";

		/// <summary>
		/// Wide-Headed North West Barb Arrow.
		/// </summary>
		public const string WideHeadedNorthWestBarbArrow_2 = "\uf0e3";

		/// <summary>
		/// Wide-Headed North East Barb Arrow.
		/// </summary>
		public const string WideHeadedNorthEastBarbArrow_2 = "\uf0e4";

		/// <summary>
		/// Wide-Headed South West Barb Arrow.
		/// </summary>
		public const string WideHeadedSouthWestBarbArrow_2 = "\uf0e5";

		/// <summary>
		/// Wide-Headed South East Barb Arrow.
		/// </summary>
		public const string WideHeadedSouthEastBarbArrow_2 = "\uf0e6";

		/// <summary>
		/// Wide-Headed Leftwards Heavy Barb Arrow.
		/// </summary>
		public const string WideHeadedLeftwardsHeavyBarbArrow_2 = "\uf0e7";

		/// <summary>
		/// Wide-Headed Rightwards Heavy Barb Arrow.
		/// </summary>
		public const string WideHeadedRightwardsHeavyBarbArrow_2 = "\uf0e8";

		/// <summary>
		/// Wide-Headed Upwards Heavy Barb Arrow.
		/// </summary>
		public const string WideHeadedUpwardsHeavyBarbArrow_2 = "\uf0e9";

		/// <summary>
		/// Wide-Headed Downwards Heavy Barb Arrow.
		/// </summary>
		public const string WideHeadedDownwardsHeavyBarbArrow_2 = "\uf0ea";

		/// <summary>
		/// Wide-Headed North West Heavy Barb Arrow.
		/// </summary>
		public const string WideHeadedNorthWestHeavyBarbArrow_2 = "\uf0eb";

		/// <summary>
		/// Wide-Headed North East Heavy Barb Arrow.
		/// </summary>
		public const string WideHeadedNorthEastHeavyBarbArrow_2 = "\uf0ec";

		/// <summary>
		/// Wide-Headed South West Heavy Barb Arrow.
		/// </summary>
		public const string WideHeadedSouthWestHeavyBarbArrow_2 = "\uf0ed";

		/// <summary>
		/// Wide-Headed South East Heavy Barb Arrow.
		/// </summary>
		public const string WideHeadedSouthEastHeavyBarbArrow_2 = "\uf0ee";

		/// <summary>
		/// Leftwards White Arrow.
		/// </summary>
		public const string LeftwardsWhiteArrow_2 = "\uf0ef";

		/// <summary>
		/// Rightwards White Arrow.
		/// </summary>
		public const string RightwardsWhiteArrow_2 = "\uf0f0";

		/// <summary>
		/// Upwards White Arrow.
		/// </summary>
		public const string UpwardsWhiteArrow_2 = "\uf0f1";

		/// <summary>
		/// Downwards White Arrow.
		/// </summary>
		public const string DownwardsWhiteArrow_2 = "\uf0f2";

		/// <summary>
		/// Left Right White Arrow.
		/// </summary>
		public const string LeftRightWhiteArrow_2 = "\uf0f3";

		/// <summary>
		/// Up Down White Arrow.
		/// </summary>
		public const string UpDownWhiteArrow_2 = "\uf0f4";

		/// <summary>
		/// North East White Arrow.
		/// </summary>
		public const string NorthEastWhiteArrow_2 = "\uf0f5";

		/// <summary>
		/// North West White Arrow.
		/// </summary>
		public const string NorthWestWhiteArrow_2 = "\uf0f6";

		/// <summary>
		/// South West White Arrow.
		/// </summary>
		public const string SouthWestWhiteArrow_2 = "\uf0f7";

		/// <summary>
		/// South East White Arrow.
		/// </summary>
		public const string SouthEastWhiteArrow_2 = "\uf0f8";

		/// <summary>
		/// White Arrow Shaft Width One.
		/// </summary>
		public const string WhiteArrowShaftWidthOne_2 = "\uf0f9";

		/// <summary>
		/// White Arrow Shaft Width Two Thirds.
		/// </summary>
		public const string WhiteArrowShaftWidthTwoThirds_2 = "\uf0fa";

		/// <summary>
		/// Ballot Bold Script X.
		/// </summary>
		public const string BallotBoldScriptX_2 = "\uf0fb";

		/// <summary>
		/// Heavy Check Mark.
		/// </summary>
		public const string HeavyCheckMark_2 = "\uf0fc";

		/// <summary>
		/// Ballot Box With Bold Script X.
		/// </summary>
		public const string BallotBoxWithBoldScriptX_2 = "\uf0fd";

		/// <summary>
		/// Ballot Box With Bold Check.
		/// </summary>
		public const string BallotBoxWithBoldCheck_2 = "\uf0fe";

		/// <summary>
		/// Windows Flag.
		/// </summary>
		public const string WindowsFlag_2 = "\uf0ff";
	}
}
