//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirectN
{
	/// <summary>
	/// Wingdings2Glyph Enums.
	/// </summary>
	public enum Wingdings2GlyphEnum
	{
		/// <summary>
		/// Device Control Four.
		/// </summary>
		DeviceControlFour = 0x0014,

		/// <summary>
		/// Lower Left Ballpoint Pen.
		/// </summary>
		LowerLeftBallpointPen = 0x0021,

		/// <summary>
		/// Lower Left Fountain Pen.
		/// </summary>
		LowerLeftFountainPen = 0x0022,

		/// <summary>
		/// Lower Left Paintbrush.
		/// </summary>
		LowerLeftPaintbrush = 0x0023,

		/// <summary>
		/// Lower Left Crayon.
		/// </summary>
		LowerLeftCrayon = 0x0024,

		/// <summary>
		/// White Scissors.
		/// </summary>
		WhiteScissors = 0x0025,

		/// <summary>
		/// Black Safety Scissors.
		/// </summary>
		BlackSafetyScissors = 0x0026,

		/// <summary>
		/// White Touchtone Telephone.
		/// </summary>
		WhiteTouchtoneTelephone = 0x0027,

		/// <summary>
		/// Right Hand Telephone Receiver.
		/// </summary>
		RightHandTelephoneReceiver = 0x0028,

		/// <summary>
		/// Empty Note.
		/// </summary>
		EmptyNote = 0x0029,

		/// <summary>
		/// Empty Note Page.
		/// </summary>
		EmptyNotePage = 0x002a,

		/// <summary>
		/// Empty Note Pad.
		/// </summary>
		EmptyNotePad = 0x002b,

		/// <summary>
		/// Note.
		/// </summary>
		Note = 0x002c,

		/// <summary>
		/// Note Page.
		/// </summary>
		NotePage = 0x002d,

		/// <summary>
		/// Note Pad.
		/// </summary>
		NotePad = 0x002e,

		/// <summary>
		/// Empty Document.
		/// </summary>
		EmptyDocument = 0x002f,

		/// <summary>
		/// Empty Page.
		/// </summary>
		EmptyPage = 0x0030,

		/// <summary>
		/// Empty Pages.
		/// </summary>
		EmptyPages = 0x0031,

		/// <summary>
		/// Clipboard.
		/// </summary>
		Clipboard = 0x0032,

		/// <summary>
		/// Wastebasket.
		/// </summary>
		Wastebasket = 0x0033,

		/// <summary>
		/// Desktop Window.
		/// </summary>
		DesktopWindow = 0x0034,

		/// <summary>
		/// Screen.
		/// </summary>
		Screen = 0x0035,

		/// <summary>
		/// Printer Icon.
		/// </summary>
		PrinterIcon = 0x0036,

		/// <summary>
		/// Fax Icon.
		/// </summary>
		FaxIcon = 0x0037,

		/// <summary>
		/// Optical Disc Icon.
		/// </summary>
		OpticalDiscIcon = 0x0038,

		/// <summary>
		/// Tape Cartridge.
		/// </summary>
		TapeCartridge = 0x0039,

		/// <summary>
		/// One Button Mouse.
		/// </summary>
		OneButtonMouse = 0x003a,

		/// <summary>
		/// Three Button Mouse.
		/// </summary>
		ThreeButtonMouse = 0x003b,

		/// <summary>
		/// Reversed Thumbs Up Sign.
		/// </summary>
		ReversedThumbsUpSign = 0x003c,

		/// <summary>
		/// Reversed Thumbs Down Sign.
		/// </summary>
		ReversedThumbsDownSign = 0x003d,

		/// <summary>
		/// Sideways White Left Pointing Index.
		/// </summary>
		SidewaysWhiteLeftPointingIndex = 0x003e,

		/// <summary>
		/// Sideways White Right Pointing Index.
		/// </summary>
		SidewaysWhiteRightPointingIndex = 0x003f,

		/// <summary>
		/// Sideways Black Left Pointing Index.
		/// </summary>
		SidewaysBlackLeftPointingIndex = 0x0040,

		/// <summary>
		/// Sideways Black Right Pointing Index.
		/// </summary>
		SidewaysBlackRightPointingIndex = 0x0041,

		/// <summary>
		/// White Left Pointing Backhand Index.
		/// </summary>
		WhiteLeftPointingBackhandIndex = 0x0042,

		/// <summary>
		/// White Right Pointing Backhand Index.
		/// </summary>
		WhiteRightPointingBackhandIndex = 0x0043,

		/// <summary>
		/// Black Left Pointing Backhand Index.
		/// </summary>
		BlackLeftPointingBackhandIndex = 0x0044,

		/// <summary>
		/// Black Right Pointing Backhand Index.
		/// </summary>
		BlackRightPointingBackhandIndex = 0x0045,

		/// <summary>
		/// Sideways White Up Pointing Index.
		/// </summary>
		SidewaysWhiteUpPointingIndex = 0x0046,

		/// <summary>
		/// Sideways White Down Pointing Index.
		/// </summary>
		SidewaysWhiteDownPointingIndex = 0x0047,

		/// <summary>
		/// Sideways Black Up Pointing Index.
		/// </summary>
		SidewaysBlackUpPointingIndex = 0x0048,

		/// <summary>
		/// Sideways Black Down Pointing Index.
		/// </summary>
		SidewaysBlackDownPointingIndex = 0x0049,

		/// <summary>
		/// White Up Pointing Backhand Index.
		/// </summary>
		WhiteUpPointingBackhandIndex = 0x004a,

		/// <summary>
		/// White Down Pointing Backhand Index.
		/// </summary>
		WhiteDownPointingBackhandIndex = 0x004b,

		/// <summary>
		/// Black Up Pointing Backhand Index.
		/// </summary>
		BlackUpPointingBackhandIndex = 0x004c,

		/// <summary>
		/// Black Down Pointing Backhand Index.
		/// </summary>
		BlackDownPointingBackhandIndex = 0x004d,

		/// <summary>
		/// Reversed Raised Hand With Fingers Splayed.
		/// </summary>
		ReversedRaisedHandWithFingersSplayed = 0x004e,

		/// <summary>
		/// Ballot Script X.
		/// </summary>
		BallotScriptX = 0x004f,

		/// <summary>
		/// Check Mark.
		/// </summary>
		CheckMark = 0x0050,

		/// <summary>
		/// Ballot Box With Script X.
		/// </summary>
		BallotBoxWithScriptX = 0x0051,

		/// <summary>
		/// Ballot Box With Check.
		/// </summary>
		BallotBoxWithCheck = 0x0052,

		/// <summary>
		/// Ballot Box With X.
		/// </summary>
		BallotBoxWithX = 0x0053,

		/// <summary>
		/// Ballot Box With X.
		/// </summary>
		BallotBoxWithX_2 = 0x0054,

		/// <summary>
		/// Circled X.
		/// </summary>
		CircledX = 0x0055,

		/// <summary>
		/// Circled Bold X.
		/// </summary>
		CircledBoldX = 0x0056,

		/// <summary>
		/// Circled Reverse Solidus.
		/// </summary>
		CircledReverseSolidus = 0x0057,

		/// <summary>
		/// Circled Reverse Solidus.
		/// </summary>
		CircledReverseSolidus_2 = 0x0058,

		/// <summary>
		/// Heavy Script Ligature Et Ornament.
		/// </summary>
		HeavyScriptLigatureEtOrnament = 0x0059,

		/// <summary>
		/// Heavy Ampersand Ornament.
		/// </summary>
		HeavyAmpersandOrnament = 0x005a,

		/// <summary>
		/// Ligature Open Et Ornament.
		/// </summary>
		LigatureOpenEtOrnament = 0x005b,

		/// <summary>
		/// Heavy Ligature Open Et Ornament.
		/// </summary>
		HeavyLigatureOpenEtOrnament = 0x005c,

		/// <summary>
		/// Interrobang.
		/// </summary>
		Interrobang = 0x005d,

		/// <summary>
		/// Heavy Interrobang Ornament.
		/// </summary>
		HeavyInterrobangOrnament = 0x005e,

		/// <summary>
		/// Sans-Serif Interrobang Ornament.
		/// </summary>
		SansSerifInterrobangOrnament = 0x005f,

		/// <summary>
		/// Heavy Sans-Serif Interrobang Ornament.
		/// </summary>
		HeavySansSerifInterrobangOrnament = 0x0060,

		/// <summary>
		/// Heavy North East Pointing Bud.
		/// </summary>
		HeavyNorthEastPointingBud = 0x0061,

		/// <summary>
		/// Heavy North West Pointing Bud.
		/// </summary>
		HeavyNorthWestPointingBud = 0x0062,

		/// <summary>
		/// Heavy South West Pointing Bud.
		/// </summary>
		HeavySouthWestPointingBud = 0x0063,

		/// <summary>
		/// Heavy South East Pointing Bud.
		/// </summary>
		HeavySouthEastPointingBud = 0x0064,

		/// <summary>
		/// North East Pointing Vine Leaf.
		/// </summary>
		NorthEastPointingVineLeaf = 0x0065,

		/// <summary>
		/// North West Pointing Vine Leaf.
		/// </summary>
		NorthWestPointingVineLeaf = 0x0066,

		/// <summary>
		/// South West Pointing Vine Leaf.
		/// </summary>
		SouthWestPointingVineLeaf = 0x0067,

		/// <summary>
		/// South East Pointing Vine Leaf.
		/// </summary>
		SouthEastPointingVineLeaf = 0x0068,

		/// <summary>
		/// Circled Digit Zero.
		/// </summary>
		CircledDigitZero = 0x0069,

		/// <summary>
		/// Circled Digit One.
		/// </summary>
		CircledDigitOne = 0x006a,

		/// <summary>
		/// Circled Digit Two.
		/// </summary>
		CircledDigitTwo = 0x006b,

		/// <summary>
		/// Circled Digit Three.
		/// </summary>
		CircledDigitThree = 0x006c,

		/// <summary>
		/// Circled Digit Four.
		/// </summary>
		CircledDigitFour = 0x006d,

		/// <summary>
		/// Circled Digit Five.
		/// </summary>
		CircledDigitFive = 0x006e,

		/// <summary>
		/// Circled Digit Six.
		/// </summary>
		CircledDigitSix = 0x006f,

		/// <summary>
		/// Circled Digit Seven.
		/// </summary>
		CircledDigitSeven = 0x0070,

		/// <summary>
		/// Circled Digit Eight.
		/// </summary>
		CircledDigitEight = 0x0071,

		/// <summary>
		/// Circled Digit Nine.
		/// </summary>
		CircledDigitNine = 0x0072,

		/// <summary>
		/// Circled Number Ten.
		/// </summary>
		CircledNumberTen = 0x0073,

		/// <summary>
		/// Negative Circled Digit Zero.
		/// </summary>
		NegativeCircledDigitZero = 0x0074,

		/// <summary>
		/// Dingbat Negative Circled Digit One.
		/// </summary>
		DingbatNegativeCircledDigitOne = 0x0075,

		/// <summary>
		/// Dingbat Negative Circled Digit Two.
		/// </summary>
		DingbatNegativeCircledDigitTwo = 0x0076,

		/// <summary>
		/// Dingbat Negative Circled Digit Three.
		/// </summary>
		DingbatNegativeCircledDigitThree = 0x0077,

		/// <summary>
		/// Dingbat Negative Circled Digit Four.
		/// </summary>
		DingbatNegativeCircledDigitFour = 0x0078,

		/// <summary>
		/// Dingbat Negative Circled Digit Five.
		/// </summary>
		DingbatNegativeCircledDigitFive = 0x0079,

		/// <summary>
		/// Dingbat Negative Circled Digit Six.
		/// </summary>
		DingbatNegativeCircledDigitSix = 0x007a,

		/// <summary>
		/// Dingbat Negative Circled Digit Seven.
		/// </summary>
		DingbatNegativeCircledDigitSeven = 0x007b,

		/// <summary>
		/// Dingbat Negative Circled Digit Eight.
		/// </summary>
		DingbatNegativeCircledDigitEight = 0x007c,

		/// <summary>
		/// Dingbat Negative Circled Digit Nine.
		/// </summary>
		DingbatNegativeCircledDigitNine = 0x007d,

		/// <summary>
		/// Dingbat Negative Circled Number Ten.
		/// </summary>
		DingbatNegativeCircledNumberTen = 0x007e,

		/// <summary>
		/// Sun.
		/// </summary>
		Sun = 0x0080,

		/// <summary>
		/// Full Moon Symbol.
		/// </summary>
		FullMoonSymbol = 0x0081,

		/// <summary>
		/// First Quarter Moon.
		/// </summary>
		FirstQuarterMoon = 0x0082,

		/// <summary>
		/// Last Quarter Moon.
		/// </summary>
		LastQuarterMoon = 0x0083,

		/// <summary>
		/// Capitulum.
		/// </summary>
		Capitulum = 0x0084,

		/// <summary>
		/// Latin Cross.
		/// </summary>
		LatinCross = 0x0085,

		/// <summary>
		/// Heavy Latin Cross.
		/// </summary>
		HeavyLatinCross = 0x0086,

		/// <summary>
		/// Clock Face One-Thirty.
		/// </summary>
		ClockFaceOneThirty = 0x0087,

		/// <summary>
		/// Clock Face Two-Thirty.
		/// </summary>
		ClockFaceTwoThirty = 0x0088,

		/// <summary>
		/// Clock Face Three-Thirty.
		/// </summary>
		ClockFaceThreeThirty = 0x0089,

		/// <summary>
		/// Clock Face Four-Thirty.
		/// </summary>
		ClockFaceFourThirty = 0x008a,

		/// <summary>
		/// Clock Face Five-Thirty.
		/// </summary>
		ClockFaceFiveThirty = 0x008b,

		/// <summary>
		/// Clock Face Six-Thirty.
		/// </summary>
		ClockFaceSixThirty = 0x008c,

		/// <summary>
		/// Clock Face Seven-Thirty.
		/// </summary>
		ClockFaceSevenThirty = 0x008d,

		/// <summary>
		/// Clock Face Eight-Thirty.
		/// </summary>
		ClockFaceEightThirty = 0x008e,

		/// <summary>
		/// Clock Face Nine-Thirty.
		/// </summary>
		ClockFaceNineThirty = 0x008f,

		/// <summary>
		/// Clock Face Ten-Thirty.
		/// </summary>
		ClockFaceTenThirty = 0x0090,

		/// <summary>
		/// Clock Face Eleven-Thirty.
		/// </summary>
		ClockFaceElevenThirty = 0x0091,

		/// <summary>
		/// Clock Face Twelve-Thirty.
		/// </summary>
		ClockFaceTwelveThirty = 0x0092,

		/// <summary>
		/// Hollow Quilt Square Ornament.
		/// </summary>
		HollowQuiltSquareOrnament = 0x0093,

		/// <summary>
		/// Hollow Quilt Square Ornament In Black Square.
		/// </summary>
		HollowQuiltSquareOrnamentInBlackSquare = 0x0094,

		/// <summary>
		/// Bullet.
		/// </summary>
		Bullet = 0x0095,

		/// <summary>
		/// Black Circle.
		/// </summary>
		BlackCircle = 0x0096,

		/// <summary>
		/// Medium Black Circle.
		/// </summary>
		MediumBlackCircle = 0x0097,

		/// <summary>
		/// Black Large Circle.
		/// </summary>
		BlackLargeCircle = 0x0098,

		/// <summary>
		/// Medium Bold White Circle.
		/// </summary>
		MediumBoldWhiteCircle = 0x0099,

		/// <summary>
		/// Bold White Circle.
		/// </summary>
		BoldWhiteCircle = 0x009a,

		/// <summary>
		/// Heavy White Circle.
		/// </summary>
		HeavyWhiteCircle = 0x009b,

		/// <summary>
		/// Very Heavy White Circle.
		/// </summary>
		VeryHeavyWhiteCircle = 0x009c,

		/// <summary>
		/// White Circle Containing Black Small Circle.
		/// </summary>
		WhiteCircleContainingBlackSmallCircle = 0x009d,

		/// <summary>
		/// Circled Bullet.
		/// </summary>
		CircledBullet = 0x009e,

		/// <summary>
		/// Black Medium Small Square.
		/// </summary>
		BlackMediumSmallSquare = 0x009f,

		/// <summary>
		/// Black Square.
		/// </summary>
		BlackSquare = 0x00a0,

		/// <summary>
		/// Black Medium Square.
		/// </summary>
		BlackMediumSquare = 0x00a1,

		/// <summary>
		/// Black Large Square.
		/// </summary>
		BlackLargeSquare = 0x00a2,

		/// <summary>
		/// White Large Square.
		/// </summary>
		WhiteLargeSquare = 0x00a3,

		/// <summary>
		/// Heavy White Square.
		/// </summary>
		HeavyWhiteSquare = 0x00a4,

		/// <summary>
		/// Very Heavy White Square.
		/// </summary>
		VeryHeavyWhiteSquare = 0x00a5,

		/// <summary>
		/// Extremely Heavy White Square.
		/// </summary>
		ExtremelyHeavyWhiteSquare = 0x00a6,

		/// <summary>
		/// White Square Containing Black Very Small Square.
		/// </summary>
		WhiteSquareContainingBlackVerySmallSquare = 0x00a7,

		/// <summary>
		/// White Square Containing Black Small Square.
		/// </summary>
		WhiteSquareContainingBlackSmallSquare = 0x00a8,

		/// <summary>
		/// White Square Containing Black Medium Square.
		/// </summary>
		WhiteSquareContainingBlackMediumSquare = 0x00a9,

		/// <summary>
		/// Square Target.
		/// </summary>
		SquareTarget = 0x00aa,

		/// <summary>
		/// Black Tiny Diamond.
		/// </summary>
		BlackTinyDiamond = 0x00ab,

		/// <summary>
		/// Black Small Diamond.
		/// </summary>
		BlackSmallDiamond = 0x00ac,

		/// <summary>
		/// Black Medium Diamond.
		/// </summary>
		BlackMediumDiamond = 0x00ad,

		/// <summary>
		/// Black Diamond.
		/// </summary>
		BlackDiamond = 0x00ae,

		/// <summary>
		/// White Diamond.
		/// </summary>
		WhiteDiamond = 0x00af,

		/// <summary>
		/// White Diamond Containing Black Very Small Diamond.
		/// </summary>
		WhiteDiamondContainingBlackVerySmallDiamond = 0x00b0,

		/// <summary>
		/// White Diamond Containing Black Small Diamond.
		/// </summary>
		WhiteDiamondContainingBlackSmallDiamond = 0x00b1,

		/// <summary>
		/// White Diamond Containing Black Medium Diamond.
		/// </summary>
		WhiteDiamondContainingBlackMediumDiamond = 0x00b2,

		/// <summary>
		/// Diamond Target.
		/// </summary>
		DiamondTarget = 0x00b3,

		/// <summary>
		/// Black Tiny Lozenge.
		/// </summary>
		BlackTinyLozenge = 0x00b4,

		/// <summary>
		/// Black Small Lozenge.
		/// </summary>
		BlackSmallLozenge = 0x00b5,

		/// <summary>
		/// Black Medium Lozenge.
		/// </summary>
		BlackMediumLozenge = 0x00b6,

		/// <summary>
		/// Black Lozenge.
		/// </summary>
		BlackLozenge = 0x00b7,

		/// <summary>
		/// Lozenge.
		/// </summary>
		Lozenge = 0x00b8,

		/// <summary>
		/// White Lozenge Containing Black Small Lozenge.
		/// </summary>
		WhiteLozengeContainingBlackSmallLozenge = 0x00b9,

		/// <summary>
		/// Left Half Black Circle.
		/// </summary>
		LeftHalfBlackCircle = 0x00ba,

		/// <summary>
		/// Right Half Black Circle.
		/// </summary>
		RightHalfBlackCircle = 0x00bb,

		/// <summary>
		/// Top Half Black Circle.
		/// </summary>
		TopHalfBlackCircle = 0x00bc,

		/// <summary>
		/// Bottom Half Black Circle.
		/// </summary>
		BottomHalfBlackCircle = 0x00bd,

		/// <summary>
		/// Black Medium Square.
		/// </summary>
		BlackMediumSquare_2 = 0x00be,

		/// <summary>
		/// Black Medium Diamond.
		/// </summary>
		BlackMediumDiamond_2 = 0x00bf,

		/// <summary>
		/// Black Pentagon.
		/// </summary>
		BlackPentagon = 0x00c0,

		/// <summary>
		/// Turned Black Pentagon.
		/// </summary>
		TurnedBlackPentagon = 0x00c1,

		/// <summary>
		/// Horizontal Black Hexagon.
		/// </summary>
		HorizontalBlackHexagon = 0x00c2,

		/// <summary>
		/// Black Hexagon.
		/// </summary>
		BlackHexagon = 0x00c3,

		/// <summary>
		/// Horizontal Black Octagon.
		/// </summary>
		HorizontalBlackOctagon = 0x00c4,

		/// <summary>
		/// Black Octagon.
		/// </summary>
		BlackOctagon = 0x00c5,

		/// <summary>
		/// Thin Greek Cross.
		/// </summary>
		ThinGreekCross = 0x00c6,

		/// <summary>
		/// Light Greek Cross.
		/// </summary>
		LightGreekCross = 0x00c7,

		/// <summary>
		/// Medium Greek Cross.
		/// </summary>
		MediumGreekCross = 0x00c8,

		/// <summary>
		/// Bold Greek Cross.
		/// </summary>
		BoldGreekCross = 0x00c9,

		/// <summary>
		/// Very Bold Greek Cross.
		/// </summary>
		VeryBoldGreekCross = 0x00ca,

		/// <summary>
		/// Very Heavy Greek Cross.
		/// </summary>
		VeryHeavyGreekCross = 0x00cb,

		/// <summary>
		/// Extremely Heavy Greek Cross.
		/// </summary>
		ExtremelyHeavyGreekCross = 0x00cc,

		/// <summary>
		/// Thin Saltire.
		/// </summary>
		ThinSaltire = 0x00cd,

		/// <summary>
		/// Light Saltire.
		/// </summary>
		LightSaltire = 0x00ce,

		/// <summary>
		/// Medium Saltire.
		/// </summary>
		MediumSaltire = 0x00cf,

		/// <summary>
		/// Bold Saltire.
		/// </summary>
		BoldSaltire = 0x00d0,

		/// <summary>
		/// Heavy Saltire.
		/// </summary>
		HeavySaltire = 0x00d1,

		/// <summary>
		/// Very Heavy Saltire.
		/// </summary>
		VeryHeavySaltire = 0x00d2,

		/// <summary>
		/// Extremely Heavy Saltire.
		/// </summary>
		ExtremelyHeavySaltire = 0x00d3,

		/// <summary>
		/// Light Five Spoked Asterisk.
		/// </summary>
		LightFiveSpokedAsterisk = 0x00d4,

		/// <summary>
		/// Medium Five Spoked Asterisk.
		/// </summary>
		MediumFiveSpokedAsterisk = 0x00d5,

		/// <summary>
		/// Bold Five Spoked Asterisk.
		/// </summary>
		BoldFiveSpokedAsterisk = 0x00d6,

		/// <summary>
		/// Heavy Five Spoked Asterisk.
		/// </summary>
		HeavyFiveSpokedAsterisk = 0x00d7,

		/// <summary>
		/// Very Heavy Five Spoked Asterisk.
		/// </summary>
		VeryHeavyFiveSpokedAsterisk = 0x00d8,

		/// <summary>
		/// Extremely Heavy Five Spoked Asterisk.
		/// </summary>
		ExtremelyHeavyFiveSpokedAsterisk = 0x00d9,

		/// <summary>
		/// Light Six Spoked Asterisk.
		/// </summary>
		LightSixSpokedAsterisk = 0x00da,

		/// <summary>
		/// Medium Six Spoked Asterisk.
		/// </summary>
		MediumSixSpokedAsterisk = 0x00db,

		/// <summary>
		/// Bold Six Spoked Asterisk.
		/// </summary>
		BoldSixSpokedAsterisk = 0x00dc,

		/// <summary>
		/// Heavy Six Spoked Asterisk.
		/// </summary>
		HeavySixSpokedAsterisk = 0x00dd,

		/// <summary>
		/// Very Heavy Six Spoked Asterisk.
		/// </summary>
		VeryHeavySixSpokedAsterisk = 0x00de,

		/// <summary>
		/// Extremely Heavy Six Spoked Asterisk.
		/// </summary>
		ExtremelyHeavySixSpokedAsterisk = 0x00df,

		/// <summary>
		/// Light Eight Spoked Asterisk.
		/// </summary>
		LightEightSpokedAsterisk = 0x00e0,

		/// <summary>
		/// Medium Eight Spoked Asterisk.
		/// </summary>
		MediumEightSpokedAsterisk = 0x00e1,

		/// <summary>
		/// Bold Eight Spoked Asterisk.
		/// </summary>
		BoldEightSpokedAsterisk = 0x00e2,

		/// <summary>
		/// Heavy Eight Spoked Asterisk.
		/// </summary>
		HeavyEightSpokedAsterisk = 0x00e3,

		/// <summary>
		/// Very Heavy Eight Spoked Asterisk.
		/// </summary>
		VeryHeavyEightSpokedAsterisk = 0x00e4,

		/// <summary>
		/// Light Three Pointed Black Star.
		/// </summary>
		LightThreePointedBlackStar = 0x00e5,

		/// <summary>
		/// Three Pointed Black Star.
		/// </summary>
		ThreePointedBlackStar = 0x00e6,

		/// <summary>
		/// Light Four Pointed Black Star.
		/// </summary>
		LightFourPointedBlackStar = 0x00e7,

		/// <summary>
		/// Black Four Pointed Star.
		/// </summary>
		BlackFourPointedStar = 0x00e8,

		/// <summary>
		/// Light Five Pointed Black Star.
		/// </summary>
		LightFivePointedBlackStar = 0x00e9,

		/// <summary>
		/// Black Star.
		/// </summary>
		BlackStar = 0x00ea,

		/// <summary>
		/// Six Pointed Black Star.
		/// </summary>
		SixPointedBlackStar = 0x00eb,

		/// <summary>
		/// Medium Six Pointed Black Star.
		/// </summary>
		MediumSixPointedBlackStar = 0x00ec,

		/// <summary>
		/// Eight Pointed Rectilinear Black Star.
		/// </summary>
		EightPointedRectilinearBlackStar = 0x00ed,

		/// <summary>
		/// Heavy Eight Pointed Black Star.
		/// </summary>
		HeavyEightPointedBlackStar = 0x00ee,

		/// <summary>
		/// Light Twelve Pointed Black Star.
		/// </summary>
		LightTwelvePointedBlackStar = 0x00ef,

		/// <summary>
		/// Twelve Pointed Black Star.
		/// </summary>
		TwelvePointedBlackStar = 0x00f0,

		/// <summary>
		/// Medium Three Pointed Pinwheel Star.
		/// </summary>
		MediumThreePointedPinwheelStar = 0x00f1,

		/// <summary>
		/// Medium Four Pointed Pinwheel Star.
		/// </summary>
		MediumFourPointedPinwheelStar = 0x00f2,

		/// <summary>
		/// Pinwheel Star.
		/// </summary>
		PinwheelStar = 0x00f3,

		/// <summary>
		/// Six Pointed Pinwheel Star.
		/// </summary>
		SixPointedPinwheelStar = 0x00f4,

		/// <summary>
		/// Heavy Twelve Pointed Pinwheel Star.
		/// </summary>
		HeavyTwelvePointedPinwheelStar = 0x00f5,

		/// <summary>
		/// Light Four Pointed Black Cusp.
		/// </summary>
		LightFourPointedBlackCusp = 0x00f6,

		/// <summary>
		/// Rotated Light Four Pointed Black Cusp.
		/// </summary>
		RotatedLightFourPointedBlackCusp = 0x00f7,

		/// <summary>
		/// Reference Mark.
		/// </summary>
		ReferenceMark = 0x00f8,

		/// <summary>
		/// Asterism.
		/// </summary>
		Asterism = 0x00f9,

		/// <summary>
		/// Device Control Four.
		/// </summary>
		DeviceControlFour_2 = 0xf014,

		/// <summary>
		/// Lower Left Ballpoint Pen.
		/// </summary>
		LowerLeftBallpointPen_2 = 0xf021,

		/// <summary>
		/// Lower Left Fountain Pen.
		/// </summary>
		LowerLeftFountainPen_2 = 0xf022,

		/// <summary>
		/// Lower Left Paintbrush.
		/// </summary>
		LowerLeftPaintbrush_2 = 0xf023,

		/// <summary>
		/// Lower Left Crayon.
		/// </summary>
		LowerLeftCrayon_2 = 0xf024,

		/// <summary>
		/// White Scissors.
		/// </summary>
		WhiteScissors_2 = 0xf025,

		/// <summary>
		/// Black Safety Scissors.
		/// </summary>
		BlackSafetyScissors_2 = 0xf026,

		/// <summary>
		/// White Touchtone Telephone.
		/// </summary>
		WhiteTouchtoneTelephone_2 = 0xf027,

		/// <summary>
		/// Right Hand Telephone Receiver.
		/// </summary>
		RightHandTelephoneReceiver_2 = 0xf028,

		/// <summary>
		/// Empty Note.
		/// </summary>
		EmptyNote_2 = 0xf029,

		/// <summary>
		/// Empty Note Page.
		/// </summary>
		EmptyNotePage_2 = 0xf02a,

		/// <summary>
		/// Empty Note Pad.
		/// </summary>
		EmptyNotePad_2 = 0xf02b,

		/// <summary>
		/// Note.
		/// </summary>
		Note_2 = 0xf02c,

		/// <summary>
		/// Note Page.
		/// </summary>
		NotePage_2 = 0xf02d,

		/// <summary>
		/// Note Pad.
		/// </summary>
		NotePad_2 = 0xf02e,

		/// <summary>
		/// Empty Document.
		/// </summary>
		EmptyDocument_2 = 0xf02f,

		/// <summary>
		/// Empty Page.
		/// </summary>
		EmptyPage_2 = 0xf030,

		/// <summary>
		/// Empty Pages.
		/// </summary>
		EmptyPages_2 = 0xf031,

		/// <summary>
		/// Clipboard.
		/// </summary>
		Clipboard_2 = 0xf032,

		/// <summary>
		/// Wastebasket.
		/// </summary>
		Wastebasket_2 = 0xf033,

		/// <summary>
		/// Desktop Window.
		/// </summary>
		DesktopWindow_2 = 0xf034,

		/// <summary>
		/// Screen.
		/// </summary>
		Screen_2 = 0xf035,

		/// <summary>
		/// Printer Icon.
		/// </summary>
		PrinterIcon_2 = 0xf036,

		/// <summary>
		/// Fax Icon.
		/// </summary>
		FaxIcon_2 = 0xf037,

		/// <summary>
		/// Optical Disc Icon.
		/// </summary>
		OpticalDiscIcon_2 = 0xf038,

		/// <summary>
		/// Tape Cartridge.
		/// </summary>
		TapeCartridge_2 = 0xf039,

		/// <summary>
		/// One Button Mouse.
		/// </summary>
		OneButtonMouse_2 = 0xf03a,

		/// <summary>
		/// Three Button Mouse.
		/// </summary>
		ThreeButtonMouse_2 = 0xf03b,

		/// <summary>
		/// Reversed Thumbs Up Sign.
		/// </summary>
		ReversedThumbsUpSign_2 = 0xf03c,

		/// <summary>
		/// Reversed Thumbs Down Sign.
		/// </summary>
		ReversedThumbsDownSign_2 = 0xf03d,

		/// <summary>
		/// Sideways White Left Pointing Index.
		/// </summary>
		SidewaysWhiteLeftPointingIndex_2 = 0xf03e,

		/// <summary>
		/// Sideways White Right Pointing Index.
		/// </summary>
		SidewaysWhiteRightPointingIndex_2 = 0xf03f,

		/// <summary>
		/// Sideways Black Left Pointing Index.
		/// </summary>
		SidewaysBlackLeftPointingIndex_2 = 0xf040,

		/// <summary>
		/// Sideways Black Right Pointing Index.
		/// </summary>
		SidewaysBlackRightPointingIndex_2 = 0xf041,

		/// <summary>
		/// White Left Pointing Backhand Index.
		/// </summary>
		WhiteLeftPointingBackhandIndex_2 = 0xf042,

		/// <summary>
		/// White Right Pointing Backhand Index.
		/// </summary>
		WhiteRightPointingBackhandIndex_2 = 0xf043,

		/// <summary>
		/// Black Left Pointing Backhand Index.
		/// </summary>
		BlackLeftPointingBackhandIndex_2 = 0xf044,

		/// <summary>
		/// Black Right Pointing Backhand Index.
		/// </summary>
		BlackRightPointingBackhandIndex_2 = 0xf045,

		/// <summary>
		/// Sideways White Up Pointing Index.
		/// </summary>
		SidewaysWhiteUpPointingIndex_2 = 0xf046,

		/// <summary>
		/// Sideways White Down Pointing Index.
		/// </summary>
		SidewaysWhiteDownPointingIndex_2 = 0xf047,

		/// <summary>
		/// Sideways Black Up Pointing Index.
		/// </summary>
		SidewaysBlackUpPointingIndex_2 = 0xf048,

		/// <summary>
		/// Sideways Black Down Pointing Index.
		/// </summary>
		SidewaysBlackDownPointingIndex_2 = 0xf049,

		/// <summary>
		/// White Up Pointing Backhand Index.
		/// </summary>
		WhiteUpPointingBackhandIndex_2 = 0xf04a,

		/// <summary>
		/// White Down Pointing Backhand Index.
		/// </summary>
		WhiteDownPointingBackhandIndex_2 = 0xf04b,

		/// <summary>
		/// Black Up Pointing Backhand Index.
		/// </summary>
		BlackUpPointingBackhandIndex_2 = 0xf04c,

		/// <summary>
		/// Black Down Pointing Backhand Index.
		/// </summary>
		BlackDownPointingBackhandIndex_2 = 0xf04d,

		/// <summary>
		/// Reversed Raised Hand With Fingers Splayed.
		/// </summary>
		ReversedRaisedHandWithFingersSplayed_2 = 0xf04e,

		/// <summary>
		/// Ballot Script X.
		/// </summary>
		BallotScriptX_2 = 0xf04f,

		/// <summary>
		/// Check Mark.
		/// </summary>
		CheckMark_2 = 0xf050,

		/// <summary>
		/// Ballot Box With Script X.
		/// </summary>
		BallotBoxWithScriptX_2 = 0xf051,

		/// <summary>
		/// Ballot Box With Check.
		/// </summary>
		BallotBoxWithCheck_2 = 0xf052,

		/// <summary>
		/// Ballot Box With X.
		/// </summary>
		BallotBoxWithX_3 = 0xf053,

		/// <summary>
		/// Ballot Box With X.
		/// </summary>
		BallotBoxWithX_4 = 0xf054,

		/// <summary>
		/// Circled X.
		/// </summary>
		CircledX_2 = 0xf055,

		/// <summary>
		/// Circled Bold X.
		/// </summary>
		CircledBoldX_2 = 0xf056,

		/// <summary>
		/// Circled Reverse Solidus.
		/// </summary>
		CircledReverseSolidus_3 = 0xf057,

		/// <summary>
		/// Circled Reverse Solidus.
		/// </summary>
		CircledReverseSolidus_4 = 0xf058,

		/// <summary>
		/// Heavy Script Ligature Et Ornament.
		/// </summary>
		HeavyScriptLigatureEtOrnament_2 = 0xf059,

		/// <summary>
		/// Heavy Ampersand Ornament.
		/// </summary>
		HeavyAmpersandOrnament_2 = 0xf05a,

		/// <summary>
		/// Ligature Open Et Ornament.
		/// </summary>
		LigatureOpenEtOrnament_2 = 0xf05b,

		/// <summary>
		/// Heavy Ligature Open Et Ornament.
		/// </summary>
		HeavyLigatureOpenEtOrnament_2 = 0xf05c,

		/// <summary>
		/// Interrobang.
		/// </summary>
		Interrobang_2 = 0xf05d,

		/// <summary>
		/// Heavy Interrobang Ornament.
		/// </summary>
		HeavyInterrobangOrnament_2 = 0xf05e,

		/// <summary>
		/// Sans-Serif Interrobang Ornament.
		/// </summary>
		SansSerifInterrobangOrnament_2 = 0xf05f,

		/// <summary>
		/// Heavy Sans-Serif Interrobang Ornament.
		/// </summary>
		HeavySansSerifInterrobangOrnament_2 = 0xf060,

		/// <summary>
		/// Heavy North East Pointing Bud.
		/// </summary>
		HeavyNorthEastPointingBud_2 = 0xf061,

		/// <summary>
		/// Heavy North West Pointing Bud.
		/// </summary>
		HeavyNorthWestPointingBud_2 = 0xf062,

		/// <summary>
		/// Heavy South West Pointing Bud.
		/// </summary>
		HeavySouthWestPointingBud_2 = 0xf063,

		/// <summary>
		/// Heavy South East Pointing Bud.
		/// </summary>
		HeavySouthEastPointingBud_2 = 0xf064,

		/// <summary>
		/// North East Pointing Vine Leaf.
		/// </summary>
		NorthEastPointingVineLeaf_2 = 0xf065,

		/// <summary>
		/// North West Pointing Vine Leaf.
		/// </summary>
		NorthWestPointingVineLeaf_2 = 0xf066,

		/// <summary>
		/// South West Pointing Vine Leaf.
		/// </summary>
		SouthWestPointingVineLeaf_2 = 0xf067,

		/// <summary>
		/// South East Pointing Vine Leaf.
		/// </summary>
		SouthEastPointingVineLeaf_2 = 0xf068,

		/// <summary>
		/// Circled Digit Zero.
		/// </summary>
		CircledDigitZero_2 = 0xf069,

		/// <summary>
		/// Circled Digit One.
		/// </summary>
		CircledDigitOne_2 = 0xf06a,

		/// <summary>
		/// Circled Digit Two.
		/// </summary>
		CircledDigitTwo_2 = 0xf06b,

		/// <summary>
		/// Circled Digit Three.
		/// </summary>
		CircledDigitThree_2 = 0xf06c,

		/// <summary>
		/// Circled Digit Four.
		/// </summary>
		CircledDigitFour_2 = 0xf06d,

		/// <summary>
		/// Circled Digit Five.
		/// </summary>
		CircledDigitFive_2 = 0xf06e,

		/// <summary>
		/// Circled Digit Six.
		/// </summary>
		CircledDigitSix_2 = 0xf06f,

		/// <summary>
		/// Circled Digit Seven.
		/// </summary>
		CircledDigitSeven_2 = 0xf070,

		/// <summary>
		/// Circled Digit Eight.
		/// </summary>
		CircledDigitEight_2 = 0xf071,

		/// <summary>
		/// Circled Digit Nine.
		/// </summary>
		CircledDigitNine_2 = 0xf072,

		/// <summary>
		/// Circled Number Ten.
		/// </summary>
		CircledNumberTen_2 = 0xf073,

		/// <summary>
		/// Negative Circled Digit Zero.
		/// </summary>
		NegativeCircledDigitZero_2 = 0xf074,

		/// <summary>
		/// Dingbat Negative Circled Digit One.
		/// </summary>
		DingbatNegativeCircledDigitOne_2 = 0xf075,

		/// <summary>
		/// Dingbat Negative Circled Digit Two.
		/// </summary>
		DingbatNegativeCircledDigitTwo_2 = 0xf076,

		/// <summary>
		/// Dingbat Negative Circled Digit Three.
		/// </summary>
		DingbatNegativeCircledDigitThree_2 = 0xf077,

		/// <summary>
		/// Dingbat Negative Circled Digit Four.
		/// </summary>
		DingbatNegativeCircledDigitFour_2 = 0xf078,

		/// <summary>
		/// Dingbat Negative Circled Digit Five.
		/// </summary>
		DingbatNegativeCircledDigitFive_2 = 0xf079,

		/// <summary>
		/// Dingbat Negative Circled Digit Six.
		/// </summary>
		DingbatNegativeCircledDigitSix_2 = 0xf07a,

		/// <summary>
		/// Dingbat Negative Circled Digit Seven.
		/// </summary>
		DingbatNegativeCircledDigitSeven_2 = 0xf07b,

		/// <summary>
		/// Dingbat Negative Circled Digit Eight.
		/// </summary>
		DingbatNegativeCircledDigitEight_2 = 0xf07c,

		/// <summary>
		/// Dingbat Negative Circled Digit Nine.
		/// </summary>
		DingbatNegativeCircledDigitNine_2 = 0xf07d,

		/// <summary>
		/// Dingbat Negative Circled Number Ten.
		/// </summary>
		DingbatNegativeCircledNumberTen_2 = 0xf07e,

		/// <summary>
		/// Sun.
		/// </summary>
		Sun_2 = 0xf080,

		/// <summary>
		/// Full Moon Symbol.
		/// </summary>
		FullMoonSymbol_2 = 0xf081,

		/// <summary>
		/// First Quarter Moon.
		/// </summary>
		FirstQuarterMoon_2 = 0xf082,

		/// <summary>
		/// Last Quarter Moon.
		/// </summary>
		LastQuarterMoon_2 = 0xf083,

		/// <summary>
		/// Capitulum.
		/// </summary>
		Capitulum_2 = 0xf084,

		/// <summary>
		/// Latin Cross.
		/// </summary>
		LatinCross_2 = 0xf085,

		/// <summary>
		/// Heavy Latin Cross.
		/// </summary>
		HeavyLatinCross_2 = 0xf086,

		/// <summary>
		/// Clock Face One-Thirty.
		/// </summary>
		ClockFaceOneThirty_2 = 0xf087,

		/// <summary>
		/// Clock Face Two-Thirty.
		/// </summary>
		ClockFaceTwoThirty_2 = 0xf088,

		/// <summary>
		/// Clock Face Three-Thirty.
		/// </summary>
		ClockFaceThreeThirty_2 = 0xf089,

		/// <summary>
		/// Clock Face Four-Thirty.
		/// </summary>
		ClockFaceFourThirty_2 = 0xf08a,

		/// <summary>
		/// Clock Face Five-Thirty.
		/// </summary>
		ClockFaceFiveThirty_2 = 0xf08b,

		/// <summary>
		/// Clock Face Six-Thirty.
		/// </summary>
		ClockFaceSixThirty_2 = 0xf08c,

		/// <summary>
		/// Clock Face Seven-Thirty.
		/// </summary>
		ClockFaceSevenThirty_2 = 0xf08d,

		/// <summary>
		/// Clock Face Eight-Thirty.
		/// </summary>
		ClockFaceEightThirty_2 = 0xf08e,

		/// <summary>
		/// Clock Face Nine-Thirty.
		/// </summary>
		ClockFaceNineThirty_2 = 0xf08f,

		/// <summary>
		/// Clock Face Ten-Thirty.
		/// </summary>
		ClockFaceTenThirty_2 = 0xf090,

		/// <summary>
		/// Clock Face Eleven-Thirty.
		/// </summary>
		ClockFaceElevenThirty_2 = 0xf091,

		/// <summary>
		/// Clock Face Twelve-Thirty.
		/// </summary>
		ClockFaceTwelveThirty_2 = 0xf092,

		/// <summary>
		/// Hollow Quilt Square Ornament.
		/// </summary>
		HollowQuiltSquareOrnament_2 = 0xf093,

		/// <summary>
		/// Hollow Quilt Square Ornament In Black Square.
		/// </summary>
		HollowQuiltSquareOrnamentInBlackSquare_2 = 0xf094,

		/// <summary>
		/// Bullet.
		/// </summary>
		Bullet_2 = 0xf095,

		/// <summary>
		/// Black Circle.
		/// </summary>
		BlackCircle_2 = 0xf096,

		/// <summary>
		/// Medium Black Circle.
		/// </summary>
		MediumBlackCircle_2 = 0xf097,

		/// <summary>
		/// Black Large Circle.
		/// </summary>
		BlackLargeCircle_2 = 0xf098,

		/// <summary>
		/// Medium Bold White Circle.
		/// </summary>
		MediumBoldWhiteCircle_2 = 0xf099,

		/// <summary>
		/// Bold White Circle.
		/// </summary>
		BoldWhiteCircle_2 = 0xf09a,

		/// <summary>
		/// Heavy White Circle.
		/// </summary>
		HeavyWhiteCircle_2 = 0xf09b,

		/// <summary>
		/// Very Heavy White Circle.
		/// </summary>
		VeryHeavyWhiteCircle_2 = 0xf09c,

		/// <summary>
		/// White Circle Containing Black Small Circle.
		/// </summary>
		WhiteCircleContainingBlackSmallCircle_2 = 0xf09d,

		/// <summary>
		/// Circled Bullet.
		/// </summary>
		CircledBullet_2 = 0xf09e,

		/// <summary>
		/// Black Medium Small Square.
		/// </summary>
		BlackMediumSmallSquare_2 = 0xf09f,

		/// <summary>
		/// Black Square.
		/// </summary>
		BlackSquare_2 = 0xf0a0,

		/// <summary>
		/// Black Medium Square.
		/// </summary>
		BlackMediumSquare_3 = 0xf0a1,

		/// <summary>
		/// Black Large Square.
		/// </summary>
		BlackLargeSquare_2 = 0xf0a2,

		/// <summary>
		/// White Large Square.
		/// </summary>
		WhiteLargeSquare_2 = 0xf0a3,

		/// <summary>
		/// Heavy White Square.
		/// </summary>
		HeavyWhiteSquare_2 = 0xf0a4,

		/// <summary>
		/// Very Heavy White Square.
		/// </summary>
		VeryHeavyWhiteSquare_2 = 0xf0a5,

		/// <summary>
		/// Extremely Heavy White Square.
		/// </summary>
		ExtremelyHeavyWhiteSquare_2 = 0xf0a6,

		/// <summary>
		/// White Square Containing Black Very Small Square.
		/// </summary>
		WhiteSquareContainingBlackVerySmallSquare_2 = 0xf0a7,

		/// <summary>
		/// White Square Containing Black Small Square.
		/// </summary>
		WhiteSquareContainingBlackSmallSquare_2 = 0xf0a8,

		/// <summary>
		/// White Square Containing Black Medium Square.
		/// </summary>
		WhiteSquareContainingBlackMediumSquare_2 = 0xf0a9,

		/// <summary>
		/// Square Target.
		/// </summary>
		SquareTarget_2 = 0xf0aa,

		/// <summary>
		/// Black Tiny Diamond.
		/// </summary>
		BlackTinyDiamond_2 = 0xf0ab,

		/// <summary>
		/// Black Small Diamond.
		/// </summary>
		BlackSmallDiamond_2 = 0xf0ac,

		/// <summary>
		/// Black Medium Diamond.
		/// </summary>
		BlackMediumDiamond_3 = 0xf0ad,

		/// <summary>
		/// Black Diamond.
		/// </summary>
		BlackDiamond_2 = 0xf0ae,

		/// <summary>
		/// White Diamond.
		/// </summary>
		WhiteDiamond_2 = 0xf0af,

		/// <summary>
		/// White Diamond Containing Black Very Small Diamond.
		/// </summary>
		WhiteDiamondContainingBlackVerySmallDiamond_2 = 0xf0b0,

		/// <summary>
		/// White Diamond Containing Black Small Diamond.
		/// </summary>
		WhiteDiamondContainingBlackSmallDiamond_2 = 0xf0b1,

		/// <summary>
		/// White Diamond Containing Black Medium Diamond.
		/// </summary>
		WhiteDiamondContainingBlackMediumDiamond_2 = 0xf0b2,

		/// <summary>
		/// Diamond Target.
		/// </summary>
		DiamondTarget_2 = 0xf0b3,

		/// <summary>
		/// Black Tiny Lozenge.
		/// </summary>
		BlackTinyLozenge_2 = 0xf0b4,

		/// <summary>
		/// Black Small Lozenge.
		/// </summary>
		BlackSmallLozenge_2 = 0xf0b5,

		/// <summary>
		/// Black Medium Lozenge.
		/// </summary>
		BlackMediumLozenge_2 = 0xf0b6,

		/// <summary>
		/// Black Lozenge.
		/// </summary>
		BlackLozenge_2 = 0xf0b7,

		/// <summary>
		/// Lozenge.
		/// </summary>
		Lozenge_2 = 0xf0b8,

		/// <summary>
		/// White Lozenge Containing Black Small Lozenge.
		/// </summary>
		WhiteLozengeContainingBlackSmallLozenge_2 = 0xf0b9,

		/// <summary>
		/// Left Half Black Circle.
		/// </summary>
		LeftHalfBlackCircle_2 = 0xf0ba,

		/// <summary>
		/// Right Half Black Circle.
		/// </summary>
		RightHalfBlackCircle_2 = 0xf0bb,

		/// <summary>
		/// Top Half Black Circle.
		/// </summary>
		TopHalfBlackCircle_2 = 0xf0bc,

		/// <summary>
		/// Bottom Half Black Circle.
		/// </summary>
		BottomHalfBlackCircle_2 = 0xf0bd,

		/// <summary>
		/// Black Medium Square.
		/// </summary>
		BlackMediumSquare_4 = 0xf0be,

		/// <summary>
		/// Black Medium Diamond.
		/// </summary>
		BlackMediumDiamond_4 = 0xf0bf,

		/// <summary>
		/// Black Pentagon.
		/// </summary>
		BlackPentagon_2 = 0xf0c0,

		/// <summary>
		/// Turned Black Pentagon.
		/// </summary>
		TurnedBlackPentagon_2 = 0xf0c1,

		/// <summary>
		/// Horizontal Black Hexagon.
		/// </summary>
		HorizontalBlackHexagon_2 = 0xf0c2,

		/// <summary>
		/// Black Hexagon.
		/// </summary>
		BlackHexagon_2 = 0xf0c3,

		/// <summary>
		/// Horizontal Black Octagon.
		/// </summary>
		HorizontalBlackOctagon_2 = 0xf0c4,

		/// <summary>
		/// Black Octagon.
		/// </summary>
		BlackOctagon_2 = 0xf0c5,

		/// <summary>
		/// Thin Greek Cross.
		/// </summary>
		ThinGreekCross_2 = 0xf0c6,

		/// <summary>
		/// Light Greek Cross.
		/// </summary>
		LightGreekCross_2 = 0xf0c7,

		/// <summary>
		/// Medium Greek Cross.
		/// </summary>
		MediumGreekCross_2 = 0xf0c8,

		/// <summary>
		/// Bold Greek Cross.
		/// </summary>
		BoldGreekCross_2 = 0xf0c9,

		/// <summary>
		/// Very Bold Greek Cross.
		/// </summary>
		VeryBoldGreekCross_2 = 0xf0ca,

		/// <summary>
		/// Very Heavy Greek Cross.
		/// </summary>
		VeryHeavyGreekCross_2 = 0xf0cb,

		/// <summary>
		/// Extremely Heavy Greek Cross.
		/// </summary>
		ExtremelyHeavyGreekCross_2 = 0xf0cc,

		/// <summary>
		/// Thin Saltire.
		/// </summary>
		ThinSaltire_2 = 0xf0cd,

		/// <summary>
		/// Light Saltire.
		/// </summary>
		LightSaltire_2 = 0xf0ce,

		/// <summary>
		/// Medium Saltire.
		/// </summary>
		MediumSaltire_2 = 0xf0cf,

		/// <summary>
		/// Bold Saltire.
		/// </summary>
		BoldSaltire_2 = 0xf0d0,

		/// <summary>
		/// Heavy Saltire.
		/// </summary>
		HeavySaltire_2 = 0xf0d1,

		/// <summary>
		/// Very Heavy Saltire.
		/// </summary>
		VeryHeavySaltire_2 = 0xf0d2,

		/// <summary>
		/// Extremely Heavy Saltire.
		/// </summary>
		ExtremelyHeavySaltire_2 = 0xf0d3,

		/// <summary>
		/// Light Five Spoked Asterisk.
		/// </summary>
		LightFiveSpokedAsterisk_2 = 0xf0d4,

		/// <summary>
		/// Medium Five Spoked Asterisk.
		/// </summary>
		MediumFiveSpokedAsterisk_2 = 0xf0d5,

		/// <summary>
		/// Bold Five Spoked Asterisk.
		/// </summary>
		BoldFiveSpokedAsterisk_2 = 0xf0d6,

		/// <summary>
		/// Heavy Five Spoked Asterisk.
		/// </summary>
		HeavyFiveSpokedAsterisk_2 = 0xf0d7,

		/// <summary>
		/// Very Heavy Five Spoked Asterisk.
		/// </summary>
		VeryHeavyFiveSpokedAsterisk_2 = 0xf0d8,

		/// <summary>
		/// Extremely Heavy Five Spoked Asterisk.
		/// </summary>
		ExtremelyHeavyFiveSpokedAsterisk_2 = 0xf0d9,

		/// <summary>
		/// Light Six Spoked Asterisk.
		/// </summary>
		LightSixSpokedAsterisk_2 = 0xf0da,

		/// <summary>
		/// Medium Six Spoked Asterisk.
		/// </summary>
		MediumSixSpokedAsterisk_2 = 0xf0db,

		/// <summary>
		/// Bold Six Spoked Asterisk.
		/// </summary>
		BoldSixSpokedAsterisk_2 = 0xf0dc,

		/// <summary>
		/// Heavy Six Spoked Asterisk.
		/// </summary>
		HeavySixSpokedAsterisk_2 = 0xf0dd,

		/// <summary>
		/// Very Heavy Six Spoked Asterisk.
		/// </summary>
		VeryHeavySixSpokedAsterisk_2 = 0xf0de,

		/// <summary>
		/// Extremely Heavy Six Spoked Asterisk.
		/// </summary>
		ExtremelyHeavySixSpokedAsterisk_2 = 0xf0df,

		/// <summary>
		/// Light Eight Spoked Asterisk.
		/// </summary>
		LightEightSpokedAsterisk_2 = 0xf0e0,

		/// <summary>
		/// Medium Eight Spoked Asterisk.
		/// </summary>
		MediumEightSpokedAsterisk_2 = 0xf0e1,

		/// <summary>
		/// Bold Eight Spoked Asterisk.
		/// </summary>
		BoldEightSpokedAsterisk_2 = 0xf0e2,

		/// <summary>
		/// Heavy Eight Spoked Asterisk.
		/// </summary>
		HeavyEightSpokedAsterisk_2 = 0xf0e3,

		/// <summary>
		/// Very Heavy Eight Spoked Asterisk.
		/// </summary>
		VeryHeavyEightSpokedAsterisk_2 = 0xf0e4,

		/// <summary>
		/// Light Three Pointed Black Star.
		/// </summary>
		LightThreePointedBlackStar_2 = 0xf0e5,

		/// <summary>
		/// Three Pointed Black Star.
		/// </summary>
		ThreePointedBlackStar_2 = 0xf0e6,

		/// <summary>
		/// Light Four Pointed Black Star.
		/// </summary>
		LightFourPointedBlackStar_2 = 0xf0e7,

		/// <summary>
		/// Black Four Pointed Star.
		/// </summary>
		BlackFourPointedStar_2 = 0xf0e8,

		/// <summary>
		/// Light Five Pointed Black Star.
		/// </summary>
		LightFivePointedBlackStar_2 = 0xf0e9,

		/// <summary>
		/// Black Star.
		/// </summary>
		BlackStar_2 = 0xf0ea,

		/// <summary>
		/// Six Pointed Black Star.
		/// </summary>
		SixPointedBlackStar_2 = 0xf0eb,

		/// <summary>
		/// Medium Six Pointed Black Star.
		/// </summary>
		MediumSixPointedBlackStar_2 = 0xf0ec,

		/// <summary>
		/// Eight Pointed Rectilinear Black Star.
		/// </summary>
		EightPointedRectilinearBlackStar_2 = 0xf0ed,

		/// <summary>
		/// Heavy Eight Pointed Black Star.
		/// </summary>
		HeavyEightPointedBlackStar_2 = 0xf0ee,

		/// <summary>
		/// Light Twelve Pointed Black Star.
		/// </summary>
		LightTwelvePointedBlackStar_2 = 0xf0ef,

		/// <summary>
		/// Twelve Pointed Black Star.
		/// </summary>
		TwelvePointedBlackStar_2 = 0xf0f0,

		/// <summary>
		/// Medium Three Pointed Pinwheel Star.
		/// </summary>
		MediumThreePointedPinwheelStar_2 = 0xf0f1,

		/// <summary>
		/// Medium Four Pointed Pinwheel Star.
		/// </summary>
		MediumFourPointedPinwheelStar_2 = 0xf0f2,

		/// <summary>
		/// Pinwheel Star.
		/// </summary>
		PinwheelStar_2 = 0xf0f3,

		/// <summary>
		/// Six Pointed Pinwheel Star.
		/// </summary>
		SixPointedPinwheelStar_2 = 0xf0f4,

		/// <summary>
		/// Heavy Twelve Pointed Pinwheel Star.
		/// </summary>
		HeavyTwelvePointedPinwheelStar_2 = 0xf0f5,

		/// <summary>
		/// Light Four Pointed Black Cusp.
		/// </summary>
		LightFourPointedBlackCusp_2 = 0xf0f6,

		/// <summary>
		/// Rotated Light Four Pointed Black Cusp.
		/// </summary>
		RotatedLightFourPointedBlackCusp_2 = 0xf0f7,

		/// <summary>
		/// Reference Mark.
		/// </summary>
		ReferenceMark_2 = 0xf0f8,

		/// <summary>
		/// Asterism.
		/// </summary>
		Asterism_2 = 0xf0f9
	}

	/// <summary>
	/// Wingdings2Glyph Enums.
	/// </summary>
	public static partial class Wingdings2GlyphResource
	{
		/// <summary>
		/// Device Control Four.
		/// </summary>
		public const string DeviceControlFour = "\u0014";

		/// <summary>
		/// Lower Left Ballpoint Pen.
		/// </summary>
		public const string LowerLeftBallpointPen = "\u0021";

		/// <summary>
		/// Lower Left Fountain Pen.
		/// </summary>
		public const string LowerLeftFountainPen = "\u0022";

		/// <summary>
		/// Lower Left Paintbrush.
		/// </summary>
		public const string LowerLeftPaintbrush = "\u0023";

		/// <summary>
		/// Lower Left Crayon.
		/// </summary>
		public const string LowerLeftCrayon = "\u0024";

		/// <summary>
		/// White Scissors.
		/// </summary>
		public const string WhiteScissors = "\u0025";

		/// <summary>
		/// Black Safety Scissors.
		/// </summary>
		public const string BlackSafetyScissors = "\u0026";

		/// <summary>
		/// White Touchtone Telephone.
		/// </summary>
		public const string WhiteTouchtoneTelephone = "\u0027";

		/// <summary>
		/// Right Hand Telephone Receiver.
		/// </summary>
		public const string RightHandTelephoneReceiver = "\u0028";

		/// <summary>
		/// Empty Note.
		/// </summary>
		public const string EmptyNote = "\u0029";

		/// <summary>
		/// Empty Note Page.
		/// </summary>
		public const string EmptyNotePage = "\u002a";

		/// <summary>
		/// Empty Note Pad.
		/// </summary>
		public const string EmptyNotePad = "\u002b";

		/// <summary>
		/// Note.
		/// </summary>
		public const string Note = "\u002c";

		/// <summary>
		/// Note Page.
		/// </summary>
		public const string NotePage = "\u002d";

		/// <summary>
		/// Note Pad.
		/// </summary>
		public const string NotePad = "\u002e";

		/// <summary>
		/// Empty Document.
		/// </summary>
		public const string EmptyDocument = "\u002f";

		/// <summary>
		/// Empty Page.
		/// </summary>
		public const string EmptyPage = "\u0030";

		/// <summary>
		/// Empty Pages.
		/// </summary>
		public const string EmptyPages = "\u0031";

		/// <summary>
		/// Clipboard.
		/// </summary>
		public const string Clipboard = "\u0032";

		/// <summary>
		/// Wastebasket.
		/// </summary>
		public const string Wastebasket = "\u0033";

		/// <summary>
		/// Desktop Window.
		/// </summary>
		public const string DesktopWindow = "\u0034";

		/// <summary>
		/// Screen.
		/// </summary>
		public const string Screen = "\u0035";

		/// <summary>
		/// Printer Icon.
		/// </summary>
		public const string PrinterIcon = "\u0036";

		/// <summary>
		/// Fax Icon.
		/// </summary>
		public const string FaxIcon = "\u0037";

		/// <summary>
		/// Optical Disc Icon.
		/// </summary>
		public const string OpticalDiscIcon = "\u0038";

		/// <summary>
		/// Tape Cartridge.
		/// </summary>
		public const string TapeCartridge = "\u0039";

		/// <summary>
		/// One Button Mouse.
		/// </summary>
		public const string OneButtonMouse = "\u003a";

		/// <summary>
		/// Three Button Mouse.
		/// </summary>
		public const string ThreeButtonMouse = "\u003b";

		/// <summary>
		/// Reversed Thumbs Up Sign.
		/// </summary>
		public const string ReversedThumbsUpSign = "\u003c";

		/// <summary>
		/// Reversed Thumbs Down Sign.
		/// </summary>
		public const string ReversedThumbsDownSign = "\u003d";

		/// <summary>
		/// Sideways White Left Pointing Index.
		/// </summary>
		public const string SidewaysWhiteLeftPointingIndex = "\u003e";

		/// <summary>
		/// Sideways White Right Pointing Index.
		/// </summary>
		public const string SidewaysWhiteRightPointingIndex = "\u003f";

		/// <summary>
		/// Sideways Black Left Pointing Index.
		/// </summary>
		public const string SidewaysBlackLeftPointingIndex = "\u0040";

		/// <summary>
		/// Sideways Black Right Pointing Index.
		/// </summary>
		public const string SidewaysBlackRightPointingIndex = "\u0041";

		/// <summary>
		/// White Left Pointing Backhand Index.
		/// </summary>
		public const string WhiteLeftPointingBackhandIndex = "\u0042";

		/// <summary>
		/// White Right Pointing Backhand Index.
		/// </summary>
		public const string WhiteRightPointingBackhandIndex = "\u0043";

		/// <summary>
		/// Black Left Pointing Backhand Index.
		/// </summary>
		public const string BlackLeftPointingBackhandIndex = "\u0044";

		/// <summary>
		/// Black Right Pointing Backhand Index.
		/// </summary>
		public const string BlackRightPointingBackhandIndex = "\u0045";

		/// <summary>
		/// Sideways White Up Pointing Index.
		/// </summary>
		public const string SidewaysWhiteUpPointingIndex = "\u0046";

		/// <summary>
		/// Sideways White Down Pointing Index.
		/// </summary>
		public const string SidewaysWhiteDownPointingIndex = "\u0047";

		/// <summary>
		/// Sideways Black Up Pointing Index.
		/// </summary>
		public const string SidewaysBlackUpPointingIndex = "\u0048";

		/// <summary>
		/// Sideways Black Down Pointing Index.
		/// </summary>
		public const string SidewaysBlackDownPointingIndex = "\u0049";

		/// <summary>
		/// White Up Pointing Backhand Index.
		/// </summary>
		public const string WhiteUpPointingBackhandIndex = "\u004a";

		/// <summary>
		/// White Down Pointing Backhand Index.
		/// </summary>
		public const string WhiteDownPointingBackhandIndex = "\u004b";

		/// <summary>
		/// Black Up Pointing Backhand Index.
		/// </summary>
		public const string BlackUpPointingBackhandIndex = "\u004c";

		/// <summary>
		/// Black Down Pointing Backhand Index.
		/// </summary>
		public const string BlackDownPointingBackhandIndex = "\u004d";

		/// <summary>
		/// Reversed Raised Hand With Fingers Splayed.
		/// </summary>
		public const string ReversedRaisedHandWithFingersSplayed = "\u004e";

		/// <summary>
		/// Ballot Script X.
		/// </summary>
		public const string BallotScriptX = "\u004f";

		/// <summary>
		/// Check Mark.
		/// </summary>
		public const string CheckMark = "\u0050";

		/// <summary>
		/// Ballot Box With Script X.
		/// </summary>
		public const string BallotBoxWithScriptX = "\u0051";

		/// <summary>
		/// Ballot Box With Check.
		/// </summary>
		public const string BallotBoxWithCheck = "\u0052";

		/// <summary>
		/// Ballot Box With X.
		/// </summary>
		public const string BallotBoxWithX = "\u0053";

		/// <summary>
		/// Ballot Box With X.
		/// </summary>
		public const string BallotBoxWithX_2 = "\u0054";

		/// <summary>
		/// Circled X.
		/// </summary>
		public const string CircledX = "\u0055";

		/// <summary>
		/// Circled Bold X.
		/// </summary>
		public const string CircledBoldX = "\u0056";

		/// <summary>
		/// Circled Reverse Solidus.
		/// </summary>
		public const string CircledReverseSolidus = "\u0057";

		/// <summary>
		/// Circled Reverse Solidus.
		/// </summary>
		public const string CircledReverseSolidus_2 = "\u0058";

		/// <summary>
		/// Heavy Script Ligature Et Ornament.
		/// </summary>
		public const string HeavyScriptLigatureEtOrnament = "\u0059";

		/// <summary>
		/// Heavy Ampersand Ornament.
		/// </summary>
		public const string HeavyAmpersandOrnament = "\u005a";

		/// <summary>
		/// Ligature Open Et Ornament.
		/// </summary>
		public const string LigatureOpenEtOrnament = "\u005b";

		/// <summary>
		/// Heavy Ligature Open Et Ornament.
		/// </summary>
		public const string HeavyLigatureOpenEtOrnament = "\u005c";

		/// <summary>
		/// Interrobang.
		/// </summary>
		public const string Interrobang = "\u005d";

		/// <summary>
		/// Heavy Interrobang Ornament.
		/// </summary>
		public const string HeavyInterrobangOrnament = "\u005e";

		/// <summary>
		/// Sans-Serif Interrobang Ornament.
		/// </summary>
		public const string SansSerifInterrobangOrnament = "\u005f";

		/// <summary>
		/// Heavy Sans-Serif Interrobang Ornament.
		/// </summary>
		public const string HeavySansSerifInterrobangOrnament = "\u0060";

		/// <summary>
		/// Heavy North East Pointing Bud.
		/// </summary>
		public const string HeavyNorthEastPointingBud = "\u0061";

		/// <summary>
		/// Heavy North West Pointing Bud.
		/// </summary>
		public const string HeavyNorthWestPointingBud = "\u0062";

		/// <summary>
		/// Heavy South West Pointing Bud.
		/// </summary>
		public const string HeavySouthWestPointingBud = "\u0063";

		/// <summary>
		/// Heavy South East Pointing Bud.
		/// </summary>
		public const string HeavySouthEastPointingBud = "\u0064";

		/// <summary>
		/// North East Pointing Vine Leaf.
		/// </summary>
		public const string NorthEastPointingVineLeaf = "\u0065";

		/// <summary>
		/// North West Pointing Vine Leaf.
		/// </summary>
		public const string NorthWestPointingVineLeaf = "\u0066";

		/// <summary>
		/// South West Pointing Vine Leaf.
		/// </summary>
		public const string SouthWestPointingVineLeaf = "\u0067";

		/// <summary>
		/// South East Pointing Vine Leaf.
		/// </summary>
		public const string SouthEastPointingVineLeaf = "\u0068";

		/// <summary>
		/// Circled Digit Zero.
		/// </summary>
		public const string CircledDigitZero = "\u0069";

		/// <summary>
		/// Circled Digit One.
		/// </summary>
		public const string CircledDigitOne = "\u006a";

		/// <summary>
		/// Circled Digit Two.
		/// </summary>
		public const string CircledDigitTwo = "\u006b";

		/// <summary>
		/// Circled Digit Three.
		/// </summary>
		public const string CircledDigitThree = "\u006c";

		/// <summary>
		/// Circled Digit Four.
		/// </summary>
		public const string CircledDigitFour = "\u006d";

		/// <summary>
		/// Circled Digit Five.
		/// </summary>
		public const string CircledDigitFive = "\u006e";

		/// <summary>
		/// Circled Digit Six.
		/// </summary>
		public const string CircledDigitSix = "\u006f";

		/// <summary>
		/// Circled Digit Seven.
		/// </summary>
		public const string CircledDigitSeven = "\u0070";

		/// <summary>
		/// Circled Digit Eight.
		/// </summary>
		public const string CircledDigitEight = "\u0071";

		/// <summary>
		/// Circled Digit Nine.
		/// </summary>
		public const string CircledDigitNine = "\u0072";

		/// <summary>
		/// Circled Number Ten.
		/// </summary>
		public const string CircledNumberTen = "\u0073";

		/// <summary>
		/// Negative Circled Digit Zero.
		/// </summary>
		public const string NegativeCircledDigitZero = "\u0074";

		/// <summary>
		/// Dingbat Negative Circled Digit One.
		/// </summary>
		public const string DingbatNegativeCircledDigitOne = "\u0075";

		/// <summary>
		/// Dingbat Negative Circled Digit Two.
		/// </summary>
		public const string DingbatNegativeCircledDigitTwo = "\u0076";

		/// <summary>
		/// Dingbat Negative Circled Digit Three.
		/// </summary>
		public const string DingbatNegativeCircledDigitThree = "\u0077";

		/// <summary>
		/// Dingbat Negative Circled Digit Four.
		/// </summary>
		public const string DingbatNegativeCircledDigitFour = "\u0078";

		/// <summary>
		/// Dingbat Negative Circled Digit Five.
		/// </summary>
		public const string DingbatNegativeCircledDigitFive = "\u0079";

		/// <summary>
		/// Dingbat Negative Circled Digit Six.
		/// </summary>
		public const string DingbatNegativeCircledDigitSix = "\u007a";

		/// <summary>
		/// Dingbat Negative Circled Digit Seven.
		/// </summary>
		public const string DingbatNegativeCircledDigitSeven = "\u007b";

		/// <summary>
		/// Dingbat Negative Circled Digit Eight.
		/// </summary>
		public const string DingbatNegativeCircledDigitEight = "\u007c";

		/// <summary>
		/// Dingbat Negative Circled Digit Nine.
		/// </summary>
		public const string DingbatNegativeCircledDigitNine = "\u007d";

		/// <summary>
		/// Dingbat Negative Circled Number Ten.
		/// </summary>
		public const string DingbatNegativeCircledNumberTen = "\u007e";

		/// <summary>
		/// Sun.
		/// </summary>
		public const string Sun = "\u0080";

		/// <summary>
		/// Full Moon Symbol.
		/// </summary>
		public const string FullMoonSymbol = "\u0081";

		/// <summary>
		/// First Quarter Moon.
		/// </summary>
		public const string FirstQuarterMoon = "\u0082";

		/// <summary>
		/// Last Quarter Moon.
		/// </summary>
		public const string LastQuarterMoon = "\u0083";

		/// <summary>
		/// Capitulum.
		/// </summary>
		public const string Capitulum = "\u0084";

		/// <summary>
		/// Latin Cross.
		/// </summary>
		public const string LatinCross = "\u0085";

		/// <summary>
		/// Heavy Latin Cross.
		/// </summary>
		public const string HeavyLatinCross = "\u0086";

		/// <summary>
		/// Clock Face One-Thirty.
		/// </summary>
		public const string ClockFaceOneThirty = "\u0087";

		/// <summary>
		/// Clock Face Two-Thirty.
		/// </summary>
		public const string ClockFaceTwoThirty = "\u0088";

		/// <summary>
		/// Clock Face Three-Thirty.
		/// </summary>
		public const string ClockFaceThreeThirty = "\u0089";

		/// <summary>
		/// Clock Face Four-Thirty.
		/// </summary>
		public const string ClockFaceFourThirty = "\u008a";

		/// <summary>
		/// Clock Face Five-Thirty.
		/// </summary>
		public const string ClockFaceFiveThirty = "\u008b";

		/// <summary>
		/// Clock Face Six-Thirty.
		/// </summary>
		public const string ClockFaceSixThirty = "\u008c";

		/// <summary>
		/// Clock Face Seven-Thirty.
		/// </summary>
		public const string ClockFaceSevenThirty = "\u008d";

		/// <summary>
		/// Clock Face Eight-Thirty.
		/// </summary>
		public const string ClockFaceEightThirty = "\u008e";

		/// <summary>
		/// Clock Face Nine-Thirty.
		/// </summary>
		public const string ClockFaceNineThirty = "\u008f";

		/// <summary>
		/// Clock Face Ten-Thirty.
		/// </summary>
		public const string ClockFaceTenThirty = "\u0090";

		/// <summary>
		/// Clock Face Eleven-Thirty.
		/// </summary>
		public const string ClockFaceElevenThirty = "\u0091";

		/// <summary>
		/// Clock Face Twelve-Thirty.
		/// </summary>
		public const string ClockFaceTwelveThirty = "\u0092";

		/// <summary>
		/// Hollow Quilt Square Ornament.
		/// </summary>
		public const string HollowQuiltSquareOrnament = "\u0093";

		/// <summary>
		/// Hollow Quilt Square Ornament In Black Square.
		/// </summary>
		public const string HollowQuiltSquareOrnamentInBlackSquare = "\u0094";

		/// <summary>
		/// Bullet.
		/// </summary>
		public const string Bullet = "\u0095";

		/// <summary>
		/// Black Circle.
		/// </summary>
		public const string BlackCircle = "\u0096";

		/// <summary>
		/// Medium Black Circle.
		/// </summary>
		public const string MediumBlackCircle = "\u0097";

		/// <summary>
		/// Black Large Circle.
		/// </summary>
		public const string BlackLargeCircle = "\u0098";

		/// <summary>
		/// Medium Bold White Circle.
		/// </summary>
		public const string MediumBoldWhiteCircle = "\u0099";

		/// <summary>
		/// Bold White Circle.
		/// </summary>
		public const string BoldWhiteCircle = "\u009a";

		/// <summary>
		/// Heavy White Circle.
		/// </summary>
		public const string HeavyWhiteCircle = "\u009b";

		/// <summary>
		/// Very Heavy White Circle.
		/// </summary>
		public const string VeryHeavyWhiteCircle = "\u009c";

		/// <summary>
		/// White Circle Containing Black Small Circle.
		/// </summary>
		public const string WhiteCircleContainingBlackSmallCircle = "\u009d";

		/// <summary>
		/// Circled Bullet.
		/// </summary>
		public const string CircledBullet = "\u009e";

		/// <summary>
		/// Black Medium Small Square.
		/// </summary>
		public const string BlackMediumSmallSquare = "\u009f";

		/// <summary>
		/// Black Square.
		/// </summary>
		public const string BlackSquare = "\u00a0";

		/// <summary>
		/// Black Medium Square.
		/// </summary>
		public const string BlackMediumSquare = "\u00a1";

		/// <summary>
		/// Black Large Square.
		/// </summary>
		public const string BlackLargeSquare = "\u00a2";

		/// <summary>
		/// White Large Square.
		/// </summary>
		public const string WhiteLargeSquare = "\u00a3";

		/// <summary>
		/// Heavy White Square.
		/// </summary>
		public const string HeavyWhiteSquare = "\u00a4";

		/// <summary>
		/// Very Heavy White Square.
		/// </summary>
		public const string VeryHeavyWhiteSquare = "\u00a5";

		/// <summary>
		/// Extremely Heavy White Square.
		/// </summary>
		public const string ExtremelyHeavyWhiteSquare = "\u00a6";

		/// <summary>
		/// White Square Containing Black Very Small Square.
		/// </summary>
		public const string WhiteSquareContainingBlackVerySmallSquare = "\u00a7";

		/// <summary>
		/// White Square Containing Black Small Square.
		/// </summary>
		public const string WhiteSquareContainingBlackSmallSquare = "\u00a8";

		/// <summary>
		/// White Square Containing Black Medium Square.
		/// </summary>
		public const string WhiteSquareContainingBlackMediumSquare = "\u00a9";

		/// <summary>
		/// Square Target.
		/// </summary>
		public const string SquareTarget = "\u00aa";

		/// <summary>
		/// Black Tiny Diamond.
		/// </summary>
		public const string BlackTinyDiamond = "\u00ab";

		/// <summary>
		/// Black Small Diamond.
		/// </summary>
		public const string BlackSmallDiamond = "\u00ac";

		/// <summary>
		/// Black Medium Diamond.
		/// </summary>
		public const string BlackMediumDiamond = "\u00ad";

		/// <summary>
		/// Black Diamond.
		/// </summary>
		public const string BlackDiamond = "\u00ae";

		/// <summary>
		/// White Diamond.
		/// </summary>
		public const string WhiteDiamond = "\u00af";

		/// <summary>
		/// White Diamond Containing Black Very Small Diamond.
		/// </summary>
		public const string WhiteDiamondContainingBlackVerySmallDiamond = "\u00b0";

		/// <summary>
		/// White Diamond Containing Black Small Diamond.
		/// </summary>
		public const string WhiteDiamondContainingBlackSmallDiamond = "\u00b1";

		/// <summary>
		/// White Diamond Containing Black Medium Diamond.
		/// </summary>
		public const string WhiteDiamondContainingBlackMediumDiamond = "\u00b2";

		/// <summary>
		/// Diamond Target.
		/// </summary>
		public const string DiamondTarget = "\u00b3";

		/// <summary>
		/// Black Tiny Lozenge.
		/// </summary>
		public const string BlackTinyLozenge = "\u00b4";

		/// <summary>
		/// Black Small Lozenge.
		/// </summary>
		public const string BlackSmallLozenge = "\u00b5";

		/// <summary>
		/// Black Medium Lozenge.
		/// </summary>
		public const string BlackMediumLozenge = "\u00b6";

		/// <summary>
		/// Black Lozenge.
		/// </summary>
		public const string BlackLozenge = "\u00b7";

		/// <summary>
		/// Lozenge.
		/// </summary>
		public const string Lozenge = "\u00b8";

		/// <summary>
		/// White Lozenge Containing Black Small Lozenge.
		/// </summary>
		public const string WhiteLozengeContainingBlackSmallLozenge = "\u00b9";

		/// <summary>
		/// Left Half Black Circle.
		/// </summary>
		public const string LeftHalfBlackCircle = "\u00ba";

		/// <summary>
		/// Right Half Black Circle.
		/// </summary>
		public const string RightHalfBlackCircle = "\u00bb";

		/// <summary>
		/// Top Half Black Circle.
		/// </summary>
		public const string TopHalfBlackCircle = "\u00bc";

		/// <summary>
		/// Bottom Half Black Circle.
		/// </summary>
		public const string BottomHalfBlackCircle = "\u00bd";

		/// <summary>
		/// Black Medium Square.
		/// </summary>
		public const string BlackMediumSquare_2 = "\u00be";

		/// <summary>
		/// Black Medium Diamond.
		/// </summary>
		public const string BlackMediumDiamond_2 = "\u00bf";

		/// <summary>
		/// Black Pentagon.
		/// </summary>
		public const string BlackPentagon = "\u00c0";

		/// <summary>
		/// Turned Black Pentagon.
		/// </summary>
		public const string TurnedBlackPentagon = "\u00c1";

		/// <summary>
		/// Horizontal Black Hexagon.
		/// </summary>
		public const string HorizontalBlackHexagon = "\u00c2";

		/// <summary>
		/// Black Hexagon.
		/// </summary>
		public const string BlackHexagon = "\u00c3";

		/// <summary>
		/// Horizontal Black Octagon.
		/// </summary>
		public const string HorizontalBlackOctagon = "\u00c4";

		/// <summary>
		/// Black Octagon.
		/// </summary>
		public const string BlackOctagon = "\u00c5";

		/// <summary>
		/// Thin Greek Cross.
		/// </summary>
		public const string ThinGreekCross = "\u00c6";

		/// <summary>
		/// Light Greek Cross.
		/// </summary>
		public const string LightGreekCross = "\u00c7";

		/// <summary>
		/// Medium Greek Cross.
		/// </summary>
		public const string MediumGreekCross = "\u00c8";

		/// <summary>
		/// Bold Greek Cross.
		/// </summary>
		public const string BoldGreekCross = "\u00c9";

		/// <summary>
		/// Very Bold Greek Cross.
		/// </summary>
		public const string VeryBoldGreekCross = "\u00ca";

		/// <summary>
		/// Very Heavy Greek Cross.
		/// </summary>
		public const string VeryHeavyGreekCross = "\u00cb";

		/// <summary>
		/// Extremely Heavy Greek Cross.
		/// </summary>
		public const string ExtremelyHeavyGreekCross = "\u00cc";

		/// <summary>
		/// Thin Saltire.
		/// </summary>
		public const string ThinSaltire = "\u00cd";

		/// <summary>
		/// Light Saltire.
		/// </summary>
		public const string LightSaltire = "\u00ce";

		/// <summary>
		/// Medium Saltire.
		/// </summary>
		public const string MediumSaltire = "\u00cf";

		/// <summary>
		/// Bold Saltire.
		/// </summary>
		public const string BoldSaltire = "\u00d0";

		/// <summary>
		/// Heavy Saltire.
		/// </summary>
		public const string HeavySaltire = "\u00d1";

		/// <summary>
		/// Very Heavy Saltire.
		/// </summary>
		public const string VeryHeavySaltire = "\u00d2";

		/// <summary>
		/// Extremely Heavy Saltire.
		/// </summary>
		public const string ExtremelyHeavySaltire = "\u00d3";

		/// <summary>
		/// Light Five Spoked Asterisk.
		/// </summary>
		public const string LightFiveSpokedAsterisk = "\u00d4";

		/// <summary>
		/// Medium Five Spoked Asterisk.
		/// </summary>
		public const string MediumFiveSpokedAsterisk = "\u00d5";

		/// <summary>
		/// Bold Five Spoked Asterisk.
		/// </summary>
		public const string BoldFiveSpokedAsterisk = "\u00d6";

		/// <summary>
		/// Heavy Five Spoked Asterisk.
		/// </summary>
		public const string HeavyFiveSpokedAsterisk = "\u00d7";

		/// <summary>
		/// Very Heavy Five Spoked Asterisk.
		/// </summary>
		public const string VeryHeavyFiveSpokedAsterisk = "\u00d8";

		/// <summary>
		/// Extremely Heavy Five Spoked Asterisk.
		/// </summary>
		public const string ExtremelyHeavyFiveSpokedAsterisk = "\u00d9";

		/// <summary>
		/// Light Six Spoked Asterisk.
		/// </summary>
		public const string LightSixSpokedAsterisk = "\u00da";

		/// <summary>
		/// Medium Six Spoked Asterisk.
		/// </summary>
		public const string MediumSixSpokedAsterisk = "\u00db";

		/// <summary>
		/// Bold Six Spoked Asterisk.
		/// </summary>
		public const string BoldSixSpokedAsterisk = "\u00dc";

		/// <summary>
		/// Heavy Six Spoked Asterisk.
		/// </summary>
		public const string HeavySixSpokedAsterisk = "\u00dd";

		/// <summary>
		/// Very Heavy Six Spoked Asterisk.
		/// </summary>
		public const string VeryHeavySixSpokedAsterisk = "\u00de";

		/// <summary>
		/// Extremely Heavy Six Spoked Asterisk.
		/// </summary>
		public const string ExtremelyHeavySixSpokedAsterisk = "\u00df";

		/// <summary>
		/// Light Eight Spoked Asterisk.
		/// </summary>
		public const string LightEightSpokedAsterisk = "\u00e0";

		/// <summary>
		/// Medium Eight Spoked Asterisk.
		/// </summary>
		public const string MediumEightSpokedAsterisk = "\u00e1";

		/// <summary>
		/// Bold Eight Spoked Asterisk.
		/// </summary>
		public const string BoldEightSpokedAsterisk = "\u00e2";

		/// <summary>
		/// Heavy Eight Spoked Asterisk.
		/// </summary>
		public const string HeavyEightSpokedAsterisk = "\u00e3";

		/// <summary>
		/// Very Heavy Eight Spoked Asterisk.
		/// </summary>
		public const string VeryHeavyEightSpokedAsterisk = "\u00e4";

		/// <summary>
		/// Light Three Pointed Black Star.
		/// </summary>
		public const string LightThreePointedBlackStar = "\u00e5";

		/// <summary>
		/// Three Pointed Black Star.
		/// </summary>
		public const string ThreePointedBlackStar = "\u00e6";

		/// <summary>
		/// Light Four Pointed Black Star.
		/// </summary>
		public const string LightFourPointedBlackStar = "\u00e7";

		/// <summary>
		/// Black Four Pointed Star.
		/// </summary>
		public const string BlackFourPointedStar = "\u00e8";

		/// <summary>
		/// Light Five Pointed Black Star.
		/// </summary>
		public const string LightFivePointedBlackStar = "\u00e9";

		/// <summary>
		/// Black Star.
		/// </summary>
		public const string BlackStar = "\u00ea";

		/// <summary>
		/// Six Pointed Black Star.
		/// </summary>
		public const string SixPointedBlackStar = "\u00eb";

		/// <summary>
		/// Medium Six Pointed Black Star.
		/// </summary>
		public const string MediumSixPointedBlackStar = "\u00ec";

		/// <summary>
		/// Eight Pointed Rectilinear Black Star.
		/// </summary>
		public const string EightPointedRectilinearBlackStar = "\u00ed";

		/// <summary>
		/// Heavy Eight Pointed Black Star.
		/// </summary>
		public const string HeavyEightPointedBlackStar = "\u00ee";

		/// <summary>
		/// Light Twelve Pointed Black Star.
		/// </summary>
		public const string LightTwelvePointedBlackStar = "\u00ef";

		/// <summary>
		/// Twelve Pointed Black Star.
		/// </summary>
		public const string TwelvePointedBlackStar = "\u00f0";

		/// <summary>
		/// Medium Three Pointed Pinwheel Star.
		/// </summary>
		public const string MediumThreePointedPinwheelStar = "\u00f1";

		/// <summary>
		/// Medium Four Pointed Pinwheel Star.
		/// </summary>
		public const string MediumFourPointedPinwheelStar = "\u00f2";

		/// <summary>
		/// Pinwheel Star.
		/// </summary>
		public const string PinwheelStar = "\u00f3";

		/// <summary>
		/// Six Pointed Pinwheel Star.
		/// </summary>
		public const string SixPointedPinwheelStar = "\u00f4";

		/// <summary>
		/// Heavy Twelve Pointed Pinwheel Star.
		/// </summary>
		public const string HeavyTwelvePointedPinwheelStar = "\u00f5";

		/// <summary>
		/// Light Four Pointed Black Cusp.
		/// </summary>
		public const string LightFourPointedBlackCusp = "\u00f6";

		/// <summary>
		/// Rotated Light Four Pointed Black Cusp.
		/// </summary>
		public const string RotatedLightFourPointedBlackCusp = "\u00f7";

		/// <summary>
		/// Reference Mark.
		/// </summary>
		public const string ReferenceMark = "\u00f8";

		/// <summary>
		/// Asterism.
		/// </summary>
		public const string Asterism = "\u00f9";

		/// <summary>
		/// Device Control Four.
		/// </summary>
		public const string DeviceControlFour_2 = "\uf014";

		/// <summary>
		/// Lower Left Ballpoint Pen.
		/// </summary>
		public const string LowerLeftBallpointPen_2 = "\uf021";

		/// <summary>
		/// Lower Left Fountain Pen.
		/// </summary>
		public const string LowerLeftFountainPen_2 = "\uf022";

		/// <summary>
		/// Lower Left Paintbrush.
		/// </summary>
		public const string LowerLeftPaintbrush_2 = "\uf023";

		/// <summary>
		/// Lower Left Crayon.
		/// </summary>
		public const string LowerLeftCrayon_2 = "\uf024";

		/// <summary>
		/// White Scissors.
		/// </summary>
		public const string WhiteScissors_2 = "\uf025";

		/// <summary>
		/// Black Safety Scissors.
		/// </summary>
		public const string BlackSafetyScissors_2 = "\uf026";

		/// <summary>
		/// White Touchtone Telephone.
		/// </summary>
		public const string WhiteTouchtoneTelephone_2 = "\uf027";

		/// <summary>
		/// Right Hand Telephone Receiver.
		/// </summary>
		public const string RightHandTelephoneReceiver_2 = "\uf028";

		/// <summary>
		/// Empty Note.
		/// </summary>
		public const string EmptyNote_2 = "\uf029";

		/// <summary>
		/// Empty Note Page.
		/// </summary>
		public const string EmptyNotePage_2 = "\uf02a";

		/// <summary>
		/// Empty Note Pad.
		/// </summary>
		public const string EmptyNotePad_2 = "\uf02b";

		/// <summary>
		/// Note.
		/// </summary>
		public const string Note_2 = "\uf02c";

		/// <summary>
		/// Note Page.
		/// </summary>
		public const string NotePage_2 = "\uf02d";

		/// <summary>
		/// Note Pad.
		/// </summary>
		public const string NotePad_2 = "\uf02e";

		/// <summary>
		/// Empty Document.
		/// </summary>
		public const string EmptyDocument_2 = "\uf02f";

		/// <summary>
		/// Empty Page.
		/// </summary>
		public const string EmptyPage_2 = "\uf030";

		/// <summary>
		/// Empty Pages.
		/// </summary>
		public const string EmptyPages_2 = "\uf031";

		/// <summary>
		/// Clipboard.
		/// </summary>
		public const string Clipboard_2 = "\uf032";

		/// <summary>
		/// Wastebasket.
		/// </summary>
		public const string Wastebasket_2 = "\uf033";

		/// <summary>
		/// Desktop Window.
		/// </summary>
		public const string DesktopWindow_2 = "\uf034";

		/// <summary>
		/// Screen.
		/// </summary>
		public const string Screen_2 = "\uf035";

		/// <summary>
		/// Printer Icon.
		/// </summary>
		public const string PrinterIcon_2 = "\uf036";

		/// <summary>
		/// Fax Icon.
		/// </summary>
		public const string FaxIcon_2 = "\uf037";

		/// <summary>
		/// Optical Disc Icon.
		/// </summary>
		public const string OpticalDiscIcon_2 = "\uf038";

		/// <summary>
		/// Tape Cartridge.
		/// </summary>
		public const string TapeCartridge_2 = "\uf039";

		/// <summary>
		/// One Button Mouse.
		/// </summary>
		public const string OneButtonMouse_2 = "\uf03a";

		/// <summary>
		/// Three Button Mouse.
		/// </summary>
		public const string ThreeButtonMouse_2 = "\uf03b";

		/// <summary>
		/// Reversed Thumbs Up Sign.
		/// </summary>
		public const string ReversedThumbsUpSign_2 = "\uf03c";

		/// <summary>
		/// Reversed Thumbs Down Sign.
		/// </summary>
		public const string ReversedThumbsDownSign_2 = "\uf03d";

		/// <summary>
		/// Sideways White Left Pointing Index.
		/// </summary>
		public const string SidewaysWhiteLeftPointingIndex_2 = "\uf03e";

		/// <summary>
		/// Sideways White Right Pointing Index.
		/// </summary>
		public const string SidewaysWhiteRightPointingIndex_2 = "\uf03f";

		/// <summary>
		/// Sideways Black Left Pointing Index.
		/// </summary>
		public const string SidewaysBlackLeftPointingIndex_2 = "\uf040";

		/// <summary>
		/// Sideways Black Right Pointing Index.
		/// </summary>
		public const string SidewaysBlackRightPointingIndex_2 = "\uf041";

		/// <summary>
		/// White Left Pointing Backhand Index.
		/// </summary>
		public const string WhiteLeftPointingBackhandIndex_2 = "\uf042";

		/// <summary>
		/// White Right Pointing Backhand Index.
		/// </summary>
		public const string WhiteRightPointingBackhandIndex_2 = "\uf043";

		/// <summary>
		/// Black Left Pointing Backhand Index.
		/// </summary>
		public const string BlackLeftPointingBackhandIndex_2 = "\uf044";

		/// <summary>
		/// Black Right Pointing Backhand Index.
		/// </summary>
		public const string BlackRightPointingBackhandIndex_2 = "\uf045";

		/// <summary>
		/// Sideways White Up Pointing Index.
		/// </summary>
		public const string SidewaysWhiteUpPointingIndex_2 = "\uf046";

		/// <summary>
		/// Sideways White Down Pointing Index.
		/// </summary>
		public const string SidewaysWhiteDownPointingIndex_2 = "\uf047";

		/// <summary>
		/// Sideways Black Up Pointing Index.
		/// </summary>
		public const string SidewaysBlackUpPointingIndex_2 = "\uf048";

		/// <summary>
		/// Sideways Black Down Pointing Index.
		/// </summary>
		public const string SidewaysBlackDownPointingIndex_2 = "\uf049";

		/// <summary>
		/// White Up Pointing Backhand Index.
		/// </summary>
		public const string WhiteUpPointingBackhandIndex_2 = "\uf04a";

		/// <summary>
		/// White Down Pointing Backhand Index.
		/// </summary>
		public const string WhiteDownPointingBackhandIndex_2 = "\uf04b";

		/// <summary>
		/// Black Up Pointing Backhand Index.
		/// </summary>
		public const string BlackUpPointingBackhandIndex_2 = "\uf04c";

		/// <summary>
		/// Black Down Pointing Backhand Index.
		/// </summary>
		public const string BlackDownPointingBackhandIndex_2 = "\uf04d";

		/// <summary>
		/// Reversed Raised Hand With Fingers Splayed.
		/// </summary>
		public const string ReversedRaisedHandWithFingersSplayed_2 = "\uf04e";

		/// <summary>
		/// Ballot Script X.
		/// </summary>
		public const string BallotScriptX_2 = "\uf04f";

		/// <summary>
		/// Check Mark.
		/// </summary>
		public const string CheckMark_2 = "\uf050";

		/// <summary>
		/// Ballot Box With Script X.
		/// </summary>
		public const string BallotBoxWithScriptX_2 = "\uf051";

		/// <summary>
		/// Ballot Box With Check.
		/// </summary>
		public const string BallotBoxWithCheck_2 = "\uf052";

		/// <summary>
		/// Ballot Box With X.
		/// </summary>
		public const string BallotBoxWithX_3 = "\uf053";

		/// <summary>
		/// Ballot Box With X.
		/// </summary>
		public const string BallotBoxWithX_4 = "\uf054";

		/// <summary>
		/// Circled X.
		/// </summary>
		public const string CircledX_2 = "\uf055";

		/// <summary>
		/// Circled Bold X.
		/// </summary>
		public const string CircledBoldX_2 = "\uf056";

		/// <summary>
		/// Circled Reverse Solidus.
		/// </summary>
		public const string CircledReverseSolidus_3 = "\uf057";

		/// <summary>
		/// Circled Reverse Solidus.
		/// </summary>
		public const string CircledReverseSolidus_4 = "\uf058";

		/// <summary>
		/// Heavy Script Ligature Et Ornament.
		/// </summary>
		public const string HeavyScriptLigatureEtOrnament_2 = "\uf059";

		/// <summary>
		/// Heavy Ampersand Ornament.
		/// </summary>
		public const string HeavyAmpersandOrnament_2 = "\uf05a";

		/// <summary>
		/// Ligature Open Et Ornament.
		/// </summary>
		public const string LigatureOpenEtOrnament_2 = "\uf05b";

		/// <summary>
		/// Heavy Ligature Open Et Ornament.
		/// </summary>
		public const string HeavyLigatureOpenEtOrnament_2 = "\uf05c";

		/// <summary>
		/// Interrobang.
		/// </summary>
		public const string Interrobang_2 = "\uf05d";

		/// <summary>
		/// Heavy Interrobang Ornament.
		/// </summary>
		public const string HeavyInterrobangOrnament_2 = "\uf05e";

		/// <summary>
		/// Sans-Serif Interrobang Ornament.
		/// </summary>
		public const string SansSerifInterrobangOrnament_2 = "\uf05f";

		/// <summary>
		/// Heavy Sans-Serif Interrobang Ornament.
		/// </summary>
		public const string HeavySansSerifInterrobangOrnament_2 = "\uf060";

		/// <summary>
		/// Heavy North East Pointing Bud.
		/// </summary>
		public const string HeavyNorthEastPointingBud_2 = "\uf061";

		/// <summary>
		/// Heavy North West Pointing Bud.
		/// </summary>
		public const string HeavyNorthWestPointingBud_2 = "\uf062";

		/// <summary>
		/// Heavy South West Pointing Bud.
		/// </summary>
		public const string HeavySouthWestPointingBud_2 = "\uf063";

		/// <summary>
		/// Heavy South East Pointing Bud.
		/// </summary>
		public const string HeavySouthEastPointingBud_2 = "\uf064";

		/// <summary>
		/// North East Pointing Vine Leaf.
		/// </summary>
		public const string NorthEastPointingVineLeaf_2 = "\uf065";

		/// <summary>
		/// North West Pointing Vine Leaf.
		/// </summary>
		public const string NorthWestPointingVineLeaf_2 = "\uf066";

		/// <summary>
		/// South West Pointing Vine Leaf.
		/// </summary>
		public const string SouthWestPointingVineLeaf_2 = "\uf067";

		/// <summary>
		/// South East Pointing Vine Leaf.
		/// </summary>
		public const string SouthEastPointingVineLeaf_2 = "\uf068";

		/// <summary>
		/// Circled Digit Zero.
		/// </summary>
		public const string CircledDigitZero_2 = "\uf069";

		/// <summary>
		/// Circled Digit One.
		/// </summary>
		public const string CircledDigitOne_2 = "\uf06a";

		/// <summary>
		/// Circled Digit Two.
		/// </summary>
		public const string CircledDigitTwo_2 = "\uf06b";

		/// <summary>
		/// Circled Digit Three.
		/// </summary>
		public const string CircledDigitThree_2 = "\uf06c";

		/// <summary>
		/// Circled Digit Four.
		/// </summary>
		public const string CircledDigitFour_2 = "\uf06d";

		/// <summary>
		/// Circled Digit Five.
		/// </summary>
		public const string CircledDigitFive_2 = "\uf06e";

		/// <summary>
		/// Circled Digit Six.
		/// </summary>
		public const string CircledDigitSix_2 = "\uf06f";

		/// <summary>
		/// Circled Digit Seven.
		/// </summary>
		public const string CircledDigitSeven_2 = "\uf070";

		/// <summary>
		/// Circled Digit Eight.
		/// </summary>
		public const string CircledDigitEight_2 = "\uf071";

		/// <summary>
		/// Circled Digit Nine.
		/// </summary>
		public const string CircledDigitNine_2 = "\uf072";

		/// <summary>
		/// Circled Number Ten.
		/// </summary>
		public const string CircledNumberTen_2 = "\uf073";

		/// <summary>
		/// Negative Circled Digit Zero.
		/// </summary>
		public const string NegativeCircledDigitZero_2 = "\uf074";

		/// <summary>
		/// Dingbat Negative Circled Digit One.
		/// </summary>
		public const string DingbatNegativeCircledDigitOne_2 = "\uf075";

		/// <summary>
		/// Dingbat Negative Circled Digit Two.
		/// </summary>
		public const string DingbatNegativeCircledDigitTwo_2 = "\uf076";

		/// <summary>
		/// Dingbat Negative Circled Digit Three.
		/// </summary>
		public const string DingbatNegativeCircledDigitThree_2 = "\uf077";

		/// <summary>
		/// Dingbat Negative Circled Digit Four.
		/// </summary>
		public const string DingbatNegativeCircledDigitFour_2 = "\uf078";

		/// <summary>
		/// Dingbat Negative Circled Digit Five.
		/// </summary>
		public const string DingbatNegativeCircledDigitFive_2 = "\uf079";

		/// <summary>
		/// Dingbat Negative Circled Digit Six.
		/// </summary>
		public const string DingbatNegativeCircledDigitSix_2 = "\uf07a";

		/// <summary>
		/// Dingbat Negative Circled Digit Seven.
		/// </summary>
		public const string DingbatNegativeCircledDigitSeven_2 = "\uf07b";

		/// <summary>
		/// Dingbat Negative Circled Digit Eight.
		/// </summary>
		public const string DingbatNegativeCircledDigitEight_2 = "\uf07c";

		/// <summary>
		/// Dingbat Negative Circled Digit Nine.
		/// </summary>
		public const string DingbatNegativeCircledDigitNine_2 = "\uf07d";

		/// <summary>
		/// Dingbat Negative Circled Number Ten.
		/// </summary>
		public const string DingbatNegativeCircledNumberTen_2 = "\uf07e";

		/// <summary>
		/// Sun.
		/// </summary>
		public const string Sun_2 = "\uf080";

		/// <summary>
		/// Full Moon Symbol.
		/// </summary>
		public const string FullMoonSymbol_2 = "\uf081";

		/// <summary>
		/// First Quarter Moon.
		/// </summary>
		public const string FirstQuarterMoon_2 = "\uf082";

		/// <summary>
		/// Last Quarter Moon.
		/// </summary>
		public const string LastQuarterMoon_2 = "\uf083";

		/// <summary>
		/// Capitulum.
		/// </summary>
		public const string Capitulum_2 = "\uf084";

		/// <summary>
		/// Latin Cross.
		/// </summary>
		public const string LatinCross_2 = "\uf085";

		/// <summary>
		/// Heavy Latin Cross.
		/// </summary>
		public const string HeavyLatinCross_2 = "\uf086";

		/// <summary>
		/// Clock Face One-Thirty.
		/// </summary>
		public const string ClockFaceOneThirty_2 = "\uf087";

		/// <summary>
		/// Clock Face Two-Thirty.
		/// </summary>
		public const string ClockFaceTwoThirty_2 = "\uf088";

		/// <summary>
		/// Clock Face Three-Thirty.
		/// </summary>
		public const string ClockFaceThreeThirty_2 = "\uf089";

		/// <summary>
		/// Clock Face Four-Thirty.
		/// </summary>
		public const string ClockFaceFourThirty_2 = "\uf08a";

		/// <summary>
		/// Clock Face Five-Thirty.
		/// </summary>
		public const string ClockFaceFiveThirty_2 = "\uf08b";

		/// <summary>
		/// Clock Face Six-Thirty.
		/// </summary>
		public const string ClockFaceSixThirty_2 = "\uf08c";

		/// <summary>
		/// Clock Face Seven-Thirty.
		/// </summary>
		public const string ClockFaceSevenThirty_2 = "\uf08d";

		/// <summary>
		/// Clock Face Eight-Thirty.
		/// </summary>
		public const string ClockFaceEightThirty_2 = "\uf08e";

		/// <summary>
		/// Clock Face Nine-Thirty.
		/// </summary>
		public const string ClockFaceNineThirty_2 = "\uf08f";

		/// <summary>
		/// Clock Face Ten-Thirty.
		/// </summary>
		public const string ClockFaceTenThirty_2 = "\uf090";

		/// <summary>
		/// Clock Face Eleven-Thirty.
		/// </summary>
		public const string ClockFaceElevenThirty_2 = "\uf091";

		/// <summary>
		/// Clock Face Twelve-Thirty.
		/// </summary>
		public const string ClockFaceTwelveThirty_2 = "\uf092";

		/// <summary>
		/// Hollow Quilt Square Ornament.
		/// </summary>
		public const string HollowQuiltSquareOrnament_2 = "\uf093";

		/// <summary>
		/// Hollow Quilt Square Ornament In Black Square.
		/// </summary>
		public const string HollowQuiltSquareOrnamentInBlackSquare_2 = "\uf094";

		/// <summary>
		/// Bullet.
		/// </summary>
		public const string Bullet_2 = "\uf095";

		/// <summary>
		/// Black Circle.
		/// </summary>
		public const string BlackCircle_2 = "\uf096";

		/// <summary>
		/// Medium Black Circle.
		/// </summary>
		public const string MediumBlackCircle_2 = "\uf097";

		/// <summary>
		/// Black Large Circle.
		/// </summary>
		public const string BlackLargeCircle_2 = "\uf098";

		/// <summary>
		/// Medium Bold White Circle.
		/// </summary>
		public const string MediumBoldWhiteCircle_2 = "\uf099";

		/// <summary>
		/// Bold White Circle.
		/// </summary>
		public const string BoldWhiteCircle_2 = "\uf09a";

		/// <summary>
		/// Heavy White Circle.
		/// </summary>
		public const string HeavyWhiteCircle_2 = "\uf09b";

		/// <summary>
		/// Very Heavy White Circle.
		/// </summary>
		public const string VeryHeavyWhiteCircle_2 = "\uf09c";

		/// <summary>
		/// White Circle Containing Black Small Circle.
		/// </summary>
		public const string WhiteCircleContainingBlackSmallCircle_2 = "\uf09d";

		/// <summary>
		/// Circled Bullet.
		/// </summary>
		public const string CircledBullet_2 = "\uf09e";

		/// <summary>
		/// Black Medium Small Square.
		/// </summary>
		public const string BlackMediumSmallSquare_2 = "\uf09f";

		/// <summary>
		/// Black Square.
		/// </summary>
		public const string BlackSquare_2 = "\uf0a0";

		/// <summary>
		/// Black Medium Square.
		/// </summary>
		public const string BlackMediumSquare_3 = "\uf0a1";

		/// <summary>
		/// Black Large Square.
		/// </summary>
		public const string BlackLargeSquare_2 = "\uf0a2";

		/// <summary>
		/// White Large Square.
		/// </summary>
		public const string WhiteLargeSquare_2 = "\uf0a3";

		/// <summary>
		/// Heavy White Square.
		/// </summary>
		public const string HeavyWhiteSquare_2 = "\uf0a4";

		/// <summary>
		/// Very Heavy White Square.
		/// </summary>
		public const string VeryHeavyWhiteSquare_2 = "\uf0a5";

		/// <summary>
		/// Extremely Heavy White Square.
		/// </summary>
		public const string ExtremelyHeavyWhiteSquare_2 = "\uf0a6";

		/// <summary>
		/// White Square Containing Black Very Small Square.
		/// </summary>
		public const string WhiteSquareContainingBlackVerySmallSquare_2 = "\uf0a7";

		/// <summary>
		/// White Square Containing Black Small Square.
		/// </summary>
		public const string WhiteSquareContainingBlackSmallSquare_2 = "\uf0a8";

		/// <summary>
		/// White Square Containing Black Medium Square.
		/// </summary>
		public const string WhiteSquareContainingBlackMediumSquare_2 = "\uf0a9";

		/// <summary>
		/// Square Target.
		/// </summary>
		public const string SquareTarget_2 = "\uf0aa";

		/// <summary>
		/// Black Tiny Diamond.
		/// </summary>
		public const string BlackTinyDiamond_2 = "\uf0ab";

		/// <summary>
		/// Black Small Diamond.
		/// </summary>
		public const string BlackSmallDiamond_2 = "\uf0ac";

		/// <summary>
		/// Black Medium Diamond.
		/// </summary>
		public const string BlackMediumDiamond_3 = "\uf0ad";

		/// <summary>
		/// Black Diamond.
		/// </summary>
		public const string BlackDiamond_2 = "\uf0ae";

		/// <summary>
		/// White Diamond.
		/// </summary>
		public const string WhiteDiamond_2 = "\uf0af";

		/// <summary>
		/// White Diamond Containing Black Very Small Diamond.
		/// </summary>
		public const string WhiteDiamondContainingBlackVerySmallDiamond_2 = "\uf0b0";

		/// <summary>
		/// White Diamond Containing Black Small Diamond.
		/// </summary>
		public const string WhiteDiamondContainingBlackSmallDiamond_2 = "\uf0b1";

		/// <summary>
		/// White Diamond Containing Black Medium Diamond.
		/// </summary>
		public const string WhiteDiamondContainingBlackMediumDiamond_2 = "\uf0b2";

		/// <summary>
		/// Diamond Target.
		/// </summary>
		public const string DiamondTarget_2 = "\uf0b3";

		/// <summary>
		/// Black Tiny Lozenge.
		/// </summary>
		public const string BlackTinyLozenge_2 = "\uf0b4";

		/// <summary>
		/// Black Small Lozenge.
		/// </summary>
		public const string BlackSmallLozenge_2 = "\uf0b5";

		/// <summary>
		/// Black Medium Lozenge.
		/// </summary>
		public const string BlackMediumLozenge_2 = "\uf0b6";

		/// <summary>
		/// Black Lozenge.
		/// </summary>
		public const string BlackLozenge_2 = "\uf0b7";

		/// <summary>
		/// Lozenge.
		/// </summary>
		public const string Lozenge_2 = "\uf0b8";

		/// <summary>
		/// White Lozenge Containing Black Small Lozenge.
		/// </summary>
		public const string WhiteLozengeContainingBlackSmallLozenge_2 = "\uf0b9";

		/// <summary>
		/// Left Half Black Circle.
		/// </summary>
		public const string LeftHalfBlackCircle_2 = "\uf0ba";

		/// <summary>
		/// Right Half Black Circle.
		/// </summary>
		public const string RightHalfBlackCircle_2 = "\uf0bb";

		/// <summary>
		/// Top Half Black Circle.
		/// </summary>
		public const string TopHalfBlackCircle_2 = "\uf0bc";

		/// <summary>
		/// Bottom Half Black Circle.
		/// </summary>
		public const string BottomHalfBlackCircle_2 = "\uf0bd";

		/// <summary>
		/// Black Medium Square.
		/// </summary>
		public const string BlackMediumSquare_4 = "\uf0be";

		/// <summary>
		/// Black Medium Diamond.
		/// </summary>
		public const string BlackMediumDiamond_4 = "\uf0bf";

		/// <summary>
		/// Black Pentagon.
		/// </summary>
		public const string BlackPentagon_2 = "\uf0c0";

		/// <summary>
		/// Turned Black Pentagon.
		/// </summary>
		public const string TurnedBlackPentagon_2 = "\uf0c1";

		/// <summary>
		/// Horizontal Black Hexagon.
		/// </summary>
		public const string HorizontalBlackHexagon_2 = "\uf0c2";

		/// <summary>
		/// Black Hexagon.
		/// </summary>
		public const string BlackHexagon_2 = "\uf0c3";

		/// <summary>
		/// Horizontal Black Octagon.
		/// </summary>
		public const string HorizontalBlackOctagon_2 = "\uf0c4";

		/// <summary>
		/// Black Octagon.
		/// </summary>
		public const string BlackOctagon_2 = "\uf0c5";

		/// <summary>
		/// Thin Greek Cross.
		/// </summary>
		public const string ThinGreekCross_2 = "\uf0c6";

		/// <summary>
		/// Light Greek Cross.
		/// </summary>
		public const string LightGreekCross_2 = "\uf0c7";

		/// <summary>
		/// Medium Greek Cross.
		/// </summary>
		public const string MediumGreekCross_2 = "\uf0c8";

		/// <summary>
		/// Bold Greek Cross.
		/// </summary>
		public const string BoldGreekCross_2 = "\uf0c9";

		/// <summary>
		/// Very Bold Greek Cross.
		/// </summary>
		public const string VeryBoldGreekCross_2 = "\uf0ca";

		/// <summary>
		/// Very Heavy Greek Cross.
		/// </summary>
		public const string VeryHeavyGreekCross_2 = "\uf0cb";

		/// <summary>
		/// Extremely Heavy Greek Cross.
		/// </summary>
		public const string ExtremelyHeavyGreekCross_2 = "\uf0cc";

		/// <summary>
		/// Thin Saltire.
		/// </summary>
		public const string ThinSaltire_2 = "\uf0cd";

		/// <summary>
		/// Light Saltire.
		/// </summary>
		public const string LightSaltire_2 = "\uf0ce";

		/// <summary>
		/// Medium Saltire.
		/// </summary>
		public const string MediumSaltire_2 = "\uf0cf";

		/// <summary>
		/// Bold Saltire.
		/// </summary>
		public const string BoldSaltire_2 = "\uf0d0";

		/// <summary>
		/// Heavy Saltire.
		/// </summary>
		public const string HeavySaltire_2 = "\uf0d1";

		/// <summary>
		/// Very Heavy Saltire.
		/// </summary>
		public const string VeryHeavySaltire_2 = "\uf0d2";

		/// <summary>
		/// Extremely Heavy Saltire.
		/// </summary>
		public const string ExtremelyHeavySaltire_2 = "\uf0d3";

		/// <summary>
		/// Light Five Spoked Asterisk.
		/// </summary>
		public const string LightFiveSpokedAsterisk_2 = "\uf0d4";

		/// <summary>
		/// Medium Five Spoked Asterisk.
		/// </summary>
		public const string MediumFiveSpokedAsterisk_2 = "\uf0d5";

		/// <summary>
		/// Bold Five Spoked Asterisk.
		/// </summary>
		public const string BoldFiveSpokedAsterisk_2 = "\uf0d6";

		/// <summary>
		/// Heavy Five Spoked Asterisk.
		/// </summary>
		public const string HeavyFiveSpokedAsterisk_2 = "\uf0d7";

		/// <summary>
		/// Very Heavy Five Spoked Asterisk.
		/// </summary>
		public const string VeryHeavyFiveSpokedAsterisk_2 = "\uf0d8";

		/// <summary>
		/// Extremely Heavy Five Spoked Asterisk.
		/// </summary>
		public const string ExtremelyHeavyFiveSpokedAsterisk_2 = "\uf0d9";

		/// <summary>
		/// Light Six Spoked Asterisk.
		/// </summary>
		public const string LightSixSpokedAsterisk_2 = "\uf0da";

		/// <summary>
		/// Medium Six Spoked Asterisk.
		/// </summary>
		public const string MediumSixSpokedAsterisk_2 = "\uf0db";

		/// <summary>
		/// Bold Six Spoked Asterisk.
		/// </summary>
		public const string BoldSixSpokedAsterisk_2 = "\uf0dc";

		/// <summary>
		/// Heavy Six Spoked Asterisk.
		/// </summary>
		public const string HeavySixSpokedAsterisk_2 = "\uf0dd";

		/// <summary>
		/// Very Heavy Six Spoked Asterisk.
		/// </summary>
		public const string VeryHeavySixSpokedAsterisk_2 = "\uf0de";

		/// <summary>
		/// Extremely Heavy Six Spoked Asterisk.
		/// </summary>
		public const string ExtremelyHeavySixSpokedAsterisk_2 = "\uf0df";

		/// <summary>
		/// Light Eight Spoked Asterisk.
		/// </summary>
		public const string LightEightSpokedAsterisk_2 = "\uf0e0";

		/// <summary>
		/// Medium Eight Spoked Asterisk.
		/// </summary>
		public const string MediumEightSpokedAsterisk_2 = "\uf0e1";

		/// <summary>
		/// Bold Eight Spoked Asterisk.
		/// </summary>
		public const string BoldEightSpokedAsterisk_2 = "\uf0e2";

		/// <summary>
		/// Heavy Eight Spoked Asterisk.
		/// </summary>
		public const string HeavyEightSpokedAsterisk_2 = "\uf0e3";

		/// <summary>
		/// Very Heavy Eight Spoked Asterisk.
		/// </summary>
		public const string VeryHeavyEightSpokedAsterisk_2 = "\uf0e4";

		/// <summary>
		/// Light Three Pointed Black Star.
		/// </summary>
		public const string LightThreePointedBlackStar_2 = "\uf0e5";

		/// <summary>
		/// Three Pointed Black Star.
		/// </summary>
		public const string ThreePointedBlackStar_2 = "\uf0e6";

		/// <summary>
		/// Light Four Pointed Black Star.
		/// </summary>
		public const string LightFourPointedBlackStar_2 = "\uf0e7";

		/// <summary>
		/// Black Four Pointed Star.
		/// </summary>
		public const string BlackFourPointedStar_2 = "\uf0e8";

		/// <summary>
		/// Light Five Pointed Black Star.
		/// </summary>
		public const string LightFivePointedBlackStar_2 = "\uf0e9";

		/// <summary>
		/// Black Star.
		/// </summary>
		public const string BlackStar_2 = "\uf0ea";

		/// <summary>
		/// Six Pointed Black Star.
		/// </summary>
		public const string SixPointedBlackStar_2 = "\uf0eb";

		/// <summary>
		/// Medium Six Pointed Black Star.
		/// </summary>
		public const string MediumSixPointedBlackStar_2 = "\uf0ec";

		/// <summary>
		/// Eight Pointed Rectilinear Black Star.
		/// </summary>
		public const string EightPointedRectilinearBlackStar_2 = "\uf0ed";

		/// <summary>
		/// Heavy Eight Pointed Black Star.
		/// </summary>
		public const string HeavyEightPointedBlackStar_2 = "\uf0ee";

		/// <summary>
		/// Light Twelve Pointed Black Star.
		/// </summary>
		public const string LightTwelvePointedBlackStar_2 = "\uf0ef";

		/// <summary>
		/// Twelve Pointed Black Star.
		/// </summary>
		public const string TwelvePointedBlackStar_2 = "\uf0f0";

		/// <summary>
		/// Medium Three Pointed Pinwheel Star.
		/// </summary>
		public const string MediumThreePointedPinwheelStar_2 = "\uf0f1";

		/// <summary>
		/// Medium Four Pointed Pinwheel Star.
		/// </summary>
		public const string MediumFourPointedPinwheelStar_2 = "\uf0f2";

		/// <summary>
		/// Pinwheel Star.
		/// </summary>
		public const string PinwheelStar_2 = "\uf0f3";

		/// <summary>
		/// Six Pointed Pinwheel Star.
		/// </summary>
		public const string SixPointedPinwheelStar_2 = "\uf0f4";

		/// <summary>
		/// Heavy Twelve Pointed Pinwheel Star.
		/// </summary>
		public const string HeavyTwelvePointedPinwheelStar_2 = "\uf0f5";

		/// <summary>
		/// Light Four Pointed Black Cusp.
		/// </summary>
		public const string LightFourPointedBlackCusp_2 = "\uf0f6";

		/// <summary>
		/// Rotated Light Four Pointed Black Cusp.
		/// </summary>
		public const string RotatedLightFourPointedBlackCusp_2 = "\uf0f7";

		/// <summary>
		/// Reference Mark.
		/// </summary>
		public const string ReferenceMark_2 = "\uf0f8";

		/// <summary>
		/// Asterism.
		/// </summary>
		public const string Asterism_2 = "\uf0f9";
	}
}
